### PR TITLE
Add sample & doc for image_publisher.py

### PR DESCRIPTION
**Pull request by wkentaro**
**sample image**
image

### CODE REVIEW

**Comment by k-okada** [comment]
please also check at https://github.com/ros-perception/image_pipeline/pull/173, putting code to pustream as much as possible will be poweful solution of https://github.com/jsk-ros-pkg/jsk_recognition/issues/1683

**Comment by wkentaro** [comment]
> putting code to pustream as much as possible will be poweful solution of #1683

I agree with you that's true in most cases, but I'm not sure in ROS community.
The problem of #1683 is slow GitHub flow.
The maintainers' response in upstream repositories is too slow for me except for some repos (ros/ros_comm, ros/ros).

> please also check at ros-perception/image_pipeline#173

Yeah, I'm subscribing that thread, but no activity since January this year.

**Comment by wkentaro** [comment]
If you decide to move some codes in this package to upsream like ros-perception/opencv_apps, please tell me.
I think I can help it.

**Comment by k-okada** [comment]
>> please also check at ros-perception/image_pipeline#173
> Yeah, I'm subscribing that thread, but no activity since January this year.

please add any positive/negative comments on that PR,so that the PR seems active.

**Comment by wkentaro** [comment]
> please add any positive/negative comments on that PR,so that the PR seems active.

@k-okada I see.

**Comment by wkentaro** [comment]
Please merge this.

**Pull request merged**
