### PR TITLE
Various sort options for cluster point indices decomposer

### PR DESCRIPTION
**Pull request by wkentaro**
## Why?

We'd like to select largest object as the most interested object to pick.

- Input indices (green) (same as label)
- Z Axis (red) (top)
- Cloud size (blue) (largest)

sample_cluster_point_indices_decomposer_sort_by_x0 5

### CODE REVIEW

**Comment by k-okada** [comment]
numpy? https://travis-ci.org/jsk-ros-pkg/jsk_recognition/jobs/247644449

```

Errors     << jsk_recognition_utils:make /workspace/ros/ws_jsk_recognition/logs/jsk_recognition_utils/build.make.000.log
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /workspace/ros/ws_jsk_recognition/build/jsk_recognition_utils/python/jsk_recognition_utils/color.c:352:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
In file included from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1809:0,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from /workspace/ros/ws_jsk_recognition/build/jsk_recognition_utils/python/jsk_recognition_utils/nms.c:352:
/usr/local/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
CMakeFiles/jsk_recognition_utils.dir/src/grid_map.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
make[2]: *** [/workspace/ros/ws_jsk_recognition/devel/.private/jsk_recognition_utils/lib/libjsk_recognition_utils.so] Error 1
```
???

**Comment by wkentaro** [comment]
Maybe caused by `ccache`
```
CMakeFiles/jsk_recognition_utils.dir/src/grid_map.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
```

**Comment by wkentaro** [comment]
@k-okada You ought to know how to clear the cache of ccache. Could you please teach me?

**Comment by k-okada** [comment]
I do not know, unfortunately. may be you
https://github.com/jsk-ros-pkg/jsk_travis/pull/212

2017年6月28日(水) 13:05 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
Thanks, I found it.

```
ssh jenkins
sudo rm -rf /export/data1/ccache
```

**Pull request merged**
