### PR TITLE
[jsk_pcl_ros] remove wrong launch_manager in tabletop_object_detector.launch

### PR DESCRIPTION
**Pull request by knorth55**
remove `launch_manager` in `OrganizedMultiPlaneSegmentation`
this is wrong.

cc. @tohirose

### CODE REVIEW

**Comment by knorth55** [comment]
@k-okada can you review and merge this PR? the launch was pretty buggy with this wrong `launch_manager` arg.

**Comment by knorth55** [comment]
@k-okada can you merge this PR?

**Review by k-okada — COMMENTED** [review]
do we remove 
```
  <arg name="launch_manager" default="true" />
```
too?

**Comment by knorth55** [comment]
@k-okada no, we need `launch_manager` argument to disable nodelet manager.
current master branch disables `OrganizedMultiPlaneSegmentation` with `launch_manager` argument, which is not manager.

https://github.com/knorth55/jsk_recognition/blob/fix-tabletop-object-detector/jsk_pcl_ros/sample/tabletop_object_detector.launch#L26-L29

**Pull request merged**
