### PR TITLE
[jsk_perception] Test KMeans

### PR DESCRIPTION
**Pull request by wkentaro**
Modified:
  - jsk_perception/CMakeLists.txt
Added:
  - jsk_perception/test/kmeans.test

### CODE REVIEW

**Comment by k-okada** [comment]
is this image segmentation node?

**Comment by wkentaro** [comment]
no.

**Comment by k-okada** [comment]
what kmenas node  do?

**Comment by wkentaro** [comment]
ah, sorry, it does.
It does clustering image pixels with color, and returns the transformed image.

**Comment by k-okada** [comment]
I see, there is sample program in sample/cpp so may be we can put this on opencv_apps in future.
https://github.com/Itseez/opencv/blob/master/samples/cpp/kmeans.cpp

**Pull request merged**
