### PR TITLE
Use jsk_common on apt to test with ROS_DISTRO=jade

### PR DESCRIPTION
**Pull request by wkentaro**
Because it is released.
So .travis.rosinstall should be .travis.rosinstall.hydro

### CODE REVIEW

**Comment by wkentaro** [comment]
I'm wondering why the Travis test with ROS_DISTRO=jade is **so stable**.
https://travis-ci.org/jsk-ros-pkg/jsk_recognition/builds/165166783
image

**Comment by wkentaro** [comment]
Seems
- testing on jade is stable
- testing on indigo is unstable
screen shot 2016-10-07 at 1 12 38 am

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
```
testing on jade is stable
testing on indigo is unstable 
```
did you able to fix this? or indigo is unstable for some reason?

**Comment by wkentaro** [comment]
> did you able to fix this?

I found that fact by this PR.
I'm not sure the reason, and how to fix it.

**Pull request merged**
