### PR TITLE
Fix cluster point indices decomposer to make bounding box from cloud including nan

### PR DESCRIPTION
**Pull request by weiqiyang**
Fixes #2373
Includes #2373

### CODE REVIEW

**Comment by weiqiyang** [comment]
@knorth55 @pazeshun

**Comment by knorth55** [comment]
@weiqiyang Can you check and merge this PR https://github.com/weiqiyang/jsk_recognition/pull/1 ?

**Comment by knorth55** [comment]
@iory @pazeshun can you review for this?

**Comment by pazeshun** [comment]
@weiqiyang Sorry, but I force-pushed to your branch to include latest #2373

**Comment by pazeshun** [comment]
Travis test correctly failed in #2373 and passed in this PR.
@k-okada Could you review this?

**Pull request merged**
