### PR TITLE
Test Kinetic on Travis

### PR DESCRIPTION
**Pull request by wkentaro**
Related to https://github.com/jsk-ros-pkg/jsk_recognition/pull/2255

## Making the test pass

- [x] jsk_recognition_utils
- [x] checkerboard_detector
- [x] resized_image_transport
- [x] imagesift
- [x] jsk_perception
- [x] jsk_pcl_ros_utils
- [x] jsk_pcl_ros

### CODE REVIEW

**Comment by k-okada** [comment]
MergeOK, please let me know if Travis passed

**Comment by wkentaro** [comment]
@k-okada I see.

```
CMakeFiles/jsk_recognition_utils.dir/src/pcl_conversion_util.cpp.o: In function `jsk_recognition_utils::rangeImageToCvMat(pcl::RangeImage const&, cv::Mat&)':
pcl_conversion_util.cpp:(.text+0x19d): undefined reference to `pcl::visualization::FloatImageUtils::getColorForFloat(float, unsigned char&, unsigned char&, unsigned char&)'
pcl_conversion_util.cpp:(.text+0x1f1): undefined reference to `pcl::visualization::FloatImageUtils::getColorForFloat(float, unsigned char&, unsigned char&, unsigned char&)'
collect2: error: ld returned 1 exit status
make[2]: *** [/workspace/ros/ws_jsk_recognition/devel/.private/jsk_recognition_utils/lib/libjsk_recognition_utils.so] Error 1
make[1]: *** [CMakeFiles/jsk_recognition_utils.dir/all] Error 2
make: *** [all] Error 2
cd /workspace/ros/ws_jsk_recognition/build/jsk_recognition_utils; catkin build --get-env jsk_recognition_utils | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
```

**Comment by wkentaro** [comment]
Rebased with origin/master.

**Comment by wkentaro** [comment]
Now it passed! Please merge this with the *rebase-merge* after #2270 .

**Comment by k-okada** [comment]
to pass the test, i had to....
- we skipped several tests https://github.com/jsk-ros-pkg/jsk_recognition/issues/2272 (https://github.com/jsk-ros-pkg/jsk_recognition/pull/2276/commits/97b6586dd3623f60c196267618bd36b20a9b2bb6, https://github.com/jsk-ros-pkg/jsk_recognition/pull/2276/commits/ef03b7749a04ae64da98ca033e3d0cb0cbfff90a)
- install chainercv on docker (14.04, 16.04 ros-inidgo-pcl.1.8) `echo -e "FROM ros-ubuntu:14.04\nRUN pip install matplotlib==2.0.0 chainer==4.0.0 chainercv==0.9.0\nEXPOSE 22" | sudo docker build -t ros-ubuntu:14.04 -`,  see https://github.com/chainer/chainer/issues/4670, https://github.com/jsk-ros-pkg/jsk_recognition/pull/2268#issuecomment-383804409
- this is very weird, but link with deb version of `jsk_topic_tool` cause failure, which failed to initialize `pnh_` at https://github.com/jsk-ros-pkg/jsk_recognition/blob/1.2.5/resized_image_transport/src/image_resizer_nodelet.cpp#L8, so it seems fail to call `DiagnosticNodelet::onInit()` and `ConnectionBasedNodelet::onInit()`. It does not reproduce with source compiled package and deb package build on docker. So I have manually build `jsk_topic_tool` deb on decker and installed it.

**Comment by k-okada** [comment]
failing ... https://api.travis-ci.org/v3/job/371316490/log.txt, restart travis
```
jsk_recognition_utils/test_results/jsk_recognition_utils/rosunit-test_add_bounding_box_array.xml: 1 tests, 0 errors, 1 failures, 0 skipped
```

**Comment by wkentaro** [comment]
I think the first and second issue can be fixed by using catkin_virtualenv with installing specific version dependencies.  But the third one seems very difficult to resolve.

**Pull request merged**
