### PR TITLE
[Major Release] Move service files: jsk_pcl_ros -> jsk_recognition_msgs to reuse

### PR DESCRIPTION
**Pull request by wkentaro**
To remove dependency of jsk_interactive_marker on jsk_pcl_ros.

### CODE REVIEW

**Comment by k-okada** [comment]
I'm afraid this will affect large set of applications,,,

**Comment by wkentaro** [comment]
> I'm afraid this will affect large set of applications,,,

So currently I'm using cmake macro for this migration.
The macro will generate message files both in jsk_recognition_msgs and jsk_pcl_ros.

**Comment by wkentaro** [comment]
**Please merge this!**

**Comment by k-okada** [comment]
Any comment on this pr? @mmurooka @YuOhara @iory ?

**Comment by mmurooka** [comment]
Lots of source codes using jsk_pcl_ros.srvs must be updated, right?

**Comment by wkentaro** [comment]
> Lots of source codes using jsk_pcl_ros.srvs must be updated, right?

No: https://github.com/jsk-ros-pkg/jsk_recognition/pull/1827#issuecomment-238073208
It generates the messages both for jsk_pcl_ros and jsk_recognition_msgs. This takes more build time, but won't break the API (I think).

**Comment by mmurooka** [comment]
If currently working program does not get bad effect, this PR is OK.

**Comment by wkentaro** [comment]
> If currently working program does not get bad effect, this PR is OK.

The whole bad effects can't be cover by only me.
Please describe about your experience or knowledge: for example
- you usually use the service files in euslisp code
- that is used in XXXX package
- that is used by demo code in euslib

You said below, so you mean you usually the jsk_pcl_ros.srvs?

> Lots of source codes using jsk_pcl_ros.srvs must be updated, right?

**Comment by mmurooka** [comment]
In drc_task_common, maybe following is the only code using jsk_pcl_ros/srvs as log as I did grep.
https://github.com/jsk-ros-pkg/jsk_demos/blob/master/jsk_2015_06_hrp_drc/drc_task_common/src/drc_task_common/manipulation_data_server.cpp#L251

If my memory is correct,  `jsk_pcl_ros/EuclideanSegment` is used in euslisp code of PR2 fridge demo.

**Comment by k-okada** [comment]
ok, before we merge this PR what is the plan? when we stop using cmake
macro that generate srv file under both jsk_pcl_ros.srv and
jsk_recognition.srv? and who will  fix codes using jsk_pcl_ros.srv? until
when?

--
◉ Kei Okada


2016-10-22 3:09 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
> before we merge this PR what is the plan? 

I think this PR can be closed.
I changed the mind of migration plan: https://github.com/jsk-ros-pkg/jsk_recognition/pull/1827#issuecomment-255435600 , if you have other ideas please tell me.

> who will  fix codes using jsk_pcl_ros.srv? until
when?

I sent PR for fixing that all jsk-ros-pkg and start-jsk packages.
- https://github.com/jsk-ros-pkg/jsk-ros-pkg-unreleased/pull/73
- https://github.com/jsk-ros-pkg/euslib/pull/219
- https://github.com/jsk-ros-pkg/jsk_visualization/pull/644
- https://github.com/jsk-ros-pkg/jsk_smart_apps/pull/68
- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1917
- https://github.com/jsk-ros-pkg/jsk_demos/pull/1204
- https://github.com/jsk-ros-pkg/jsk_control/pull/637

**Comment by k-okada** [comment]
moved to #1914 , for now

**Comment by k-okada** [comment]
> I sent PR for fixing that all jsk-ros-pkg and start-jsk packages.


all done, which PR to be merged next

**Comment by wkentaro** [comment]
Thank you for the cooperation.
The next PR to be merged is https://github.com/jsk-ros-pkg/jsk_visualization/pull/623, which is a goal of this migration

**Comment by k-okada** [comment]
> Remove jsk_pcl_ros/srv.

we also need this.

**Comment by wkentaro** [comment]
Ok, I summarized them: https://github.com/jsk-ros-pkg/jsk_recognition/issues/1980

**Pull request closed without merging**
