### PR TITLE
mask_rcnn_instance_segmentation: support loading yaml from file

### PR DESCRIPTION
**Pull request by furushchev**
- Support loading labels from yaml file.
- Add option 'anchor_scales', 'min_size', 'max_size' to pass the model
- Support to change 'score_thresh' dynamically

### CODE REVIEW

**Comment by furushchev** [comment]
@k-okada

- Add option 'anchor_scales', 'min_size', 'max_size' to pass the model

The values of parameters `anchor_scales`, `min_size` etc. actually depend on which pretrained model is loaded and now are fixed for `mask_rcnn_resnet50_voc_20180516.npz` model which is used in sample launch file (https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/sample/sample_mask_rcnn_instance_segmentation.launch).
However, when we use another model (e.g. learned model by using https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/scripts/train_mask_rcnn.py), we must change the parameters.

- Support loading labels from yaml file.

This feature is necessary when the yaml file is located in a remote machine.

If I remember correctly, we have an example model learned by using `train_mask_rcnn.py` and photos taken in `73b2 kitchen`, and I think it is good to add an example for using this model.
@iory Could you add a sample launch file to use 73b2 model?

**Comment by knorth55** [comment]
@iory kindly ping

**Comment by iory** [comment]
Please check https://github.com/jsk-ros-pkg/jsk_recognition/pull/2423

**Comment by k-okada** [comment]
@iory @knorth55 please resolve conflicts

**Comment by YutoUchimi** [comment]
I resoloved conflict.
Waiting for #2448 and #2446 to pass travis test.

**Comment by YutoUchimi** [comment]
Travis passed!

**Pull request merged**
