### PR TITLE
[jsk_pcl_ros] Do not use deprecated utility headers

### PR DESCRIPTION
**Pull request by garaemon**
see #1430

### CODE REVIEW

**Comment by garaemon** [comment]
@wkentaro 
```
[jsk_perception] [ROSUNIT] Outputting test results to /workspace/ros/ws_jsk_recognition/build/jsk_perception/test_results/jsk_perception/rostest-test_test_label_image_decomposer_slop.xml 
[jsk_pcl_ros] ... logging to /workspace/jsk-ros-pkg/jsk_recognition/log/rostest-ddbc47f281b4-48815.log 
[jsk_pcl_ros] ... logging to /workspace/jsk-ros-pkg/jsk_recognition/log/rostest-ddbc47f281b4-48814.log 
[jsk_pcl_ros] ... logging to /workspace/jsk-ros-pkg/jsk_recognition/log/rostest-ddbc47f281b4-48813.log 
[jsk_pcl_ros] Traceback (most recent call last):                                
[jsk_pcl_ros]   File "/opt/ros/jade/share/rostest/cmake/../../../bin/rostest", line 36, in <module> 
[jsk_pcl_ros]     rostestmain()                                                 
[jsk_pcl_ros]   File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/__init__.py", line 268, in rostestmain 
[jsk_pcl_ros] Traceback (most recent call last):                                
[jsk_pcl_ros]   File "/opt/ros/jade/share/rostest/cmake/../../../bin/rostest", line 36, in <module> 
[jsk_pcl_ros]     rostestmain()                                                 
[jsk_pcl_ros]   File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/__init__.py", line 268, in rostestmain 
[jsk_pcl_ros] Traceback (most recent call last):                                
[jsk_pcl_ros]   File "/opt/ros/jade/share/rostest/cmake/../../../bin/rostest", line 36, in <module> 
[jsk_pcl_ros]     rostestmain()                                                 
[jsk_pcl_ros]   File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/__init__.py", line 268, in rostestmain 
[jsk_pcl_ros]     _main()                                                       
[jsk_pcl_ros]   File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/rostest_main.py", line 159, in rostestmain 
[jsk_pcl_ros]     _main()                                                       
[jsk_pcl_ros]       File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/rostest_main.py", line 159, in rostestmain 
[jsk_pcl_ros] _main()                                                           
[jsk_pcl_ros]   File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/rostest_main.py", line 159, in rostestmain 
[jsk_pcl_ros]     testCase = rostest.runner.createUnitTest(pkg, test_file, options.reuse_master, options.clear, options.results_base_dir) 
[jsk_pcl_ros]   File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/runner.py", line 229, in createUnitTest 
[jsk_pcl_ros]     testCase = rostest.runner.createUnitTest(pkg, test_file, options.reuse_master, options.clear, options.results_base_dir) 
[jsk_pcl_ros]   File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/runner.py", line 229, in createUnitTest 
[jsk_pcl_ros]     testCase = rostest.runner.createUnitTest(pkg, test_file, options.reuse_master, options.clear, options.results_base_dir) 
[jsk_pcl_ros]   File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/runner.py", line 229, in createUnitTest 
[jsk_pcl_ros]     config = roslaunch.parent.load_config_default([test_file], None) 
[jsk_pcl_ros]     config = roslaunch.parent.load_config_default([test_file], None) 
[jsk_pcl_ros]       File "/opt/ros/jade/lib/python2.7/dist-packages/roslaunch/config.py", line 455, in load_config_default 
[jsk_pcl_ros] config = roslaunch.parent.load_config_default([test_file], None)  
[jsk_pcl_ros]   File "/opt/ros/jade/lib/python2.7/dist-packages/roslaunch/config.py", line 455, in load_config_default 
[jsk_pcl_ros]   File "/opt/ros/jade/lib/python2.7/dist-packages/roslaunch/config.py", line 455, in load_config_default 
[jsk_pcl_ros]         raise RLException(e)                                      
[jsk_pcl_ros]     raise RLException(e)                                          
[jsk_pcl_ros] roslaunch.core.RLExceptionraise RLException(e)                    
[jsk_pcl_ros] : error loading <rosparam> tag:  
```

**Comment by wkentaro** [comment]
the error log is too short for me to analyze the cause of the problem.

**Comment by wkentaro** [comment]
rostest can fail if there are some problem when installing dependencies on `rosdep` fase.
However, currently rosdep install ignores errors with `-r` option, so that does not work for testing.

**Comment by garaemon** [comment]
retried 3times but never succeeded

https://travis-ci.org/jsk-ros-pkg/jsk_recognition/jobs/97627226#L9416

**Comment by garaemon** [comment]
```
file does not exist [/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/test_data/2015-11-04-19-37-29_baxter-kiva-object-in-hand-cloud/rosparam.yaml] 
```

**Comment by wkentaro** [comment]
sorry, I will fix it.

**Comment by wkentaro** [comment]
@garaemon Please merge https://github.com/garaemon/jsk_recognition/pull/1.

**Pull request merged**
