### PR TITLE
[jsk_pcl_ros_utils] Fixed md5sum version of visualizatoin msgs in bag

### PR DESCRIPTION
**Pull request by iory**
# What is this?

Fixed md5sum version of visualizatoin msgs in bagfile for test.
Versions prior to kinetic have different `visualization_msgs/MarkerArray` md5sum.

### CODE REVIEW

**Comment by k-okada** [comment]
Thank you, just of of curiosity, does the old bagfile block test code?  

c.f. https://github.com/jsk-ros-pkg/jsk_robot/pull/898

**Comment by iory** [comment]
This is the loophole for `test_topic_published.py`.
The following is the test of `evaluate_voxel_segmentation_by_gt` in docker environment.

```
root@zinn:/catkin_ws/src/jsk_recognition/jsk_pcl_ros_utils# rostest jsk_pcl_ros_utils evaluate_voxel_segmentation_by_gt_box.test
... logging to /root/.ros/log/rostest-zinn-8154.log
[ROSUNIT] Outputting test results to /root/.ros/test_results/jsk_pcl_ros_utils/rostest-test_evaluate_voxel_segmentation_by_gt_box.xml
/usr/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[WARN] [1652000795.006091, 0.000000]: /use_sim_time is specified and rostime is 0, /clock is published?
[ERROR] [1652000796.054424526, 1486474052.747239256]: Client [/evaluate_voxel_segmentation_by_gt_box] wants topic /octree_voxel_grid/output_marker_array to have datatype/md5sum [visualization_msgs/MarkerArray/d155b9ce5188fbaf89745847fd5882d7], but our version has [visualization_msgs/MarkerArray/90da67007c26525f655c1c269094e39f]. Dropping connection.
Traceback (most recent call last):
  File "/opt/ros/melodic/share/jsk_tools/src/test_topic_published.py", line 102, in <module>
    rostest.run(PKG, NAME, TestTopicPublished, sys.argv)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rostest/__init__.py", line 146, in rosrun
    result = rosunit.create_xml_runner(package, test_name, result_file).run(suite)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosunit/xmlrunner.py", line 253, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/opt/ros/melodic/share/jsk_tools/src/test_topic_published.py", line 97, in test_published
    rospy.sleep(0.01)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/timer.py", line 163, in sleep
    raise rospy.exceptions.ROSTimeMovedBackwardsException(time_jump)
rospy.exceptions.ROSTimeMovedBackwardsException: ROS time moved backwards
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/timer.py", line 228, in run
    r.sleep()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/timer.py", line 103, in sleep
    sleep(self._remaining(curr_time))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/timer.py", line 163, in sleep
    raise rospy.exceptions.ROSTimeMovedBackwardsException(time_jump)
ROSTimeMovedBackwardsException: ROS time moved backwards

[Testcase: testtest_evaluate_voxel_segmentation_by_gt_box] ... ok

[ROSTEST]-----------------------------------------------------------------------


SUMMARY
 * RESULT: SUCCESS
 * TESTS: 0
 * ERRORS: 0
 * FAILURES: 0

```

`rospy.sleep` cause the error `ROSTimeMovedBackwardsException`.
Since test is not executed correctly, test itself becomes success. (`RESULT: SUCCESS`)

**Comment by iory** [comment]
I added the code and comments for avoiding the above errors in `jsk_tools/test_topic_published.py` .
https://github.com/jsk-ros-pkg/jsk_common/pull/1725/commits/15889adf75e486bf4f4471acc08030d628b1f8d4

**Comment by k-okada** [comment]
I have fixed this problem by https://github.com/jsk-ros-pkg/jsk_recognition/commit/426b3d93e28eabe9dd77a3c7e41707f32e280d8d, how do you think? @iory

**Pull request closed without merging**
