### PR TITLE
[jsk_perception] #2722 has broken backward compatibility that is necessary for existing demonstration

### PR DESCRIPTION
**Pull request by tkmtnt7000**
I added test code about point_pose_extractor with group namespace.
First, I expect to fail `point_pose_extractor_group_ns.test` successfully.

By #2722, we encountered something wrong when we use point_pose_extractor with group namespace.
That change is so critical that some existing demonstrations such as PR2 pick object demo (冷蔵庫デモ) do not work.

https://github.com/jsk-ros-pkg/jsk_demos/blob/525607131711ad9ad1420d7b05e458408a9b70af/detect_cans_in_fridge_201202/launch/detect_fridge.launch#L36-L55
For example in the code above, we expect `/kinect_head/rgb/ObjectDetection` to publish from point_pose_extractor, but now `/ObjectDetection` publishes.

c.f. https://github.com/search?q=repo%3Ajsk-ros-pkg%2Fjsk_demos+%2FObjectDetection&type=code

cc: @Kanazawanaoaki @pazeshun @nakane11

### CODE REVIEW

**Comment by nakane11** [comment]
@tkmtnt7000 
I am sorry to have troubled you. I think #2779 fixes it.

**Comment by tkmtnt7000** [comment]
@nakane11 
Don't worry. And thank you very much for your very quick response!!

**Comment by tkmtnt7000** [comment]
Test successfully failed when I added https://github.com/jsk-ros-pkg/jsk_recognition/pull/2778/commits/151cf6f09071f4e1efc6f428631b59443e442eeb

Besides, #2779 with point_pose_extractor_group_ns.test passed all test.

**Comment by nakane11** [comment]
Sorry, I shouldn’t have used git rebase to keep commit id...

**Pull request closed without merging**
