### PR TITLE
[jsk_pcl_ros] Do not compile build_check.cpp in normal compilation time, just in run_tests

### PR DESCRIPTION
**Pull request by garaemon**
Little bit a tricky, do not compile build_check.cpp in normal compilation because ros buildfarm looks fail
to build it (memory starvation?).

http://jenkins.ros.org/view/IbinS64/job/ros-indigo-jsk-pcl-ros_binarydeb_saucy_amd64/69/console
```
[ 56%] Building CXX object CMakeFiles/build_check.dir/build_check.cpp.o
/usr/lib/ccache/c++   -DROSCONSOLE_BACKEND_LOG4CXX -DROS_PACKAGE_NAME=\"jsk_pcl_ros\" -DUSE_OLD_YAML -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -D_FORTIFY_SOURCE=2   -Wno-deprecated -fopenmp -O2 -g -DNDEBUG -I/tmp/buildd/ros-indigo-jsk-pcl-ros-0.3.5-0saucy-20150910-0811/obj-x86_64-linux-gnu/devel/include -I/usr/include/vtk-5.8 -I/usr/include/opencv -I/tmp/buildd/ros-indigo-jsk-pcl-ros-0.3.5-0saucy-20150910-0811/include -I/opt/ros/indigo/include -I/usr/include/eigen3 -I/usr/include/pcl-1.7 -I/usr/include/ni -I/usr/include/qhull    -O2 -g -o CMakeFiles/build_check.dir/build_check.cpp.o -c /tmp/buildd/ros-indigo-jsk-pcl-ros-0.3.5-0saucy-20150910-0811/obj-x86_64-linux-gnu/build_check.cpp
Build timed out (after 120 minutes). Marking the build as aborted.
```

### CODE REVIEW

**Comment by garaemon** [comment]
Strange error on jenkins

```
+ wstool info -t .
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wstool/common.py", line 283, in run
    result_dict = self.worker.do_work()
  File "/usr/lib/python2.7/dist-packages/wstool/multiproject_cmd.py", line 470, in do_work
    path_spec = self.element.get_versioned_path_spec(fetch=fetch)
  File "/usr/lib/python2.7/dist-packages/wstool/config_elements.py", line 414, in get_versioned_path_spec
    remote_revision = self._get_vcsc().get_remote_version(fetch=fetch)
AttributeError: 'GitClient' object has no attribute 'get_remote_version'
ERROR in config: Error processing 'jsk_recognition' : 'GitClient' object has no attribute 'get_remote_version'
```

**Comment by garaemon** [comment]
0.3.6 has been released

**Comment by wkentaro** [comment]
need update the name of .rosinstall also. (it has been changed to .travis.rosinstall)
https://github.com/jsk-ros-pkg/jsk_travis/pull/136

**Comment by garaemon** [comment]
@wkentaro Could you update other repos too?

**Comment by wkentaro** [comment]
alright.

**Comment by garaemon** [comment]
I update jsk_common

**Pull request merged**
