### PR TITLE
Upgrade jsk_travis: 0.4.9 -> 0.4.10

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
I'll merge #1734,
BTW I have restarted
```
     - ROS_DISTRO=indigo USE_DEB=true BEFORE_SCRIPT='$CI_SOURCE_PATH/.travis_before_script_released_testing.bash' ROS_REPOSITORY_PATH="http://packages.ros.org/ros/ubuntu"
```
several times, but still failng

**Comment by wkentaro** [comment]
What do you mean?

**Comment by k-okada** [comment]
https://travis-ci.org/jsk-ros-pkg/jsk_recognition/jobs/135821291 test is still failing,

**Comment by wkentaro** [comment]
I think that is unrelated to this PR..

**Comment by wkentaro** [comment]
and I cannot fix it without the error messages.

**Comment by wkentaro** [comment]
Please merge this.

**Pull request merged**
