### PR TITLE
Fix test failures of jsk_perception on Travis

### LINKED ISSUE #1656: jsk_travis is still old: 0.4.2
## Issue

0.4.2 has below issues, so we need fix it.

- https://github.com/jsk-ros-pkg/jsk_travis/issues/254
- https://github.com/jsk-ros-pkg/jsk_travis/issues/253

## Solution

Upgrade jsk_travis submodule.

**PRs**

- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1640
- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1641

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #1656

## Why?

This has been overlooked by https://github.com/jsk-ros-pkg/jsk_travis/issues/254 and https://github.com/jsk-ros-pkg/jsk_travis/issues/253 .

## Todo

- [x] Fix build failures of jsk_perception because of unconfigured dependency on image_view2 (58ca9a5) (https://travis-ci.org/jsk-ros-pkg/jsk_recognition/jobs/127032032)
- [x] Fix unstableness of tests in jsk_perception

### CODE REVIEW

**Comment by wkentaro** [comment]
```
] -- run_tests.py: verify result "/workspace/ros/ws_jsk_recognition/build/jsk_perception/test_results/jsk_perception/rostest-test_colorize_labels.xml"




                                                                                
[jsk_perception:make] Cannot find results, writing failure results to '/workspace/ros/ws_jsk_recognition/build/jsk_perception/test_results/jsk_perception/MISSING-rostest-test_colorize_labels.xml'




                                                                                
[jsk_perception:make] make[3]: Leaving directory `/workspace/ros/ws_jsk_recognition/build/jsk_perception'


```

**Comment by wkentaro** [comment]
image

Test with opencv3 won't pass.

**Comment by wkentaro** [comment]
As temporary operation, I move the opencv3 test to allow failures section. Maybe I will fix the test later.

**Comment by wkentaro** [comment]
close/reopen to trigger travis again

**Comment by wkentaro** [comment]
@k-okada Please merge this.
But unexpectedly I can push button of merge pull request.

**Comment by k-okada** [comment]
As we discussed yesterday, I added write permission to all uses, that may change behavior

**Comment by k-okada** [comment]
Changed configuration , can you still able to push merge button?

2016年5月7日土曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> @k-okada <https://github.com/k-okada> Please merge this.
> But unexpectedly I can push button of merge pull request.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1641#issuecomment-217601710>
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
No, it works as expected.
screen shot 2016-05-07 at 1 13 20 pm

**Pull request merged**
