### PR TITLE
USE_DEB=true on travis (this is to avoid regression in jsk_common)

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
After test is passed, please merge this first.

**Comment by wkentaro** [comment]
```[jsk_pcl_ros] FAILURE: Package [jsk_tools] for test node [jsk_tools/test_stdout.py] does not exist 

[jsk_pcl_ros]   File "/usr/lib/python2.7/unittest/case.py", line 331, in run    

[jsk_pcl_ros]     testMethod()                                                  

[jsk_pcl_ros]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 93, in fn 

[jsk_pcl_ros]     self.fail(message)                                            

[jsk_pcl_ros]   File "/usr/lib/python2.7/unittest/case.py", line 412, in fail   

[jsk_pcl_ros]     raise self.failureException(msg)                              
```

**Comment by wkentaro** [comment]
Need to wait for release of jsk_common.

**Comment by garaemon** [comment]
```
[jsk_perception] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/sparse_image_encoder.cpp: In member function 'void jsk_p
erception::SparseImageEncoder::do_work(const ImageConstPtr&, std::string)': 
[jsk_perception] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/sparse_image_encoder.cpp:69:9: warning: unknown conversi
on type character 0xa in format [-Wformat] 
[jsk_perception] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/sparse_image_encoder.cpp: In member function 'void jsk_p
erception::SparseImageEncoder::subscribe()': 
[jsk_perception] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/sparse_image_encoder.cpp:87:5: error: 'jsk_topic_tools' 
has not been declared 
```

**Comment by garaemon** [comment]
need https://github.com/jsk-ros-pkg/jsk_common/pull/1276

**Comment by garaemon** [comment]
USE_DEB should be true for hydro

**Comment by garaemon** [comment]
```
[jsk_pcl_ros]   Could not find a package configuration file provided by "ml_classifiers" 
[jsk_pcl_ros]   with any of the following names:                                
[jsk_pcl_ros]                                                                   
[jsk_pcl_ros]     ml_classifiersConfig.cmake                                    
[jsk_pcl_ros]     ml_classifiers-config.cmake                                   
[jsk_pcl_ros]                                                                   
[jsk_pcl_ros]   Add the installation prefix of "ml_classifiers" to CMAKE_PREFIX_PATH or set 
[jsk_pcl_ros]   "ml_classifiers_DIR" to a directory containing one of the above files.  If 
[jsk_pcl_ros]   "ml_classifiers" provides a separate development package or SDK, be sure it 
[jsk_pcl_ros]   has been installed.                                             
[jsk_pcl_ros] Call Stack (most recent call first):                              
[jsk_pcl_ros]   CMakeLists.txt:33 (find_package)       
```

**Comment by garaemon** [comment]
USE_DEB:=true does not work for

* hydro: not updated anymore
* jade: ml_classifiers are not maintained anymore

**Comment by wkentaro** [comment]
Ok I will change these. 
maybe the dependency on ml_classifier can removed because that library is not so useful actually.

**Comment by garaemon** [comment]
> maybe the dependency on ml_classifier can removed because that library is not so useful actually.

see #1385

**Comment by garaemon** [comment]
@wkentaro 
jsk_recognition may need the latest jsk_common.

Can you compile only jsk_common?
I don't want to compile assimp...

**Comment by wkentaro** [comment]
> Can you compile only jsk_common?

What do u mean? I should check if there is no error ?

**Comment by garaemon** [comment]
> What do u mean? I should check if there is no error ?
>  Hide all checks

on hydro, install jsk_3rdparty from deb and compile jsk_common from source.

**Comment by wkentaro** [comment]
so why should I compile jsk_common?

**Comment by garaemon** [comment]
jsk_recognition depends on the latest jsk_topic_tools

**Comment by wkentaro** [comment]
> jsk_recognition depends on the latest jsk_topic_tools

yeah, I understand about it. But for what should I compile jsk_common on my PC? and what should I check?

**Comment by garaemon** [comment]
> But for what should I compile jsk_common on my PC?

on your pc? for jsk_recognition.

I mean on travis, we cannot use shadow-fixed jsk_common packages for hydro.

**Comment by wkentaro** [comment]
I thought you mean I should compile jsk_common on my PC by below:
> Can you compile only jsk_common?
I don't want to compile assimp...

Now I understand.

**Comment by k-okada** [comment]
for hydro users, from 0.3.9, we no longer able to compile jsk_recognition itself, we need un released jsk_tools. This is a big change so I think I should have to use 0.4.x version...

**Comment by wkentaro** [comment]
> for hydro users, from 0.3.9, we no longer able to compile jsk_recognition itself

really, I didn't know that.

> we need un released jsk_tools.

What do you mean? Do you mean remove jsk_tools in apt release?

>  This is a big change so I think I should have to use 0.4.x version...

what do you mean? Do you mean we need release 0.4.0 as next minor release of jsk_recognition?

**Comment by k-okada** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1314 requries jsk_tools which is not released on apt, so I think you can not compile jsk_recognitoin from source, unless you also have jsk_tools source tree, is it correct, I think this was a big change. Just to notify everyone who did not aware of that (including me)

> what do you mean? Do you mean we need release 0.4.0 as next minor release of jsk_recognition?
may be this is too late, now we have 0.3.21 ....

**Comment by wkentaro** [comment]
> #1314 requries jsk_tools which is not released on apt

I think so.

**Pull request merged**
