### PR TITLE
[imagesift] INFO -> DEBUG to remove verbose output

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
```
[downward] CMake Error at downward-stamp/download-downward.cmake:22 (message):
[downward]   error: downloading
[downward]   'https://cdn.rawgit.com/jsk-ros-pkg/archives/master/Fast-Downward-f33d3b65601f.tar.gz'
[downward]   failed
[downward]
[downward]     status_code: 18
[downward]     status_string: "Transferred a partial file"
[downward]     log: Hostname was NOT found in DNS cache
[downward]     Trying 198.232.124.74...
[downward]
[downward]   Connected to cdn.rawgit.com (198.232.124.74) port 443 (#0)
[downward]
[downward]   successfully set certificate verify locations:
[downward]
[downward]     CAfile: none
[downward]     CApath: /etc/ssl/certs
[downward]
[downward]   SSLv3, TLS handshake, Client hello (1):
[downward]
[downward]
[downward]
[downward]
[downward]
[downward] make[2]: *** [downward-prefix/src/downward-stamp/downward-download] Error 1
[downward] make[1]: *** [CMakeFiles/downward.dir/all] Error 2
[downward] make: *** [all] Error 2
[downward] <== '/workspace/ros/ws_jsk_recognition/build/downward/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' failed with return code '2'
Failed   <== downward                 [ 4 minutes and 6.3 seconds ]
[
```

**Comment by garaemon** [comment]
Why does it download downwards?
I believe apt package will be used.

**Comment by wkentaro** [comment]
on jade
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/.travis.rosinstall.jade#L3

**Comment by garaemon** [comment]
I see. jsk_3rdparty should be released on jade by these PRs.
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/47
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/48

**Pull request merged**
