### PR TITLE
[docs][color_histogram_classifier] add tutorials

### PR DESCRIPTION
**Pull request by furushchev**
### Add docs
- [x] how to learn histogram
- [x] how to start program with learnt histogram
- [x] how to visualize result

### Minor fix
- [x] change BG color of histogram graph to light gray to clearly show the bar of white color histogram
- [x] update sample launch file
- [x] add sample rviz config

### CODE REVIEW

**Comment by furushchev** [comment]
This now requires https://github.com/jsk-ros-pkg/jsk_visualization/pull/669 to be released

**Comment by furushchev** [comment]
@k-okada Thanks for merging!
BTW, is there any trigger to sync `jsk-docs` with this repos?

**Comment by k-okada** [comment]
maybe we have to trigger by our self, right ? @wkentaro 
https://readthedocs.org/projects/jsk-docs/builds/

**Comment by wkentaro** [comment]
I added cron job in Jenkins using root user.
It triggers its build every 10 minutes.

**Pull request merged**
