### PR TITLE
[jsk_pcl_ros] Use jsk_data download_data func for test_data

### PR DESCRIPTION
**Pull request by knorth55**
same as #1627 
Depends on https://github.com/jsk-ros-pkg/jsk_common/pull/1383

### CODE REVIEW

**Comment by k-okada** [comment]
should we merge this or #1627?

**Comment by knorth55** [comment]
both
#1627 is for jsk_perception and this is for jsk_pcl_ros

**Comment by k-okada** [comment]
ok, will merge after jsk_common releaed

**Comment by knorth55** [comment]
please merge this

**Pull request merged**
