### PR TITLE
libcmt: Node to track object on 2D image: ConsensusTracking

### PR DESCRIPTION
**Pull request by wkentaro**
Close #1869 
Close #1537 

Waiting for https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/74

### CODE REVIEW

**Comment by wkentaro** [comment]
sample_consensus_tracking

**Comment by wkentaro** [comment]
```
[jsk_pcl_ros] flags:   -Wno-deprecated -fopenmp 

[jsk_perception] In file included from /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/consensus_tracking.cpp:46:0: 

[jsk_perception] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/include/jsk_perception/consensus_tracking.h:40:24: fatal error: libcmt/CMT.h: No such file or directory 
```

**Comment by k-okada** [comment]
```
$ dpkg -L ros-indigo-libcmt
/.
/opt
/opt/ros
/opt/ros/indigo
/opt/ros/indigo/lib
/opt/ros/indigo/lib/pkgconfig
/opt/ros/indigo/lib/pkgconfig/libcmt.pc
/opt/ros/indigo/share
/opt/ros/indigo/share/libcmt
/opt/ros/indigo/share/libcmt/cmake
/opt/ros/indigo/share/libcmt/cmake/libcmtConfig-version.cmake
/opt/ros/indigo/share/libcmt/cmake/libcmtConfig.cmake
/opt/ros/indigo/share/libcmt/package.xml
/usr
/usr/share
/usr/share/doc
/usr/share/doc/ros-indigo-libcmt
/usr/share/doc/ros-indigo-libcmt/changelog.Debian.gz
/tmp
/tmp/binarydeb
/tmp/binarydeb/ros-indigo-libcmt-2.0.14
/tmp/binarydeb/ros-indigo-libcmt-2.0.14/obj-x86_64-linux-gnu
/tmp/binarydeb/ros-indigo-libcmt-2.0.14/obj-x86_64-linux-gnu/devel
/tmp/binarydeb/ros-indigo-libcmt-2.0.14/obj-x86_64-linux-gnu/devel/include
/tmp/binarydeb/ros-indigo-libcmt-2.0.14/obj-x86_64-linux-gnu/devel/include/libcmt
/tmp/binarydeb/ros-indigo-libcmt-2.0.14/obj-x86_64-linux-gnu/devel/include/libcmt/CMT.h
/tmp/binarydeb/ros-indigo-libcmt-2.0.14/obj-x86_64-linux-gnu/devel/lib
/tmp/binarydeb/ros-indigo-libcmt-2.0.14/obj-x86_64-linux-gnu/devel/lib/libcmt.so
/tmp/binarydeb/ros-indigo-libcmt-2.0.14/obj-x86_64-linux-gnu/devel/lib/pkgconfig
/tmp/binar
```
I have installed include files to different location,,,
https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/71/files
did I create libcmt-release package somewhere??

--
◉ Kei Okada


2016-10-16 0:46 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by k-okada** [comment]
need to wait https://github.com/jsk-ros-pkg/jsk_3rdparty/pull/77

**Comment by k-okada** [comment]
fixed conflict in #1918

**Pull request closed without merging**
