### PR TITLE
[jsk_perception] Roslint test for cpp sources (it does not exit 1 when run_tests)

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by garaemon** [comment]
hmm, is it good idea to change existing code to satisfy lint?

roslint style is 
```
if (...) 
{
  ...
}
```

But almost jsk_recognition code follow the style like
```
if (...) {
}
```

**Comment by wkentaro** [comment]
I see, so maybe I should ignore that syntax warning.

**Comment by wkentaro** [comment]
Current style is
```
if () {
}
else {
}
```
?
but
```
void foo ()
{
}
```
?

Am I right?

**Comment by wkentaro** [comment]
Iit does not mark as fail for linter error.

**Comment by wkentaro** [comment]
```
Fetched 1002 kB in 6s (159 kB/s)

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch



W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Hash Sum mismatch



E: Some index files failed to download. They have been ignored, or old ones used instead.

+ echo Ignore error of apt-get update

Ignore error of apt-get update

+ sudo apt-get install -y -q -qq python-rosdep python-wstool python-catkin-tools ros-indigo-rosbash ros-indigo-rospack ccache

```

**Comment by wkentaro** [comment]
Could you please review and merge this?

**Comment by garaemon** [comment]
> Am I right?

Yeah, true


I forget the reason but I assume it may be emacs default issue.

**Comment by garaemon** [comment]
FYI. pcl default style including emacs lisp.
http://www.pointclouds.org/documentation/advanced/pcl_style_guide.php

**Comment by wkentaro** [comment]
I see thx.

**Pull request merged**
