### PR TITLE
Add cluster point indices label filter

### PR DESCRIPTION
**Pull request by Affonso-Gui**
Talking to @YutoUchimi and @knorth55 we realized that we do not actually have any good methods to extract cluster_points from `mask_rcnn` with matching labels  _e.g._ getting only pet bottle objects from 73b2_kitchen recognition node. So we decided to implement a node to do that: `ClusterPointIndicesLabelFilter`.

Other approaches such as using [LabelToMaskImage](https://jsk-recognition.readthedocs.io/en/latest/jsk_perception/nodes/label_to_mask_image.html) are not only redundant, but also many times only cover the first label instance. Subscribing and filtering in eus is also not safe regarding synchronization.

The usage / design of this node is questionable, so am open to discussions / suggestions.

Specially regarding cases where we want to get multiple types of objects, was also thinking it might be a good idea to set a namespace and a label list and have filtered results under that namespace (using the label name). Something like:
id_value: [7,9,13]
namespace: 'test'
`test/plastic_bottle`
`test/can`
`test/table`

@iory

### CODE REVIEW

**Comment by Affonso-Gui** [comment]
Btw regarding sample / test code, was thinking on making use of the hsr bag file on https://github.com/jsk-ros-pkg/jsk_recognition/pull/2463 , but for that we would need to have it on the `jsk_pcl_ros_utils` repo. 

@iory @YutoUchimi

**Comment by iory** [comment]
I see. Should I mv the bag file to `jsk_pcl_ros_utils` on #2463 or make another PR?

**Comment by Affonso-Gui** [comment]
@iory If you can move the bag file (and the play_rosbag xml) to the jsk_pcl_ros_utils in the same PR that would be appreciated!

**Comment by iory** [comment]
OK. I moved the bag file to `jsk_pcl_ros_utils` https://github.com/jsk-ros-pkg/jsk_recognition/pull/2463/commits/dbe9239d9c3d725fd5e242d0edd7759aa97872dd

**Comment by Affonso-Gui** [comment]
Added sample and test code!

**Comment by Affonso-Gui** [comment]
NOTE: this requires #2463 to be merged first

**Pull request merged**
