### PR TITLE
something have changed in updatream (maybe cv_bridge), added image_geometry as depends

### PR DESCRIPTION
**Pull request by k-okada**
could not compile on build firm http://jenkins.ros.org/job/ros-hydro-checkerboard-detector_binarydeb_precise_i386/80/console

### CODE REVIEW

**Comment by k-okada** [comment]
need release

**Comment by garaemon** [comment]
I will

◉  ryohei

**Comment by k-okada** [comment]
Done 

--
◉ Kei Okada

2015/01/08 15:18、Ryohei Ueda <notifications@github.com> のメッセージ:

> I will 
> 
> ◉ ryohei 
>

**Comment by garaemon** [comment]
thanks

✉︎ Ryohei

**Pull request merged**
