### PR TITLE
[doc/jsk_perception] added decument for image_publisher.py

### PR DESCRIPTION
**Pull request by Horisu**
doc for #696

### CODE REVIEW

**Comment by knorth55** [comment]
please squash commits to one and fix typo

**Comment by wkentaro** [comment]
> please squash commits to one and fix typo

I think it's ok because the merger can squash the commits.

**Comment by knorth55** [comment]
ok

**Comment by Horisu** [comment]
fixed typo and squashed commits

**Comment by wkentaro** [comment]
I sent PR that contains this PR: https://github.com/jsk-ros-pkg/jsk_recognition/pull/1707 .

**Comment by wkentaro** [comment]
This is merged in https://github.com/jsk-ros-pkg/jsk_recognition/pull/1707

**Pull request closed without merging**
