### PR TITLE
[jsk_perception] Add rosdoc.yaml to overwrite default file_patterns

### PR DESCRIPTION
**Pull request by wkentaro**
For https://github.com/jsk-ros-pkg/jsk_recognition/pull/1092

### CODE REVIEW

**Comment by k-okada** [comment]
I think we have to at least add `mainpage.dox` that write link to README.md to make documents

**Comment by wkentaro** [comment]
Because of no change?
I thought md_README.html should be generated even if no file change at:
http://docs.ros.org/indigo/api/jsk_perception/html/md_README.html

**Comment by k-okada** [comment]
but there is no way to find that file

--
◉ Kei Okada

**Comment by wkentaro** [comment]
understood.
This PR is for https://github.com/jsk-ros-pkg/jsk_recognition/pull/1092#issuecomment-134594038 .
So this is just testing.

**Comment by k-okada** [comment]
so please add mainpage.dox so we can release document pages at least everyone can agree at this moment.

**Comment by wkentaro** [comment]
I added.
The expected html is:
image
image

**Comment by garaemon** [comment]
looks good

**Pull request closed without merging**
