### PR TITLE
[jsk_pcl_ros_utils][CMakeLists.txt] Suppress warning on build

### PR DESCRIPTION
**Pull request by furushchev**
To suppress warning:

```bash
Starting  >>> jsk_pcl_ros_utils                                                                                 
________________________________________________________________________________________________________________
Warnings   << jsk_pcl_ros_utils:check /home/furushchev/ros/indigo/logs/jsk_pcl_ros_utils/build.check.017.log    
CMake Warning at /home/furushchev/ros/indigo/build/jsk_pcl_ros_utils/cmake/jsk_pcl_ros_utils-genmsg.cmake:3 (message):
  Invoking generate_messages() without having added any message or service
  file before.

  You should either add add_message_files() and/or add_service_files() calls
  or remove the invocation of generate_messages().
Call Stack (most recent call first):
  /opt/ros/indigo/share/genmsg/cmake/genmsg-extras.cmake:307 (include)
  CMakeLists.txt:156 (generate_messages)


flags:   -Wno-deprecated -fopenmp
cd /home/furushchev/ros/indigo/build/jsk_pcl_ros_utils; catkin build --get-env jsk_pcl_ros_utils | catkin env -si  /usr/bin/make cmake_check_build_system; cd -
```

### CODE REVIEW

**Comment by k-okada** [comment]
I think we can remove these line, along with https://github.com/jsk-ros-
pkg/jsk_recognition/pull/2040/files#diff-c976f5301dcd948d44a9109fe31ce550L70
Instead of comment out

--
◉ Kei Okada


2017-03-26 14:38 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada OK. Removed all unnecessary lines.

**Comment by furushchev** [comment]
```bash
+ WORKSPACE=/var/lib/jenkins/jobs/precise-travis-jsk-ros-pkg-jsk-recognition-hydro-deb-false-true/workspace
+ [ jenkins-precise-travis-jsk-ros-pkg-jsk-recognition-hydro-deb-false-true-832 =  ]
+ trap pwd; sudo rm -fr /var/lib/jenkins/jobs/precise-travis-jsk-ros-pkg-jsk-recognition-hydro-deb-false-true/workspace/jenkins-precise-travis-jsk-ros-pkg-jsk-recognition-hydro-deb-false-true-832 || echo 'ok' EXIT
+ git clone http://github.com/jsk-ros-pkg/jsk_recognition jenkins-precise-travis-jsk-ros-pkg-jsk-recognition-hydro-deb-false-true-832/jsk-ros-pkg/jsk_recognition
Cloning into 'jenkins-precise-travis-jsk-ros-pkg-jsk-recognition-hydro-deb-false-true-832/jsk-ros-pkg/jsk_recognition'...
+ cd jenkins-precise-travis-jsk-ros-pkg-jsk-recognition-hydro-deb-false-true-832/jsk-ros-pkg/jsk_recognition
+ [ 2040 != false ]
+ git fetch -q origin +refs/pull/2040/merge
+ git checkout -qf FETCH_HEAD
+ git submodule init
Submodule '.travis' (git://github.com/jsk-ros-pkg/jsk_travis) registered for path '.travis'
Submodule 'jsk_perception/slic' (https://github.com/garaemon/SLIC-Superpixels.git) registered for path 'jsk_perception/slic'
+ git submodule update
Cloning into '.travis'...
Submodule path '.travis': checked out '9100c3e65a4747cba6f98373f074341c342f6661'
Cloning into 'jsk_perception/slic'...
Submodule path 'jsk_perception/slic': checked out '78d9a2ba7ae1d3fee8c2ec774a52536c5f08f07c'
+ [ jsk_recognition = jsk_travis ]
+ timeout 10s sudo docker ps -a
+ exit 1
+ pwd
/var/lib/jenkins/jobs/precise-travis-jsk-ros-pkg-jsk-recognition-hydro-deb-false-true/workspace/jenkins-precise-travis-jsk-ros-pkg-jsk-recognition-hydro-deb-false-true-832/jsk-ros-pkg/jsk_recognition
+ sudo rm -fr /var/lib/jenkins/jobs/precise-travis-jsk-ros-pkg-jsk-recognition-hydro-deb-false-true/workspace/jenkins-precise-travis-jsk-ros-pkg-jsk-recognition-hydro-deb-false-true-832
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

docker on jenkins is dead?

**Comment by k-okada** [comment]
restarted jenkins

--
◉ Kei Okada


2017-03-28 22:29 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada @wkentaro Danke!

**Pull request merged**
