### PR TITLE
Add PointCloudXYZRGBToXYZ

### PR DESCRIPTION
**Pull request by wkentaro**
## Application

PointCloudXYZRGB -> [PointCloudXYZRGBToXYZ] -> PointCloudXYZ = A
Label -> [ColorizeLabel] = B
(A, B) -> [AddColorFromImage] -> LabeledPointCloud = C

**B**

frame0000

**C**

### CODE REVIEW

**Comment by knorth55** [comment]
+1
But i think you can use PointCloudXYZRGBtoXYZI in pcl.
Why do you prefer PointCloudXYZ to PointCloudXYZI?

**Comment by wkentaro** [comment]
What is I?

**Comment by wkentaro** [comment]
I've found AddColorFromImage converts PointXYZRGB to PointXYZ at the initial point.
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/src/add_color_from_image_nodelet.cpp#L87
So currently this node is not necessary for me.

**Comment by wkentaro** [comment]
@knorth55 Thanks for your review.

**Comment by knorth55** [comment]
I is intensity and it is for gray scale image.
I don't know which format  XYZ or XYZI is better, but pcl default conversion is XYZRGB to XYZI, so i thought youcan use the convert function for this nodelet.

**Comment by wkentaro** [comment]
I see. Thank you

**Pull request closed without merging**
