### PR TITLE
Add LabelArray to ssd object detector

### PR DESCRIPTION
**Pull request by Affonso-Gui**
Enable ssd_object_detector.py to publish LabelArray.

Related to https://github.com/jsk-ros-pkg/jsk_recognition/pull/2467

### CODE REVIEW

**Comment by YutoUchimi** [comment]
Please update test as well.

**Comment by Affonso-Gui** [comment]
@YutoUchimi Updated.

**Comment by knorth55** [comment]
@k-okada travis passed! can you check and merge this PR?

**Comment by k-okada** [comment]
@knorth55 @Affonso-Gui please reveiw again, this PR conflicts with current HEAD and I have manually resolved.

**Review by knorth55 — APPROVED** [review]

**Pull request merged**
