### PR TITLE
[jsk_perception] Add template directory to run eusmodel_template_gen.…

### PR DESCRIPTION
**Pull request by garaemon**
…l correctly

### CODE REVIEW

**Comment by garaemon** [comment]
Still raise an error.

```
[jsk_perception] ;; loading roseus("c1aac9c") on euslisp((9.12 jzou Thu May 28 09:29:56 PDT 2015 bb29754 1.0.6))                                                                                                                                               
[jsk_perception] ;; (generate-launcher)                                                                                                                                                                                                                        
[jsk_perception] ;; (test-detection-result)                                                                                                                                                                                                                    
[jsk_perception] /home/leus/ros/hydro_parent/devel/share/euslisp/jskeus/eus/Linux64/bin/irteusgl: ERROR th=0  0x5772b80 in #<compiled-code #X5793510>[ INFO] [1441244288.947497398]: cell* ROSEUS_EXIT(context*, int, cell**)                                  
```

**Comment by garaemon** [comment]
FIxed cmake targets and merged origin/master

**Comment by garaemon** [comment]
Still unstable. I'm doubting euslisp depend codes.

**Comment by k-okada** [comment]
http://jenkins.ros.org/job/ros-indigo-jsk-perception_binarydeb_trusty_amd64/52/console

it could not pass the build process:

```
cd /tmp/buildd/ros-indigo-jsk-perception-0.2.18-0trusty-20150903-1733/sample && roseus ./pose_detector_auto_gen_sample.l
[33m;; loading roseus("") on euslisp((9.15 host02.storm.ros.org Mon Aug 31 15:37:47 UTC 2015  1.0.10))
[0m;; (generate-launcher)
;; (test-detection-result)
[31m;; could not find pacakge [jsk_perception]
[0m/opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl: ERROR th=0  0x556f200 in (error "file ~s not found" fname)/opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl: ERROR th=0  0x5587730 in (apply #'ros::load-org-for-ros ros::fullname args)/opt/ros/indigo/share/euslisp/jskeus/eus/Linux64/bin/irteusgl: ERROR th=0 undefined function gen-all-launchgen-all-launch in (generate-launcher);; Segmentation Fault.
;; in (gen-all-launch (list (make-sony-rimokon) (make-sharp-rimokon)) "rimokon-pose.launch" :ns "/narrow_stereo/left")
;; You are still in a signal handler.
;;Try reset or throw to upper level as soon as possible.
;; code=1406051440 x=53cea340 addr=2000000000000000
signal=11 to thread 0, 
;; No, you cannot continue the previous evaluation.
make[4]: *** [../sample/rimokon-pose.launch] Error 11
make[4]: Leaving directory `/tmp/buildd/ros-indigo-jsk-perception-0.2.18-0trusty-20150903-1733/obj-x86_64-linux-gnu'
make[3]: *** [CMakeFiles/eusmodel_template.dir/all] Error 2
make[3]: Leaving directory `/tmp/buildd/ros-indigo-jsk-perception-0.2.18-0trusty-20150903-1733/obj-x86_64-linux-gnu'
make[2]: *** [all] Error 2
```

**Pull request merged**
