### PR TITLE
[jsk_perception] add weight_candidates_refiner node

### PR DESCRIPTION
**Pull request by knorth55**
- add `Weight` and `WeightStamped` msg
- add `weight_candidates_refiner.py` and doc

cc. @wkentaro

### CODE REVIEW

**Comment by knorth55** [comment]
Updated

**Comment by wkentaro** [comment]
Please test this on jsk_apc pick or stow task.

**Comment by wkentaro** [comment]
Please add rosbag of scale value, and sample.

@pazeshun Maybe you can add `bool stable` to the `Weight.msg` in this PR.

**Comment by pazeshun** [comment]
Can we move to #2193 ?

**Pull request closed without merging**
