### PR TITLE
[jsk_pcl_ros/openni2_remote.launch] Modified namespace

### PR DESCRIPTION
**Pull request by iory**
I modified that you can change the camera source and rgb namespace.

### CODE REVIEW

**Comment by 708yamaguchi** [comment]
fetchでも使えるようになりました。
ありがとうございました。

**Comment by iory** [comment]
Also, I checked thisPR  with real HRP2 environment.

**Comment by k-okada** [comment]
what is the  rgb namespace of fetch robot?

--
◉ Kei Okada


2018-06-21 14:00 GMT+09:00 iory <notifications@github.com>:

**Comment by iory** [comment]
> what is the  rgb namespace of fetch robot?

rgb.

Since, in openni2_launch, user can change the namespace of rgb,
I changed the rgb as a argument.
https://github.com/ros-drivers/openni2_camera/blob/indigo-devel/openni2_launch/launch/openni2.launch#L30

**Comment by k-okada** [comment]
if the rgb namespace of fetch robot is rgb, why we have to add this feature? and/or what is the namespace of other robot?

**Comment by iory** [comment]
> if the rgb namespace of fetch robot is rgb

Not specified fetch. 
Why are you taking about fetch?

For instances, aero in jsk has a d415 camera, and its rgb namespace is color.

**Comment by k-okada** [comment]
> Why are you taking about fetch?


because of
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2302#issuecomment-398974137

--
◉ Kei Okada


2018-06-21 16:51 GMT+09:00 iory <notifications@github.com>:

**Comment by iory** [comment]
> and
- fetchでも使えるようになりました。
is
- fetchでも今までどおり問題なく使えることを確認しました．
?

No. This PR enable openni2_remote.launch for robots that have changed camera space and rgb space, 
such that fetch.

> may be better use arg for 'depth'

I agree with you. I added arg for 'depth'.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2302/commits/4518f05ed3b22b0ef04f716ebc152afb057bf68e

**Comment by k-okada** [comment]
...
   
so fetch publishes `/head_camera/rgb/image_rect_color` (or  `/head_camera/rgb/quater/image_rect_color` )[1] and now you can run `openni2_remote.launch` with `local_camera:=head_camera rgb:=rgb`

If this is correct,
`I modified that you can change the camera source and rgb namespace.`  ( https://github.com/jsk-ros-pkg/jsk_recognition/pull/2302#issue-196264826 ) means 'camera namespace and rgb namesapce`, and my question https://github.com/jsk-ros-pkg/jsk_recognition/pull/2302#issuecomment-399005214 means `what is the camera and  rgb namespace of fetch robot?` not `what is the  rgb namespace of fetch robot?`

[1] https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/jsk_fetch_startup/config/jsk_startup.rviz#L402

**Comment by iory** [comment]
> my question #2302 (comment) means what is the camera and rgb namespace of fetch robot? not what is the rgb namespace of fetch robot?

rgb

**Comment by k-okada** [comment]
my question is
1. what is the camera namespace  -> head_camera
2. what is the rgb namespace -> rgb

--
◉ Kei Okada


2018-06-26 23:11 GMT+09:00 iory <notifications@github.com>:

**Comment by iory** [comment]
> 1. what is the camera namespace

head_camera

> 2. what is the rgb namespace

rgb

**Comment by k-okada** [comment]
then, may be you'd better to fix and improve your first comment.

**Comment by iory** [comment]
> then, may be you'd better to fix and improve your first comment. 

I'll do my best.

**Comment by iory** [comment]
> then, may be you'd better to fix and improve your first comment.

@k-okada Based on the above comments, I changed the first comment.

**Pull request merged**
