### PR TITLE
Add travis test for jade

### PR DESCRIPTION
**Pull request by wkentaro**
Please wait for https://github.com/jsk-ros-pkg/jsk_travis/pull/102 to be merged
and submodules to be updated.

### CODE REVIEW

**Comment by wkentaro** [comment]
The error is caused by unreleased `ros-jade-ml-classifiers`.
https://github.com/sniekum/ml_classifiers/issues/4

**Comment by k-okada** [comment]
yes, I'm asking ...
https://github.com/jolting/ml_classifiers-release/issues/1


--
◉ Kei Okada

**Comment by wkentaro** [comment]
```
[jsk_perception] -- Using these message generators: gencpp;geneus;genlisp;genpy
[jsk_pcl_ros] -- Using these message generators: gencpp;geneus;genlisp;genpy
[jsk_pcl_ros] CMake Error at /opt/ros/jade/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
[jsk_pcl_ros]   Could not find a package configuration file provided by "sklearn" with any
[jsk_pcl_ros]   of the following names:
[jsk_pcl_ros]
[jsk_pcl_ros]     sklearnConfig.cmake
[jsk_pcl_ros]     sklearn-config.cmake
[jsk_pcl_ros]
[jsk_pcl_ros]   Add the installation prefix of "sklearn" to CMAKE_PREFIX_PATH or set
[jsk_pcl_ros]   "sklearn_DIR" to a directory containing one of the above files.  If
[jsk_pcl_ros]   "sklearn" provides a separate development package or SDK, be sure it has
[jsk_pcl_ros]   been installed.
[jsk_pcl_ros] Call Stack (most recent call first):
[jsk_pcl_ros]   CMakeLists.txt:26 (find_pa
```

**Comment by wkentaro** [comment]
~~~
package): 

[ml_classifiers]   Could not find a package configuration file provided by "eigen" with any of 

[ml_classifiers]   the following names:                                         

[ml_classifiers]                                                                

[ml_classifiers]     eigenConfig.cmake                                          

[ml_classifiers]     eigen-config.cmake                                         

[ml_classifiers]               
~~~

**Comment by garaemon** [comment]
see http://wiki.ros.org/jade/Migration#Eigen_CMake_Module_in_cmake_modules

**Comment by wkentaro** [comment]
That note is about `FindEigen.cmake`, but this is because ecl_eigen is not released in jade.
so I install https://github.com/stonier/ecl_core from source.

**Comment by wkentaro** [comment]
```
[ecl_exceptions] CMake Error at /opt/ros/jade/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
[ecl_exceptions]   Could not find a package configuration file provided by "ecl_config" with
[ecl_exceptions]   any of the following names:
[ecl_exceptions]
[ecl_exceptions]     ecl_configConfig.cmake
[ecl_exceptions]     ecl_config-config.cmake
[ecl_exceptions]
[ecl_exceptions]   Add the installation prefix of "ecl_config" to CMAKE_PREFIX_PATH or set
[ecl_exceptions]   "ecl_config_DIR" to a directory containing one of the above files.  If
[ecl_exceptions]   "ecl_config" provides a separate development package or SDK, be sure it has
[ecl_exceptions]   been installed.
[ecl_exceptions] Call Stack (most recent call first):
[ecl_exceptions]   CMakeLists.txt:12 (find_package)
[ecl_exceptions]
[
```

**Comment by garaemon** [comment]
Which package require ecl?

**Comment by wkentaro** [comment]
ml_classifiers

**Comment by garaemon** [comment]
reported https://github.com/sniekum/ml_classifiers/issues/5

**Comment by wkentaro** [comment]
I and @k-okada reported before, but have no response.
https://github.com/sniekum/ml_classifiers/issues/4
https://github.com/jolting/ml_classifiers-release/issues/1

**Comment by wkentaro** [comment]
sorry, I was misunderstanding.t the error at [here](https://github.com/jsk-ros-pkg/jsk_recognition/pull/976#issuecomment-147933167) is not about ecl.
so I will also you shared migration link.

**Comment by wkentaro** [comment]
@garaemon Test passed finally. Your comment at https://github.com/jsk-ros-pkg/jsk_recognition/pull/976#issuecomment-147933769 was accurate, thanks. :pray:

**Comment by wkentaro** [comment]
I sent PR at https://github.com/sniekum/ml_classifiers/pull/6 .
But I don't expect it is merged soon. So, I specify my forked repo at this point.

**Comment by wkentaro** [comment]
the test passes, could you please review?

**Comment by garaemon** [comment]
Do you need to install jsk_3rdparty from source?

**Comment by wkentaro** [comment]
jsk_pcl_ros depens on sklearn.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/976#issuecomment-147655637

**Comment by garaemon** [comment]
I see

**Pull request merged**
