### PR TITLE
[Major Release] Remove jsk_pcl_ros/box_array_to_box.py

### PR DESCRIPTION
**Pull request by wkentaro**
Close https://github.com/jsk-ros-pkg/jsk_recognition/issues/1831
This change should be released as a major release.

cc @k-okada

### CODE REVIEW

**Comment by k-okada** [comment]
why you removed imagesift

--
◉ Kei Okada

**Comment by wkentaro** [comment]
It is already fixed.

**Comment by k-okada** [comment]
since no one claimed that this is used, but not sure if we're ok to remove this .... https://github.com/jsk-ros-pkg/jsk_recognition/pull/1799

**Comment by k-okada** [comment]
it seems we had users for box_array_to_box.py -> https://github.com/jsk-ros-pkg/jsk_recognition/pull/1799#issuecomment-244731229

**Pull request merged**
