### PR TITLE
MaskImageToPointIndices: support multi channel mask image

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by furushchev** [comment]
Updated.

**Comment by knorth55** [comment]
can you update output msg type in doc?
if you choose `use_multi_channel:=true` and `target_index:=-1`, `~output` message type would be `ClusterPointIndices`

**Comment by knorth55** [comment]
Or you can use different topic namespace for the specific case.

**Comment by knorth55** [comment]
Or you can use different topic namespace for the specific case.

**Comment by YutoUchimi** [comment]
I use different topic name. i.e. `~output` for pcl_msgs/PointIndices and `~output/all_indices` for jsk_recognition_msgs/ClusterPointIndices.

**Comment by YutoUchimi** [comment]
Hmm... travis test is unstable.
```
[ROSTEST]-----------------------------------------------------------------------
[jsk_pcl_ros_utils.rosunit-test_mask_image_to_point_indices/test_published][FAILURE]
Topic [/mask_image_to_point_indices2/output/all_indices] is not published
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/opt/ros/melodic/share/jsk_tools/src/test_topic_published.py", line 96, in test_published
    checker.topic_name)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------
SUMMARY
 * RESULT: FAIL
 * TESTS: 1
 * ERRORS: 0
 * FAILURES: 1
rostest log file is in /workspace/jsk-ros-pkg/jsk_recognition/log/rostest-812380ba91e4-24665.log
-- run_tests.py: verify result "/workspace/ros/ws_jsk_recognition/build/jsk_pcl_ros_utils/test_results/jsk_pcl_ros_utils/rostest-test_mask_image_to_point_indices.xml"
make[3]: Leaving directory '/workspace/ros/ws_jsk_recognition/build/jsk_pcl_ros_utils'
Built target _run_tests_jsk_pcl_ros_utils_rostest_test_mask_image_to_point_indices.test
```

**Comment by YutoUchimi** [comment]
Travis passed!
@knorth55 Could you review again?

**Comment by YutoUchimi** [comment]
### Before https://github.com/jsk-ros-pkg/jsk_recognition/pull/2409/commits/9df55df105750daf63a4023d5564b4585eeaa668
The invalid output shown below is caused by JPEG compression of original image (`kiva_pod_mask.jpg` and `circles.jpg`).

mask_image_to_point_indices_no_jpg_support

### After https://github.com/jsk-ros-pkg/jsk_recognition/pull/2409/commits/9df55df105750daf63a4023d5564b4585eeaa668
I increased the threshold from 0 to 127 in order to support JPEG images as much as possible.

mask_image_to_point_indices

**Pull request merged**
