### PR TITLE
[jsk_perception] BING: Binarized Normed Gradients for Objectness Estimation at 300fps

### PR DESCRIPTION
**Pull request by wkentaro**
**Demo**
bing

**Speed**
around 20fps on my Macbook Pro Retina (mid 2012)
```
         topic             rate    min_delta   max_delta   std_dev
==================================================================
/camera/rgb/image_color   29.887   0.028       0.037       0.002
/bing/output              2.842    0.352       0.352       0
```

### CODE REVIEW

**Comment by k-okada** [comment]
why you added `include_directories(${OpenCV_INCLUDE_DIRS})`
at
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1598/files#diff-f491a4c6a876a74588bec404e3d766ceR44
and
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1598/files#diff-f491a4c6a876a74588bec404e3d766ceR220

and why you check `if(${OpenCV_VERSION} VERSION_GREATER "2.4.8")` in one place but did not on the other.

**Comment by wkentaro** [comment]
The upper one is a mistake, I think.
The condition with version is in order not to change the behavior before introducing this PR.

**Comment by k-okada** [comment]
on trusty, OpenCV version is 2.4.8. Does this code inted not to compile
bing on indigo?
```
$ aptitude show libcv-dev
Package: libcv-dev
State: installed
Automatically installed: yes
Multi-Arch: same
Version: 2.4.8+dfsg1-2ubuntu1
```


--
◉ Kei Okada

**Comment by wkentaro** [comment]
If you install ros-indigo-opencv3, the `${OpenCV_Version}` is `3.0.0`.

**Comment by k-okada** [comment]
Note that hydro uses 2.4.9
- http://www.ros.org/debbuild/hydro.html?q=opencv2

Not sure how this inference our source tree, just a reminder.
2016年5月21日土曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> If you install ros-indigo-opencv3, the ${OpenCV_Version} is 3.0.0.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1598#issuecomment-220771831>
>


-- 
--
◉ Kei Okada

**Pull request merged**
