### PR TITLE
Retry at most three times point_indices_to_mask_image.test

### PR DESCRIPTION
**Pull request by wkentaro**
To fix error sometimes on Travis.

### CODE REVIEW

**Comment by k-okada** [comment]
why it sometimes fail?

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Sometimes the topic message does not come and the test reaches the timeout.
It happens only on Travis/Jenkins, and I don't know other ways to fix this than retrying.

**Comment by k-okada** [comment]
may be because of lack of cpu resources, try test code under high load average or cheapest AWS machine.
ONe solution may running node with `use_sim_time` with slow `/clock` speed, and other may be increase queue size for the subscriber?
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros_utils/src/point_indices_to_mask_image_nodelet.cpp#L60-L66

**Comment by wkentaro** [comment]
You mean retrying is not good solution?

**Comment by k-okada** [comment]
Yes, I think that should be used when you know that process is designed to stochastically fail.
In this case, you created the node as to work 100% reliability, so this means there might be something wrong.
Usually if it is working on you machine, but failing in travis/jenkins usually means the node works wrongly if the CPU/memory resource is limited.
So it is better to remember that there might be bug in point_indices_to_mask_image_nodelet.cpp

One question is in the following code, queue size of input and input/image is 1, but that of message filter is 100. Is this ok?
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros_utils/src/point_indices_to_mask_image_nodelet.cpp#L60-L66

**Comment by wkentaro** [comment]
> queue size of input and input/image is 1

is for messages for processing in callback.

> that of message filter is 100

is for sychronization of messages.

So I think it is ok.

---

> Yes, I think that should be used when you know that process is designed to stochastically fail.
In this case, you created the node as to work 100% reliability, so this means there might be something wrong.
Usually if it is working on you machine, but failing in travis/jenkins usually means the node works wrongly if the CPU/memory resource is limited.
So it is better to remember that there might be bug in point_indices_to_mask_image_nodelet.cpp

Hmm, but currently we use retry=3 for almost all test files...
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros_utils/test/bounding_box_array_to_bounding_box.test
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros_utils/test/cluster_point_indices_to_point_indices.test
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros_utils/test/point_indices_to_cluster_point_indices.test
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros_utils/test/pointcloud_to_mask_image.test
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros_utils/test/pointcloud_to_point_indices.test
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/test/add_mask_image.test
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_perception/test/extract_image_channel.test

**Comment by k-okada** [comment]
>
> So I think it is ok.

if so, message filter has 100 x 2 queues and copy the data from
subscriber, instead of just to have an array of pointer. that is not
efficient....
anyway i just look at the test code and it seems very simple and not
sure why test fails, so only possibility is to drop incoming data by
setting queue size 1. May be there might be other problems.

> Hmm, but currently we use retry=3 for almost all test files...

Yes, and that's may hiding potential bugs. I do not say you have to
fix that, just to remind that adding "retry" did not "solve" problem,
the bug may appear in future, sometimes just before the deadline or
during important demos....

**Pull request merged**
