### PR TITLE
Update the documentation for Intel RealSense

### PR DESCRIPTION
**Pull request by sktometometo**
- [x]  add a description of D400 series
- [x] add a description of T265
- [x] add 16.04/18.04/20.04 installation
- [x] add an example of VSLAM

### CODE REVIEW

**Comment by knorth55** [comment]
we can run L515 by following launch. (be careful that L515 RGB does not support 4:3 images such as 640x480)

```
roslaunch realsense2_camera rs_rgbd.launch color_width:=1280 color_height:=720 depth_width:=1024 depth_height:=768
```

cc. @tohirose

**Review by k-okada — CHANGES_REQUESTED** [review]
@yuki-shark please add your findigs with images

**Review by k-okada — APPROVED** [review]

**Review by knorth55 — APPROVED** [review]

**Comment by k-okada** [comment]
travis failing, any idea ? https://travis-ci.com/github/jsk-ros-pkg/jsk_recognition/jobs/497197089

```
Downloading/unpacking fcn
  Downloading fcn-6.4.17.tar.gz
  Running setup.py (path:/tmp/pip_build_root/fcn/setup.py) egg_info for package fcn
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    
    warning: no files found matching '*' under directory 'static'
Downloading/unpacking chainercv
  Running setup.py (path:/tmp/pip_build_root/chainercv/setup.py) egg_info for package chainercv
    
    warning: no previously-included files matching '*.pyx' found under directory 'chainercv'
Downloading/unpacking chainer==6.7.0
  Running setup.py (path:/tmp/pip_build_root/chainer/setup.py) egg_info for package chainer
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    
Downloading/unpacking cupy-cuda91
  Could not find any downloads that satisfy the requirement cupy-cuda91
Cleaning up...
No distributions at all found for cupy-cuda91
Storing debug log for failure in /home/user/.pip/pip.log
The command '/bin/sh -c sudo pip install fcn chainercv chainer==6.7.0 cupy-cuda91' returned a non-zero code: 1
+ set +x
Build step 'シェルの実行' marked build as failure
Finished: FAILURE
```

**Comment by knorth55** [comment]
I have no idea...
It seems cupy-cuda91 is still available.
https://pypi.org/project/cupy-cuda91/

**Pull request merged**
