### PR TITLE
1.7.1 does not contain organized_edge_detector

### PR DESCRIPTION
**Pull request by k-okada**
see https://github.com/jsk-ros-pkg/jsk_recognition/pull/245#issuecomment-153711241

### CODE REVIEW

**Comment by garaemon** [comment]
Indigo uses 1.7.2?

**Comment by k-okada** [comment]
inidigo ues 1.7.1 http://packages.ros.org/ros/ubuntu/pool/main/p/pcl-1.7/
but someone(B3) using ppa version
ppaa uses 1.7.2 : https://launchpadlibrarian.net/186326341/pcl-1.7_1.7.2-1%2Btrusty6_source.changes
vivid uses 1.7.2: http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libpcl&searchon=names

**Comment by snozawa** [comment]
（すいません、色々勘違いしてましたがついさっきmergeされたんですね）

**Comment by garaemon** [comment]
In enshu environment, does they use 1.7.2?

**Comment by garaemon** [comment]
> but someone(B3) using ppa version

Oh, I see.

**Comment by garaemon** [comment]
what I can say is just recompile everything.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1367

**Comment by k-okada** [comment]
We're providing special deb file for them, since we ' re very kind
professors

https://github.com/jsk-enshu/robot-programming/releases/tag/2.1.3

2015年12月4日金曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> what I can say is just recompile everything.
> #1367 <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1367>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1301#issuecomment-161931254>
> .
>


-- 
--
◉ Kei Okada

**Pull request merged**
