### PR TITLE
[jsk_perception, slic_super_pixels] add parameter, publish_debug_images

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**

### CODE REVIEW

**Comment by wkentaro** [comment]
why not check the num of subscribers?

**Comment by YoheiKakiuchi** [comment]
The ports are used for just debug purpose.
It's enough to select by parameter.

**Comment by wkentaro** [comment]
So you have more than 9999 topics in your system?

**Comment by YoheiKakiuchi** [comment]
> So you have more than 9999 topics in your system?
???

**Comment by wkentaro** [comment]
> The ports are used for just debug purpose.

You have some trouble caused by missing ports, right?

**Comment by YoheiKakiuchi** [comment]
No.
Some bugs may exist for generating debug images. 
Node crashes at random when using debug images.

**Comment by wkentaro** [comment]
So, you can use try-catch?

**Comment by YoheiKakiuchi** [comment]
try-catch do not work for segfault

**Comment by wkentaro** [comment]
I see. Then you should add comment to the code about problems you encountered, and why you need this PR. Please refer to this PR in the comment.
Basically, switching debug publication by rosparam is not necessary, in my opinion.

**Comment by wkentaro** [comment]
BTW, your segfault problem is similar to https://github.com/jsk-ros-pkg/jsk_recognition/issues/1308 which is caused by large input image size?

**Pull request merged**
