### PR TITLE
Fix #1701 & Sample & Test for MaskImageGenerator

### LINKED ISSUE #1701: MaskImageGenerator's mask size is different from the assigned parameter
in this picture, I assign height, width of mask image as 256, but it seems different. (it is not square but rectangle)
the meaning of the parameter is described in https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/doc/jsk_perception/nodes/mask_image_generator.md#parameters

screen shot 2016-05-27 at 16 05 21

### PR DESCRIPTION
**Pull request by wkentaro**
Fix #1701 

image

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
Sorry need rebase

**Comment by wkentaro** [comment]
why?
image

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Please merge this.

**Pull request merged**
