### PR TITLE
Adaptive object tracking

### PR DESCRIPTION
**Pull request by iKrishneel**
Nodelet for updating template during tracking using the Particle Filters. 
-- the nodelet for selecting the target object for tracking will be will be added soon with the descriptions

### CODE REVIEW

**Comment by k-okada** [comment]
Great, can you create document for this node? @YuOhara, @wkentaro or
@aginika  know how to do this.

2015年10月20日火曜日、Krishneel<notifications@github.com>さんは書きました:

> Nodelet for updating template during tracking using the Particle Filters.
> -- the nodelet for selecting the target object for tracking will be will
> be added soon
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jsk-ros-pkg/jsk_recognition/pull/1263
> Commit Summary
>
>    - nodelet for tracking and updating object changes
>    - added cfg and launch files
>    - added rviz script and other minor changes
>    - Delete #target_adaptive_tracking.h#
>    - Delete #target_adaptive_tracking_nodelet.cpp#
>    - added rviz script and other minor changes
>    - Merge branch 'adaptive-object-tracking' of ssh://
>    github.com/iKrishneel/jsk_recognition into adaptive-object-tracking
>
> File Changes
>
>    - *M* jsk_pcl_ros/CMakeLists.txt
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1263/files#diff-0>
>    (4)
>    - *A* jsk_pcl_ros/cfg/TargetAdaptiveTrackingConfig.cfg
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1263/files#diff-1>
>    (37)
>    - *A* jsk_pcl_ros/include/jsk_pcl_ros/target_adaptive_tracking.h
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1263/files#diff-2>
>    (270)
>    - *M* jsk_pcl_ros/jsk_pcl_nodelets.xml
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1263/files#diff-3>
>    (7)
>    - *A* jsk_pcl_ros/launch/target_adaptive_tracking.launch
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1263/files#diff-4>
>    (50)
>    - *A* jsk_pcl_ros/sample/rviz/target_adaptive_tracking.rviz
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1263/files#diff-5>
>    (315)
>    - *A* jsk_pcl_ros/src/target_adaptive_tracking_nodelet.cpp
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1263/files#diff-6>
>    (1884)
>
> Patch Links:
>
>    - https://github.com/jsk-ros-pkg/jsk_recognition/pull/1263.patch
>    - https://github.com/jsk-ros-pkg/jsk_recognition/pull/1263.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1263>.
>


-- 
--
◉ Kei Okada

**Comment by garaemon** [comment]
@iKrishneel 
You use `DiagnosticNodelet::advertise`, `DiagnosticNodelet::subscribe`, `DiagnosticNodelet::unsubscribe` mechanism.
It means "If output topics are not subscribed, it does not subscribe input topic to reduce computation".

But in tracking, it needs to compute always and DiagnosticNodelet mechanism does not match the purpose.
I recommend you to always subscribe input topics.

**Comment by iKrishneel** [comment]
@garaemon  thanks for the info. 
I will make the changes accordingly.

**Comment by k-okada** [comment]
commit in #1868

**Pull request closed without merging**
