### PR TITLE
[jsk_pcl_ros_utils][polygon_magnifier] Support scale factor to magnify polygon

### PR DESCRIPTION
**Pull request by furushchev**
Supports factor to magnify polygon in addition to distance.
Magnified planes are definitely convex with scale factor.

**NOTE** This Pull request supposed to be merged after #2053

### CODE REVIEW

**Comment by k-okada** [comment]
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk-recognition-jade-deb-false-true/997/consoleFull

```
-- run_tests.py: verify result "/workspace/ros/ws_jsk_recognition/build/jsk_perception/test_results/jsk_perception/rostest-test_apply_mask_image.xml"

00:20:44 


make[3]: Leaving directory `/workspace/ros/ws_jsk_recognition/build/jsk_perception'

00:20:44 

/usr/bin/cmake -E cmake_progress_report /workspace/ros/ws_jsk_recognition/build/jsk_perception/CMakeFiles 

00:20:44 


Built target _run_tests_jsk_perception_rostest_test_apply_mask_image.test

00:20:44 


/usr/bin/make -f CMakeFiles/_run_tests_jsk_perception_rostest_test_bof_histogram_extractor.test.dir/build.make CMakeFiles/_run_tests_jsk_perception_rostest_test_bof_histogram_extractor.test.dir/depend

00:20:44 


make[3]: Entering directory `/workspace/ros/ws_jsk_recognition/build/jsk_perception'

00:20:44 

cd /workspace/ros/ws_jsk_recognition/build/jsk_perception && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception /workspace/ros/ws_jsk_recognition/build/jsk_perception /workspace/ros/ws_jsk_recognition/build/jsk_perception /workspace/ros/ws_jsk_recognition/build/jsk_perception/CMakeFiles/_run_tests_jsk_perception_rostest_test_bof_histogram_extractor.test.dir/DependInfo.cmake --color=

00:20:44 


Dependee "/workspace/ros/ws_jsk_recognition/build/jsk_perception/CMakeFiles/_run_tests_jsk_perception_rostest_test_bof_histogram_extractor.test.dir/DependInfo.cmake" is newer than depender "/workspace/ros/ws_jsk_recognition/build/jsk_perception/CMakeFiles/_run_tests_jsk_perception_rostest_test_bof_histogram_extractor.test.dir/depend.internal".

00:20:44 

Dependee "/workspace/ros/ws_jsk_recognition/build/jsk_perception/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/workspace/ros/ws_jsk_recognition/build/jsk_perception/CMakeFiles/_run_tests_jsk_perception_rostest_test_bof_histogram_extractor.test.dir/depend.internal".

00:20:44 


Scanning dependencies of target _run_tests_jsk_perception_rostest_test_bof_histogram_extractor.test

00:20:44 


make[3]: Leaving directory `/workspace/ros/ws_jsk_recognition/build/jsk_perception'

00:20:44 


/usr/bin/make -f CMakeFiles/_run_tests_jsk_perception_rostest_test_bof_histogram_extractor.test.dir/build.make CMakeFiles/_run_tests_jsk_perception_rostest_test_bof_histogram_extractor.test.dir/build

00:20:44 


make[3]: Entering directory `/workspace/ros/ws_jsk_recognition/build/jsk_perception'

00:20:44 

catkin_generated/env_cached.sh /usr/bin/python /opt/ros/jade/share/catkin/cmake/test/run_tests.py /workspace/ros/ws_jsk_recognition/build/jsk_perception/test_results/jsk_perception/rostest-test_bof_histogram_extractor.xml /opt/ros/jade/share/rostest/cmake/../../../bin/rostest\ --pkgdir=/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception\ --package=jsk_perception\ --results-filename\ test_bof_histogram_extractor.xml\ --results-base-dir\ "/workspace/ros/ws_jsk_recognition/build/jsk_perception/test_results"\ /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/test/bof_histogram_extractor.test\ 

00:20:44 


-- run_tests.py: execute commands

00:20:44 

  /opt/ros/jade/share/rostest/cmake/../../../bin/rostest --pkgdir=/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception --package=jsk_perception --results-filename test_bof_histogram_extractor.xml --results-base-dir /workspace/ros/ws_jsk_recognition/build/jsk_perception/test_results /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/test/bof_histogram_extractor.test 

00:20:44 


... logging to /workspace/jsk-ros-pkg/jsk_recognition/log/rostest-204a1a262d5f-34447.log

00:20:45 


[ROSUNIT] Outputting test results to /workspace/ros/ws_jsk_recognition/build/jsk_perception/test_results/jsk_perception/rostest-test_bof_histogram_extractor.xml

00:20:48 

/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LabelEncoder from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:20:48 

  UserWarning)

00:20:48 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LogisticRegression from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:20:48 

  UserWarning)

00:20:50 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator NearestNeighbors from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:20:50 

  UserWarning)

00:20:53 


[WARN] [WallTime: 1493738453.809240] [/sklearn_classifier] subscribes topics only with child subscribers. Set '~always_subscribe' as True to have it subscribe always.

00:21:17 


terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'

00:21:17 


  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

00:21:21 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LabelEncoder from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:21:21 

  UserWarning)

00:21:21 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LogisticRegression from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:21:21 

  UserWarning)

00:21:23 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator NearestNeighbors from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:21:23 

  UserWarning)

00:21:26 


[WARN] [WallTime: 1493738486.121197] [/sklearn_classifier] subscribes topics only with child subscribers. Set '~always_subscribe' as True to have it subscribe always.

00:21:50 


terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'

00:21:50 

  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

00:21:53 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LabelEncoder from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:21:53 

  UserWarning)

00:21:53 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LogisticRegression from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:21:53 

  UserWarning)

00:21:55 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator NearestNeighbors from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:21:55 

  UserWarning)

00:21:58 


[WARN] [WallTime: 1493738518.479060] [/sklearn_classifier] subscribes topics only with child subscribers. Set '~always_subscribe' as True to have it subscribe always.

00:22:22 


terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'

00:22:22 

  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

00:22:25 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LabelEncoder from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:22:25 

  UserWarning)

00:22:25 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LogisticRegression from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:22:25 

  UserWarning)

00:22:27 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator NearestNeighbors from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:22:27 

  UserWarning)

00:22:30 


[WARN] [WallTime: 1493738550.693213] [/sklearn_classifier] subscribes topics only with child subscribers. Set '~always_subscribe' as True to have it subscribe always.

00:22:54 


terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'

00:22:54 

  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

00:22:58 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LabelEncoder from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:22:58 

  UserWarning)

00:22:58 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LogisticRegression from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:22:58 

  UserWarning)

00:23:00 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator NearestNeighbors from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:23:00 

  UserWarning)

00:23:03 


[WARN] [WallTime: 1493738583.285165] [/sklearn_classifier] subscribes topics only with child subscribers. Set '~always_subscribe' as True to have it subscribe always.

00:23:27 


terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'

00:23:27 

  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

00:23:30 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LabelEncoder from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:23:30 

  UserWarning)

00:23:30 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LogisticRegression from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:23:30 

  UserWarning)

00:23:32 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator NearestNeighbors from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:23:32 

  UserWarning)

00:23:35 


[WARN] [WallTime: 1493738615.518301] [/sklearn_classifier] subscribes topics only with child subscribers. Set '~always_subscribe' as True to have it subscribe always.

00:23:59 


terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'

00:23:59 

  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

00:24:03 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LabelEncoder from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:24:03 

  UserWarning)

00:24:03 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator LogisticRegression from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:24:03 

  UserWarning)

00:24:05 


/usr/local/lib/python2.7/dist-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator NearestNeighbors from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.

00:24:05 

  UserWarning)

00:24:07 


[WARN] [WallTime: 1493738647.981012] [/sklearn_classifier] subscribes topics only with child subscribers. Set '~always_subscribe' as True to have it subscribe always.

00:24:31 


terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'

00:24:31 

  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument

00:24:32 



testtest_bof_histogram_extractor ... ERROR!

00:24:32 

ERROR: max time [30.0s] allotted for test [test_bof_histogram_extractor] of type [jsk_tools/test_topic_published.py]

00:24:32 


  File "/usr/lib/python2.7/unittest/case.py", line 331, in run

00:24:32 

    testMethod()

00:24:32 

  File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/runner.py", line 148, in fn

00:24:32 

    self.test_parent.run_test(test)

00:24:32 

  File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 132, in run_test

00:24:32 

    return self.runner.run_test(test)

00:24:32 

  File "/opt/ros/jade/lib/python2.7/dist-packages/roslaunch/launch.py", line 681, in run_test

00:24:32 

    (test.time_limit, test.test_name, test.package, test.type))

00:24:32 

--------------------------------------------------------------------------------

00:24:32 




00:24:32 

[ROSTEST]-----------------------------------------------------------------------

00:24:32 



00:24:32 



00:24:32 

SUMMARY

00:24:32 

 * RESULT: FAIL

00:24:32 

 * TESTS: 0

00:24:32 

 * ERRORS: 1

00:24:32 

 * FAILURES: 0
```

**Comment by furushchev** [comment]
Travis failed on no response from jenkins.

```bash
next build number is 120
wait for trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash 120
start building, wait for result....
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash/120/ building:  True result:  None progress:  0.25881197114
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash/120/ building:  True result:  None progress:  0.355739388567
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash/120/ building:  True result:  None progress:  0.452656280929
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash/120/ building:  True result:  None progress:  0.548991920668
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash/120/ building:  True result:  None progress:  0.645421322715
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash/120/ building:  True result:  None progress:  0.742324462035
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash/120/ building:  True result:  None progress:  0.627118829848
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash/120/ building:  True result:  None progress:  0.699198943222
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash/120/ building:  True result:  None progress:  0.771281866335
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash/120/ building:  True result:  None progress:  0.843418986284
The job exceeded the maximum time limit for jobs, and has been terminated.
```

But build on jenkins finished successfully in 15 minutes.

```bash
14:42:16 Summary: 67 tests, 0 errors, 0 failures, 0 skipped
14:42:16 + '[' -e /workspace/.ros/test_results/ ']'
14:42:16 + travis_time_end
14:42:16 + set +x
14:42:16 traivs_time:end:4mzjsxwt:start=1497418935996499087,finish=1497418936454803850,duration=458304763
14:42:16 
14:42:16 traivs_fold:end:after_script<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
14:42:16 Function after_script takes 0 min 0 sec
14:42:25 + pwd
14:42:25 /var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash/workspace@2/jenkins-trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash-120/jsk-ros-pkg/jsk_recognition
14:42:25 + sudo rm -fr /var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash/workspace@2/jenkins-trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-jsk-pcl-ros-utils-jsk-pcl-ros-CI-SOURCE-PATH-travis-before-script-pcl1-8-bash-120
14:42:27 Finished: SUCCESS
```

It's strange.....

**Comment by k-okada** [comment]
that's 14時42分
and it takes 所要時間 1 時間 44 分
so if travis wait for 15 min until jenkins start, it will overt 120 min.

--
◉ Kei Okada


2017-06-15 11:21 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Wow, nice catch! Anyway, I restarted. If this still does not solve the issue, I'll look into the worker deeper.

**Comment by furushchev** [comment]
@k-okada Sorry, the tests already passed. Please merge if there is no problem.

**Pull request merged**
