### PR TITLE
[jsk_recognition_msgs, jsk_pcl_ros] add and publish edge message

### PR DESCRIPTION
**Pull request by mmurooka**
part of #2027

- Add Edge.msg EdgeArray.msg.
- Publish EdgeArray message in edge_depth_refinement_nodelet.

rviz plugin for visualization is https://github.com/jsk-ros-pkg/jsk_visualization/pull/665/commits/05eb6faf9eb141d30dde01a7c1b1c9da59cdb18e in https://github.com/jsk-ros-pkg/jsk_visualization/pull/665 .

### CODE REVIEW

**Comment by mmurooka** [comment]
visualization_msgs/Marker might be available for visualization, but I think we should add edge message for treating edge information in many nodelets. (same as polygon, boundingbox, etc..)

**Comment by wkentaro** [comment]
@mmurooka Do you want to distinguish segment and edge? And that's why you choose edge for the message name.

**Comment by mmurooka** [comment]
I don't intend to distinguish segment and edge.
And, I made this message before I know jsk_recognition_utils/geo/Segment.cpp.

Segment, SegmentArray is better?

**Comment by wkentaro** [comment]
Considering relationship of Edge ⊂ Segment, someone may add segment in the future, and I think Segment is better if you don't have any special intention.

**Comment by YoheiKakiuchi** [comment]
ping @mmurooka @wkentaro

**Comment by YoheiKakiuchi** [comment]
ping @mmurooka @wkentaro

**Comment by mmurooka** [comment]
I'll rename Edge to Segment (is that OK? > @wkentaro ), and make another PR.

**Comment by wkentaro** [comment]
OK

**Pull request closed without merging**
