### PR TITLE
[jsk_pcl_ros] Add Kinfu nodelet

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
jenkins failed because of git error?

```
+ wstool info -t src
WARNING [vcstools] Command failed: 'git status -s  -uno'
 run at: '/workspace/ros/ws_jsk_recognition/src/jsk_recognition'
 errcode: 128:
fatal: Not a git repository: /var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_recognition-hydro-deb-true-true-jsk_pcl_ros/workspace/jenkins-trusty-travis-jsk-ros-pkg-jsk_recognition-hydro-deb-true-true-jsk_pcl_ros-629/jsk-ros-pkg/jsk_recognition/.git/modules/.travis
```

**Comment by garaemon** [comment]
reboot?

**Comment by k-okada** [comment]
this is strange, I rebooted yesterday and
https://travis-ci.org/jsk-ros-pkg/jsk_recognition/builds/66730315 passed,

--
◉ Kei Okada

**Comment by k-okada** [comment]
where does `-uno` come from

**Comment by garaemon** [comment]
> where does -uno come from???

wsinfo?

**Comment by garaemon** [comment]
I found my CMakeLists has illegal syntax. probably that's my faul.

**Pull request merged**
