### PR TITLE
[WIP] Move README from GitHub to docs.ros.org

### LINKED ISSUE #330: jsk_pcl_ros documentation
documentを作る。
* 何をするためのコードか
* パラメータの一覧
* ユースケース
* デモ画像・動画

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #330

- [ ] Need search form in api page
- [ ] Move README of jsk_pcl_ros to api page

### CODE REVIEW

**Comment by garaemon** [comment]
How about write contents of REAME.md in header files?

**Comment by wkentaro** [comment]
Yeah, I think it's a good idea, I like it. 
In that case, however  the things we should think about is

1. how to generate pages from parsed by doxygen
1. how to handle executables which has no header files (ex. python files)
1. possible frequent change of header file which makes log difficult to look back
1. how to handle static files (ex images)

3 becomes not so a big problem if the documentation is small, however when we want to add some more information (ex tutorial, how to run programs), it will be changed frequently and it's very annoying. Also it is difficult to handle source codes consistently, which is similar problem with 2)

**Comment by garaemon** [comment]
> how to generate pages from parsed by doxygen

Difficult, 

> how to handle executables which has no header files (ex. python files)

we can use doxygen to generate python document http://www.doxygen.jp/docblocks.html, but using sphinx for python makes sense.

Fortunately, jsk_recognition does not have re-usable python code.

> possible frequent change of header file which makes log difficult to look back

document is automatically generated when we release a new version, so there would be no problem.


> how to handle static files (ex images)

image command is available http://www.doxygen.jp/commands.html#cmdimage

**Comment by garaemon** [comment]
We do not need perfect solution, please make steps clear to make better documment and I will merge PRs step by step.

**Comment by garaemon** [comment]
So first, I'd like to merge rosdoc.yaml only and check result of docs.ros.org before separating md file.

**Comment by wkentaro** [comment]
Ok, I sent PR: #1096

**Comment by k-okada** [comment]
I 've created prototype for this -> https://github.com/jsk-ros-pkg/jsk_recognition/pull/1097, I'm afraid it only compile every 3 days, so we have time to discuss:

- Should we keep ONE file for package documentation or separate them?
- If we can agree on separate files, then where should we put them:
 - put under doc/ directory
 - keep documentation on the header ( and is it possible ? )

**Comment by garaemon** [comment]
If we can allow special landmarks in header, it's easy to generate markdown from header.

```c++
  /**
__MARKDOWN__
This is a sample of markdown written in header
=============================

hello world.
     
* hello world
  * hello world.
* hello world.
__EOF_MARKDOWN__
   */
  class AddColorFromImage: public jsk_topic_tools::DiagnosticNodelet
  {
  public:
  };
```

command to generate markdown
```
sed -n -e "/__MARKDOWN__/,/__EOF_MARKDOWN__/p" add_color_from_image.h | grep -v __MARKDOWN__ | grep -v __EOF_MARKDOWN__ > hoge.md
```

markdown result
```markdown
This is a sample of markdown written in header
=============================

hello world.
     
* hello world
  * hello world.
* hello world.
```

**Comment by garaemon** [comment]
* one markdown
  * pros
     * rendered on github without no effort
     * easy-to-search (`C-f`)
  * cons
     * too large
     * no API docs like doxygen
* separated markdown
  * pros 
    * small files
    * Can use readthedocs full-search
  * cons
    * trouble in maintaining
* doxygen
  * pros
    * code api
    * hosting on docs.ros.org and support link over different packages
  * cons
    * poor full-text search on docs.ros.org
    * not generated until new version released

**Comment by garaemon** [comment]
* generate markdown from headers with landmarks
  * pros
    * small files
    * can use readthedocs and full-text search on it
    * good at maintenance, documentation is near to the code
  * cons
    * too hacky
    * no api docs

**Comment by garaemon** [comment]
* cldoc. see [here](http://kumar.hateblo.jp/entry/2014/10/09/024218)
  * pros
    * code api
    * readthedocs hosting and full-text search
  * cons
    * how to run with catkin?
    * no links over different packages

**Comment by k-okada** [comment]
On Wed, Aug 26, 2015 at 11:28 AM, Ryohei Ueda <notifications@github.com>
wrote:

>
>    -
>       -
>          - not generated until new version released
>
>
it depends on configurations (
https://github.com/ros/rosdistro/blob/master/indigo/distribution.yaml#L3572
) but usually
it runs ever 3 days from HEAD of master branch.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
+1 for
* separated md + generate md from header files (hosting at readthedocs)
* doxygen for code api (hosting at docs.ros.org)

It supports both node/code api, full text search, and contributor friendly
because docs and code are at same place.
With separated md I mean to make it possible manually adding the document
(maybe under doc/) for nodes which have no header files. We have codes not
only c++ but also python and euslisp, so I think extendable solution should
be selected.
Also I think using landmark is simple enough not too hacky.

2015年8月26日水曜日、Kei Okada<notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:

> On Wed, Aug 26, 2015 at 11:28 AM, Ryohei Ueda <notifications@github.com>
> wrote:
>
> >
> > -
> > -
> > - not generated until new version released
> >
> >
> it depends on configurations (
> https://github.com/ros/rosdistro/blob/master/indigo/distribution.yaml#L3572
> ) but usually
> it runs ever 3 days from HEAD of master branch.
>
> --
> ◉ Kei Okada
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1092#issuecomment-134797214>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by garaemon** [comment]
About nodes which have no header files, I think we can just add header files for them.

**Comment by garaemon** [comment]
> +1 for
> * separated md + generate md from header files (hosting at readthedocs)
> * doxygen for code api (hosting at docs.ros.org)

sounds good to me.

**Comment by garaemon** [comment]
And also I'd like to use it for some packages like jsk_topic_tools, jsk_pcl_ros, jsk_perception.

**Comment by wkentaro** [comment]
http://docs.ros.org/indigo/api/jsk_perception/html/

seems updated.

but cannot see the contents in README.

2015年8月27日木曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> And also I'd like to use it for some packages like jsk_topic_tools,
> jsk_pcl_ros, jsk_perception.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1092#issuecomment-135285565>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by k-okada** [comment]
yeah, they use old doxygen and it did not read markdown -> https://github.com/jsk-ros-pkg/jsk_recognition/pull/1118

another wey to use rosdoc is use sphinx as build and `pandoc README.md --output=index.rst`. This will ok (but image is displayed with original size)

I'm -1 for 
`generate md from header files`
if there is no existing tools, and we can not find maintainer for that script, who can support more than 5 years.

launchdoc project is just a 4 years ago and it is not maintained anymore....
https://github.com/jsk-ros-pkg/jsk_common/blob/master/jsk_tools/bin/launchdoc-generator.py

**Comment by k-okada** [comment]
so I think current options is
- sphinx + doc.ros.org
- readthedoc that interpret <repository>/README.md, and if each package maintainer prefer to small files for documentation, then they create documents and make link from <reaposiory>/README

**Comment by wkentaro** [comment]
The problem we're resolving is:
* Code API (needed by @garaemon)
* Too large file and few information in README.md (which I have a critical mind for)

So doxygen is necessary so 'sphinx + docs.ros.org' maybe unable to fix this problem.
docs.ros.org does allow few customization so we can't use doxygen and breathe for sphinx.

The second option is same as 'separated markdown' in practice at https://github.com/jsk-ros-pkg/jsk_recognition/pull/1092#issuecomment-134795667
So need agreement of @garaemon .

**Comment by garaemon** [comment]
> The second option is same as 'separated markdown' in practice at #1092 (comment)
> So need agreement of @garaemon .
>  Show all checks

Hmm, ok let's start with `separated markdown` managiment and see how it is easy/difficult to maintain.

**Comment by wkentaro** [comment]
Moved to: https://github.com/jsk-ros-pkg/jsk_recognition/pull/1159

**Pull request closed without merging**
