### PR TITLE
add negative rosparam in mask_image_filter

### PR DESCRIPTION
**Pull request by takayuki5168**
I added `negative` rosparam like [thi](https://jsk-recognition.readthedocs.io/en/latest/jsk_perception/nodes/apply_mask_image.html).

If someone thinks this PR as correct modification, I will also update docs.

### CODE REVIEW

**Comment by knorth55** [comment]
@takayuki5168 can you write a test for `mask_image_filter`?

**Comment by takayuki5168** [comment]
@knorth55 Should I write a test [here](https://github.com/jsk-ros-pkg/jsk_recognition/tree/master/jsk_pcl_ros/sample)?

**Comment by knorth55** [comment]
@takayuki5168 here https://github.com/jsk-ros-pkg/jsk_recognition/tree/master/jsk_pcl_ros/test

**Comment by takayuki5168** [comment]
@knorth55 On my understanding, first I implement sample launch file of mask_image_filter, then I implement test launch file with rosbag file in this repo. Is that right?

**Comment by knorth55** [comment]
@takayuki5168 that is better. please add sample and test together

**Comment by takayuki5168** [comment]
@knorth55 I added sampl and test code for mask_image_filter.

Test code always successes, but sometimes dump error of `ROS time moved backwards` like below.

This occurrs because rosbag is looped sometimes with `rosbag play -l hoge.bag`, so time of ROS is backed when rosbag returns from end to start.

```bash
$ rostest jsk_pcl_ros test_mask_image_filter.test 
... logging to /home/takayuki/.ros/log/rostest-takayuki-ThinkPad-T460s-31161.log
[ROSUNIT] Outputting test results to /home/takayuki/.ros/test_results/jsk_pcl_ros/rostest-test_test_mask_image_filter.xml
[ INFO] [1559278718.189060862]: Initializing nodelet with 4 worker threads.
Traceback (most recent call last):
  File "/home/takayuki/ros/kinetic/src/jsk-ros-pkg/jsk_common/jsk_tools/src/test_topic_published.py", line 102, in <module>
    rostest.run(PKG, NAME, TestTopicPublished, sys.argv)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/__init__.py", line 146, in rosrun
    result = rosunit.create_xml_runner(package, test_name, result_file).run(suite)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosunit/xmlrunner.py", line 261, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/takayuki/ros/kinetic/src/jsk-ros-pkg/jsk_common/jsk_tools/src/test_topic_published.py", line 97, in test_published
    rospy.sleep(0.01)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/timer.py", line 164, in sleep
    raise rospy.exceptions.ROSTimeMovedBackwardsException(time_jump)
rospy.exceptions.ROSTimeMovedBackwardsException: ROS time moved backwards
[Testcase: testtest_mask_image_filter] ... ok

[ROSTEST]-----------------------------------------------------------------------


SUMMARY
 * RESULT: SUCCESS
 * TESTS: 0
 * ERRORS: 0
 * FAILURES: 0

rostest log file is in /home/takayuki/.ros/log/rostest-takayuki-ThinkPad-T460s-31161.log
```

**Comment by knorth55** [comment]
hmm, the error does  not happen to me :(
anyway, test and sample works fine.

**Comment by YutoUchimi** [comment]
@takayuki5168 Good feature. Can you please update document?

**Comment by takayuki5168** [comment]
@YutoUchimi I added.

I don't know how html doc is generated by rst file. How can I confirm the html doc is correctly modified?

**Comment by YutoUchimi** [comment]
1. Go to document directory.
```
roscd jsk_recognition; cd ../doc
```

2. Set up virtualenv.
```
source setup.sh
```

3. Run sphinx build.
```
make html
```

4. Check if document is successfully built with browser.
```
google-chrome _build/html/index.html
```

**Comment by knorth55** [comment]
@takayuki5168 probably you wrongly made branch on `jsk-ros-pkg/jsk_recognition`.
https://github.com/jsk-ros-pkg/jsk_recognition/tree/update-mask-image-filter
please do not use branch on `origin`

**Comment by takayuki5168** [comment]
@knorth55 Sorry I mistook. I deleted branch on `origin` and updated branch on folked repo.

**Comment by k-okada** [comment]
@takayuki5168 If you learn something new, it is always better to update the
document.
so, please add how to generate doc on your local machine , for example ->
https://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/tips.html

--
◉ Kei Okada



2019年6月19日(水) 16:27 Yuto Uchimi <notifications@github.com>:

**Comment by takayuki5168** [comment]
@k-okada

**Pull request merged**
