### PR TITLE
[Major Release] Migrate srv files from jsk_pcl_ros to jsk_recognition_msgs for #1914

### PR DESCRIPTION
**Pull request by wkentaro**
## Background

Some packages in jsk_visualization depends on jsk_pcl_ros because it uses the srv files.
But jsk_pcl_ros is a very large package and the dependency should be avoided ideally.
The solution is placing `msg/srv` files into `jsk_recognition_msgs`.

## Plans

1. Merge this after `jsk_recognition_msgs` is released: http://repositories.ros.org/status_page/ros_indigo_default.html?q=jsk_recognition_msgs
1. Release this pacakge.
1. Remove `jsk_pcl_ros/srv`.
1. Release `jsk_pcl_ros`.

## Related PRs

- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1827
- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1914

### CODE REVIEW

**Comment by k-okada** [comment]
all tests except .4 failing
```
                                                ^
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/depth_calibration_nodelet.cpp:98:3: error: expected ',' or ';' before '{' token
   {
   ^
make[2]: *** [CMakeFiles/jsk_pcl_ros.dir/src/depth_calibration_nodelet.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/incremental_model_registration_nodelet.cpp: In member function 'virtual void jsk_pcl_ros::IncrementalModelRegistration::callICP(pcl::PointCloud<pcl::PointXYZRGB>::Ptr, pcl::PointCloud<pcl::PointXYZRGB>::Ptr, Eigen::Affine3f&)':
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/incremental_model_registration_nodelet.cpp:187:5: error: 'ICPAlign' was not declared in this scope
     ICPAlign srv;
     ^
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/incremental_model_registration_nodelet.cpp:187:5: note: suggested alternative:
In file included from /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/incremental_model_registration_nodelet.cpp:42:0:
/workspace/ros/ws_jsk_recognition/devel/.private/jsk_recognition_msgs/include/jsk_recognition_msgs/ICPAlign.h:18:8: note:   'jsk_recognition_msgs::ICPAlign'
 struct ICPAlign
        ^
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/incremental_model_registration_nodelet.cpp:187:14: error: expected ';' before 'srv'
     ICPAlign srv;
              ^
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/incremental_model_registration_nodelet.cpp:188:5: error: 'srv' was not declared in this scope
     srv.request.reference_cloud = reference_ros;
     ^
make[2]: *** [CMakeFiles/jsk_pcl_ros.dir/src/incremental_model_registration_nodelet.cpp.o] Error 1
```

**Comment by k-okada** [comment]
does this mean if someone uses latest jsk_recognition, without changing srv/msg files location from jsk_pcl_ros to jsk_recognition_msgs, the compile fails?

**Comment by wkentaro** [comment]
No, it can't be. The fail just caused by remaining migration.
(because of abbreviated namespace for using message)

**Comment by k-okada** [comment]
please update -> https://github.com/jsk-ros-pkg/jsk_recognition/pull/1827#issuecomment-256150923

**Comment by wkentaro** [comment]
> please update -> #1827 (comment)

Updated.

**Comment by k-okada** [comment]
```

+++sh -c '$CI_SOURCE_PATH/.travis_before_script_hydro.bash'
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
     Performing actions: 
     Add new elements:
  jsk_recognition/jsk_recognition_msgs
Config changed, maybe you need run wstool update to update SCM entries.
Overwriting /home/travis/ros/ws_jsk_smart_apps/src/.rosinstall
update complete.
Prepare updating http://github.com/jsk-ros-pkg/jsk_smart_apps (version None) to /home/travis/ros/ws_jsk_smart_apps/src/jsk_smart_apps
Url https://github.com/jsk-ros-pkg/jsk_smart_apps.git does not match http://github.com/jsk-ros-pkg/jsk_smart_apps requested.
  (d)elete and replace, (a)bort, (i)nplace delete and replace at symlink, (s)kip: 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```
something wrong with the script @wkentaro

**Comment by wkentaro** [comment]
Here?

**Comment by k-okada** [comment]
moved to https://github.com/jsk-ros-pkg/jsk_smart_apps/pull/68#issuecomment-263214213

**Comment by k-okada** [comment]
@wkentaro please check again, It seems we still have old code -> https://github.com/jsk-ros-pkg/jsk_recognition/pull/2021

**Comment by wkentaro** [comment]
@k-okada Thank you for the report. I found a bug in the migration code: https://github.com/jsk-ros-pkg/jsk_common/issues/1506

**Pull request merged**
