### PR TITLE
Add face detector

### PR DESCRIPTION
**Pull request by hyaguchijsk**
I added face detector node which can run with monocular camera.
`detectMultiScale` returns face regions as rectangle array,
so I added `RectArray.msg` into `jsk_recognition_msgs`.

### CODE REVIEW

**Comment by garaemon** [comment]
Does it solve any problem about face_detector? http://wiki.ros.org/face_detector

**Comment by hyaguchijsk** [comment]
I want to use face detection with monocular camera.


2015-02-10 22:19 GMT+09:00 Ryohei Ueda <notifications@github.com>:

**Comment by k-okada** [comment]
please use
https://github.com/ros-perception/vision_opencv/tree/indigo/opencv_apps

--
◉ Kei Okada

**Comment by hyaguchijsk** [comment]
Oh, I missed it... Thanks


2015-02-10 22:41 GMT+09:00 Kei Okada <notifications@github.com>:

**Comment by garaemon** [comment]
there is another package called face_recognition: http://wiki.ros.org/face_recognition

**Pull request closed without merging**
