### PR TITLE
Fully Convolutional Networks for Object Segmentation

### PR DESCRIPTION
**Pull request by wkentaro**
## Description

This is deep learning approach for object segmentation. It can segment 20 objects with the trained model distributed from the author.
Paper: http://people.eecs.berkeley.edu/~jonlong/long_shelhamer_fcn.pdf

I [implemented it with Chainer](http://github.com/wkentaro/fcn) and created ROS node.

image

Depends on https://github.com/ros/rosdistro/pull/11802

### CODE REVIEW

**Comment by k-okada** [comment]
please add another example which seems hard to solve existing technique,
this example look like color (or histogram) based segmentation.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
really? Human can be segmented like the picture with color histogram?

**Comment by k-okada** [comment]
your example is almost equal to ->
http://www.societyofrobots.com/programming_computer_vision_tutorial_pt3.shtml#middle_mass

--
◉ Kei Okada

**Comment by wkentaro** [comment]
I dont think so, because the pictures in your attached site does not detect
human.
but i will respect your thought and update the picture.

2016年6月13日月曜日、Kei Okada<notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:

> your example is almost equal to ->
>
> http://www.societyofrobots.com/programming_computer_vision_tutorial_pt3.shtml#middle_mass
>
> --
> ◉ Kei Okada
>
>
> On Mon, Jun 13, 2016 at 10:26 AM, Kentaro Wada <notifications@github.com>
> wrote:
>
> > really? Human can be segmented like the picture with color histogram?
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_recognition/pull/1740#issuecomment-225472704
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAeG3Pd4ercxM-0SEMhYsqYYp6Xi8fs5ks5qLLHhgaJpZM4IznXd
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1740#issuecomment-225484513>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEHFk94w21shLrKXla2VWGCsM5dRdYQaks5qLNRcgaJpZM4IznXd>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
## New Demonstration Image

screenshot 2016-06-21 14 26 18

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
**Please merge this!**

**Comment by wkentaro** [comment]
@k-okada Any problems to merge this PR?

**Comment by k-okada** [comment]
no

**Pull request merged**
