### PR TITLE
[jsk_perception] Run roslint for python code

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
it hangs on hydro
image

**Comment by garaemon** [comment]
Need to update package.xml patch in order to release newer version after merge this.

**Comment by garaemon** [comment]
Check if patch to package.xml is required or not first.

**Comment by wkentaro** [comment]
Sorry I don't understand what u mean.
What should I do?
I think roslint needs to be test_depend.

**Comment by garaemon** [comment]
patch process of bloom is really complexed and I don't know we can do it
with PR...

@k-okada what do you think?

2015年12月16日水曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> Sorry I don't understand what u mean.
> What should I do?
> I think roslint needs to be test_depend.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1398#issuecomment-164966820>
> .
>


-- 
✉︎ from iPhone

**Comment by k-okada** [comment]
I'm happy if you do not break this patch,
https://github.com/tork-a/jsk_recognition-release/blob/patches/release/indigo/jsk_perception/0001-comment-out-pip-depends.patch
so you do not have to move robot_self_filter location
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1398/files

--
◉ Kei Okada

**Comment by wkentaro** [comment]
> so you do not have to move robot_self_filter location

Looks good now?

**Comment by k-okada** [comment]
yes

**Comment by wkentaro** [comment]
on hydro
```
jsk_perception/test_results/jsk_perception/roslint-jsk_perception.xml: 1 tests, 0 errors, 1 failures
```

on jade
```
jsk_perception/test_results/jsk_perception/roslint-jsk_perception.xml: 1 tests

jsk_perception/test_results/jsk_perception/rostest-test_slic_super_pixels.xml: 1 tests

jsk_perception/test_results/jsk_perception/rostest-test_sparse_image.xml: 1 tests

jsk_perception/test_results/jsk_perception/rostest-test_test_label_image_decomposer_slop.xml: 1 tests

jsk_perception/test_results/jsk_perception/rosunit-sparse_image_test.xml: 2 tests

jsk_perception/test_results/jsk_perception/rosunit-test_label_image_decomposer_slop.xml: 1 tests

jsk_perception/test_results/jsk_perception/rosunit-test_slic_super_pixels.xml: 1 tests

jsk_recognition_utils/test_results/jsk_recognition_utils/gtest-test_cv_utils.xml: 1 tests

jsk_recognition_utils/test_results/jsk_recognition_utils/gtest-test_rgb_colors.xml: 1 tests

jsk_recognition_utils/test_results/jsk_recognition_utils/rostest-test_test_tf_listener_singleton.xml: 1 tests

jsk_recognition_utils/test_results/jsk_recognition_utils/rosunit-test_tf_listener_singleton.xml: 1 tests

Summary: 19 tests, 0 errors, 0 failures
```

**Comment by wkentaro** [comment]
```
 fatal: unable to access 'https://github.com/garaemon/SLIC-Superpixels.git/': Could not resolve host: github.com 

[jsk_perception] make: *** [build/patched-SLIC-Superpixels] Error 128         
```

**Comment by wkentaro** [comment]
Now I disable roslint test on hydro.

**Comment by wkentaro** [comment]
Could you please review and merge this?

**Pull request merged**
