### PR TITLE
Fix special character for double to print

### PR DESCRIPTION
**Pull request by wkentaro**
@furushchev It seems you changed the line before. Could you please review this?

### CODE REVIEW

**Comment by furushchev** [comment]
@wkentaro This is a percentage, so it is better not to remove the last `%`.

**Comment by wkentaro** [comment]
Oh, I see. I thought it was typo of `~%` for euslisp..

**Comment by wkentaro** [comment]
Fixed.

**Comment by furushchev** [comment]
@wkentaro Thanks. Now ok to merge.

**Comment by wkentaro** [comment]
Please merge this.

**Pull request merged**
