### PR TITLE
Decompose labels with their names listed as legend

### PR DESCRIPTION
**Pull request by wkentaro**
## What is this?

**before -> after**

## Why?

- For visualization of segmentation result.

hrp2_apc_label_image_decomposer_with_names

### CODE REVIEW

**Comment by wkentaro** [comment]
Also update the image for documentation:
hrp2_apc_label_image_decomposer_with_names

**Comment by wkentaro** [comment]
```
flags:   -Wno-deprecated -fopenmp


CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:163 (message):


  catkin_package() DEPENDS on 'pcl' which must be find_package()-ed before.


  If it is a catkin package it can be declared as CATKIN_DEPENDS instead


  without find_package()-ing it.


Call Stack (most recent call first):


  /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)


  CMakeLists.txt:264 (catkin_package)


```

**Comment by k-okada** [comment]
try find_package(PCL)

--
◉ Kei Okada

**Comment by wkentaro** [comment]
```
...............................................................................

Finished <<< jsk_recognition_utils                  [ 12.1 seconds ]

Starting >>> imagesift                             

Starting >>> jsk_pcl_ros_utils                     

_______________________________________________________________________________

Errors << imagesift:cmake /workspace/ros/ws_jsk_recognition/logs/imagesift/build.cmake.000.log

CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:163 (message):


  catkin_package() DEPENDS on 'libsiftfast' which must be find_package()-ed


  before.  If it is a catkin package it can be declared as CATKIN_DEPENDS


  instead without find_package()-ing it.


Call Stack (most recent call first):


  /opt/ros/indigo/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)


  CMakeLists.txt:16 (catkin_package)


```

**Comment by wkentaro** [comment]
Please merge this

**Comment by wkentaro** [comment]
please merge this.

**Comment by wkentaro** [comment]
**Please merge this!**

**Comment by k-okada** [comment]
I'm reading emails as FIFO rule, so if you send multiple e-mails, your request always stay in queue.

**Comment by wkentaro** [comment]
Sorry for my hasty requests.

**Pull request merged**
