### PR TITLE
[jsk_perception] Rename download_trained_data -> install_trained_data.py

### PR DESCRIPTION
**Pull request by wkentaro**
To follow install_test_data.py.

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
does this requires some changes to downstream packages?
need rebase

**Comment by wkentaro** [comment]
No, this is just a refactoring.

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
> This branch has conflicts that must be resolved

**Comment by wkentaro** [comment]
oops.

**Pull request merged**
