### PR TITLE
[jsk_perception] Ignore slic dir which is cloned at building time

### PR DESCRIPTION
**Pull request by wkentaro**
Modified:
  - jsk_perception/.gitignore

### CODE REVIEW

**Comment by wkentaro** [comment]
Could you please review and merge this?

**Comment by garaemon** [comment]
I believe slic is cloned in build directory

**Comment by wkentaro** [comment]
Ah, slic as submodule commit is reverted now. https://github.com/jsk-ros-pkg/jsk_recognition/pull/1429
Thanks.

**Comment by garaemon** [comment]
Yeah, unfortunately, ros buildfarm does not support submodule.

**Pull request closed without merging**
