### PR TITLE
Stop depending on pkgs in jsk_visualization

### PR DESCRIPTION
**Pull request by wkentaro**
For https://github.com/jsk-ros-pkg/jsk_recognition/pull/1837#issuecomment-278814833
Dependency graph: jsk_visualization **depends on** jsk_recognition

### CODE REVIEW

**Comment by wkentaro** [comment]
Replaced rqt by python node to make test pass:
screen shot 2017-03-09 at 3 06 26

**Comment by k-okada** [comment]
I think it is very hard to build clean dependency within jsk-ros-pkg, so it ok to have cross dependency, so create node and test different PR and wait for release of upstream repository, for me ts ok to have -6 month delay between these updates.

**Comment by wkentaro** [comment]
> so create node and test different PR and wait for release of upstream repository,

Sorry. What do you mean by this?

**Comment by k-okada** [comment]
waiting for https://github.com/ros-visualization/rqt_common_plugins/pull/442

**Comment by wkentaro** [comment]
@k-okada The dependency graph is like below, so can I close this?

- **jsk_rviz_plugins** depends on
  - jsk_recognition_msgs
  - jsk_recognition_utils
- **jsk_pcl_ros** depends on
  - jsk_recognition_msgs
  - jsk_recognition_utils
  - jsk_rviz_plugins
  - jsk_rqt_plugins

**Comment by k-okada** [comment]
Thanks 
What we learned is there is build time depends, runtime depends and test time depends
We must be vary careful about build time depends, but as for runtime/test depends we must find good compromise

**Pull request closed without merging**
