### PR TITLE
Specify requirements versions for doc

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by garaemon** [comment]
New version of robot_self_filter has just released.
It should be solved by the new package in 1-2 day.

**Comment by wkentaro** [comment]
```
[resized_image_transport] Linking CXX executable /workspace/ros/ws_jsk_recognition/devel/lib/resized_image_transport/log_polar 

[resized_image_transport] Linking CXX executable /workspace/ros/ws_jsk_recognition/devel/lib/resized_image_transport/image_resizer 

[resized_image_transport] //usr/bin/ld: CMakeFiles/image_resizer.dir/image_resizer.cpp.o: undefined usrreference /binto symbol/ld: CMakeFiles/log_polar.dir/log_polar.cpp.o: undefined reference to symbol '_ZN5boost15program_options29options_description_easy_initclEPKcS3_' 

[resized_image_transport] //usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.54.0: error adding symbols: DSO missing  from '_ZN5boost15program_options29options_description_easy_initclEPKcS3_command line' 

[resized_image_transport]                                                       

[resized_image_transport] //usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.54.0: error adding symbols: DSO missing from command line 

[resized_image_transport] collect2: error: ld returned 1 exit status            

[resized_image_transport] collect2: error: ld returned 1 exit status            

[resized_image_transport] make[2]: make[2]: *** [/workspace/ros/ws_jsk_recognition/devel/lib/resized_image_transport/log_polar] Error 1*** [/workspace/ros/ws_jsk_recognition/devel/lib/resized_image_transport/image_resizer] Error 1 

[resized_image_transport]                                                       

[resized_image_transport] make[1]: *** [CMakeFiles/log_polar.dir/all] Error 2   

[resized_image_transport] make[1]: *** Waiting for unfinished jobs....          

[resized_image_transport] make[1]: *** [CMakeFiles/image_resizer.dir/all] Error 2 
```

**Comment by wkentaro** [comment]
regression of https://github.com/jsk-ros-pkg/jsk_common/pull/1231

**Comment by wkentaro** [comment]
https://github.com/jsk-ros-pkg/jsk_common/pull/1264
will fix this problem.

**Comment by wkentaro** [comment]
```
[nlopt] [rosbuild] Downloading http://ab-initio.mit.edu/nlopt/nlopt-2.3.tar.gz to build/nlopt-2.3.tar.gz...Traceback (most recent call last): 

[nlopt]   File "/opt/ros/jade/share/ros/core/rosbuild/bin/download_checkmd5.py", line 89, in <module> 

[nlopt]     sys.exit(main())                                                    

[nlopt]   File "/opt/ros/jade/share/ros/core/rosbuild/bin/download_checkmd5.py", line 61, in main 

[nlopt]     urllib.urlretrieve(uri, dest)                                       

[nlopt]   File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve          

[nlopt]     return _urlopener.retrieve(url, filename, reporthook, data)         

[nlopt]   File "/usr/lib/python2.7/urllib.py", line 240, in retrieve            

[nlopt]     fp = self.open(url, data)                                           

[nlopt]   File "/usr/lib/python2.7/urllib.py", line 208, in open                

[nlopt]     return getattr(self, name)(url)                                     

[nlopt]   File "/usr/lib/python2.7/urllib.py", line 345, in open_http           

[nlopt]     h.endheaders(data)                                                  

[nlopt]   File "/usr/lib/python2.7/httplib.py", line 975, in endheaders         

[nlopt]     self._send_output(message_body)                                     

[nlopt]   File "/usr/lib/python2.7/httplib.py", line 835, in _send_output       

[nlopt]     self.send(msg)                                                      

[nlopt]   File "/usr/lib/python2.7/httplib.py", line 797, in send               

[nlopt]     self.connect()                                                      

[nlopt]   File "/usr/lib/python2.7/httplib.py", line 778, in connect            

[nlopt]     self.timeout, self.source_address)                                  

[nlopt]   File "/usr/lib/python2.7/socket.py", line 553, in create_connection   

[nlopt]     for res in getaddrinfo(host, port, 0, SOCK_STREAM):                 

[nlopt] IOError: [Errno socket error] [Errno -2] Name or service not known      

[nlopt] make[3]: *** [build/nlopt-2.3/unpacked] Error 1                         

[nlopt] make[2]: *** [/workspace/ros/ws_jsk_recognition/devel/lib/libnlopt_cxx.so] Error 2 

[nlopt] make[1]: *** [CMakeFiles/libnlopt_cxx.dir/all] Error 2                  

[nlopt] make: *** [all] Error 2                                                 

[nlopt] <== '/workspace/ros/ws_jsk_recognition/build/nlopt/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' failed with return code '2' 
```

**Pull request merged**
