### PR TITLE
Add sample to calibrate and rectify insta360 air image

### PR DESCRIPTION
**Pull request by 708yamaguchi**
Merge after https://github.com/jsk-ros-pkg/jsk_recognition/pull/2553

I add sample to split, calibrate and rectify insta360 air image.
When rectify the image, I use `add_camera_info.py`.
This node add camera_info to splitted insta360 air images, which do not have camera_info.

|raw|after calib fore|after calib back|
|--|--|--|
||||

### CODE REVIEW

**Comment by knorth55** [comment]
how about `camera_info_publisher.py` instead of `add_camera_info.py`?

**Comment by 708yamaguchi** [comment]
@knorth55 

I found that `camera_info_publisher` (the exact same name!) already exists in jsk-ros-pkg/jsk_visualization.
https://github.com/jsk-ros-pkg/jsk_visualization/blob/master/jsk_interactive_markers/jsk_interactive_marker/src/camera_info_publisher.cpp

I decide to use this node instead of creating new node.
Now, I create pull request, which enables existing `camera_info_publisher` to load camera info yaml file.
https://github.com/jsk-ros-pkg/jsk_visualization/pull/793

Thank you for your advice.

**Review by k-okada — CHANGES_REQUESTED** [review]
can you add bag file of insta360 and test code? @708yamaguchi

**Comment by 708yamaguchi** [comment]
Thank you for your advice.

I add rosbag and test script for insta360 air.

Currently, I do not test rectification feature, because rectification process depends on jsk_interactive_marker/camera_info_publisher and jsk_perception does not depends on jsk_interactive_marker.

**Comment by 708yamaguchi** [comment]
Travis tests with indigo fail because `gdown` command does not work correctly and insta360_air.bag is not downloaded.
This problem happens only with indigo, (maybe) because indigo's default requests module is low version (2.2.1) and does not have [socks] extras_require.
https://travis-ci.com/github/jsk-ros-pkg/jsk_recognition/jobs/478096527
https://travis-ci.com/github/jsk-ros-pkg/jsk_recognition/jobs/478096529
https://travis-ci.com/github/jsk-ros-pkg/jsk_recognition/jobs/478096530
```Traceback (most recent call last):
  File "/usr/local/bin/gdown", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 633, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2299, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.2.1 has no such extra feature 'socks'
```
I created PR to gdown to fix this problem.https://github.com/wkentaro/gdown/pull/89
I think that this travis failure will fix when the next version of gdown is released.
In this PR, I added travis BEFORE_SCRIPT as a temporary fix.

**Comment by 708yamaguchi** [comment]
We can also use this package:
https://github.com/tu-darmstadt-ros-pkg/image_projection

Thank you for your infomation, @knorth55

**Comment by 708yamaguchi** [comment]
Travis tests with indigo and kinetic fail because g++, OpenCV and cmake versions are old.
It seems difficult to pass these tests...
https://travis-ci.com/github/jsk-ros-pkg/jsk_recognition/builds/218092094

Original fisheyeStitcker's pre-requisite:
https://github.com/drNoob13/fisheyeStitcher#pre-requisite
```
* C++17-support compiler.
* CMake 3.5.1.
* OpenCV 3.4.2 (with calib3d) or more recent version of OpenCV.
```

Software versions in indigo travis tests:
```
$ g++ -v
~~
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.4)
$ cmake --version
cmake version 2.8.12.2
$ pkg-config --modversion opencv
2.4.8
```

Software versions in kinetic travis tests:
```
$ g++ -v
~~
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
$ cmake --version
cmake version 3.5.1
$ pkg-config --modversion opencv
2.4.9.1
```

Also, noetic travis tests fail because noetic tests use OpenCV 4.2.0
Error example:
```
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/include/jsk_perception/fisheye_stitcher.cpp:206:51: error: 'CV_INTER_LINEAR' was not declared in this scope

  206 |     cv::remap(src, dst, m_mls_map_x, m_mls_map_y, CV_INTER_LINEAR,

      |                                                   ^~~~~~~~~~~~~~~
```

**Comment by 708yamaguchi** [comment]
fisheye stitcher is not build and tested for indigo and kinetic, because the software (gcc, OpenCV, cmake) version is old.
```cmake
# See https://github.com/drNoob13/fisheyeStitcher#pre-requisite
if("${CMAKE_CXX_COMPILER_VERSION}" VERSION_GREATER "7.0" AND # >= 7.1
   "${OpenCV_VERSION}" VERSION_GREATER "2.9.9" AND # >= 3.0.0
   "${CMAKE_MAJOR_VERSION}" VERSION_GREATER "2") # >= 3
  jsk_add_nodelet(src/dual_fisheye_to_panorama.cpp "jsk_perception/DualFisheyeToPanorama" "dual_fisheye_to_panorama")
endif()
```

It seems that travis tests will pass if https://github.com/jsk-ros-pkg/jsk_recognition/pull/2574 is merged.
https://travis-ci.com/github/jsk-ros-pkg/jsk_recognition/builds/218208996

@k-okada 
Could you merge https://github.com/jsk-ros-pkg/jsk_recognition/pull/2574 if there is no problem?

**Comment by 708yamaguchi** [comment]
Thank you for your merging.
Travis passed!

**Pull request merged**
