### PR TITLE
travis: drop hydro

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by furushchev** [comment]
failed on some env:

```bash
+ sh -c '$CI_SOURCE_PATH/.travis_before_script_opencv3.bash'
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package ros-indigo-opencv3.
(Reading database ... 94941 files and directories currently installed.)
Preparing to unpack .../ros-indigo-opencv3_3.1.0-1trusty-20170607-101218-0800_amd64.deb ...
Unpacking ros-indigo-opencv3 (3.1.0-1trusty-20170607-101218-0800) ...
Setting up ros-indigo-opencv3 (3.1.0-1trusty-20170607-101218-0800) ...
Processing triggers for libc-bin (2.19-0ubuntu6.13) ...
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
     Performing actions: 
     Add new elements:
  image_common/image_transport,  jsk_common/image_view2,  jsk_common/jsk_data,  jsk_common/jsk_topic_tools,  opencv_apps,  vision_opencv/cv_bridge,  vision_opencv/image_geometry
Config changed, maybe you need run wstool update to update SCM entries.
Overwriting /workspace/ros/ws_jsk_recognition/src/.rosinstall
update complete.
Prepare updating http://github.com/jsk-ros-pkg/jsk_recognition (version None) to /workspace/ros/ws_jsk_recognition/src/jsk_recognition
Url https://github.com/jsk-ros-pkg/jsk_recognition does not match http://github.com/jsk-ros-pkg/jsk_recognition requested.
  (d)elete and replace, (a)bort, (i)nplace delete and replace at symlink, (s)kip: Traceback (most recent call last):
  File "/usr/bin/wstool", line 62, in <module>
    sys.exit(wstool.wstool_cli.wstool_main(sys.argv))
  File "/usr/lib/python2.7/dist-packages/wstool/wstool_cli.py", line 180, in wstool_main
    return ws_commands[command](workspace, args)
  File "/usr/lib/python2.7/dist-packages/wstool/multiproject_cli.py", line 1066, in cmd_update
    verbose=options.verbose)
  File "/usr/lib/python2.7/dist-packages/wstool/multiproject_cmd.py", line 365, in cmd_install_or_update
    robust=robust)
  File "/usr/lib/python2.7/dist-packages/wstool/config_elements.py", line 310, in prepare_install
    allow_inplace=is_link)
  File "/usr/lib/python2.7/dist-packages/wstool/ui.py", line 93, in prompt_del_abort_retry
    mode_input = self.get_input(full_prompt)
  File "/usr/lib/python2.7/dist-packages/wstool/ui.py", line 68, in get_input
    return raw_input(prompt)
EOFError: EOF when reading a line
```

maybe some scripts need to be fixed? I'm now trying just reverting `.travis`.

**Comment by furushchev** [comment]
now at least waiting for https://github.com/jsk-ros-pkg/jsk_common/pull/1564

**Comment by k-okada** [comment]
hydro is already dropped https://github.com/jsk-ros-pkg/jsk_recognition/pull/2217, i think..

**Comment by furushchev** [comment]
@k-okada Thank you! Closed.

**Pull request closed without merging**
