### PR TITLE
Update travis

### PR DESCRIPTION
**Pull request by garaemon**
update travis to check if catkin build works

### CODE REVIEW

**Comment by garaemon** [comment]
```
The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).
```

**Comment by k-okada** [comment]
Ok, I'll take care of this

2015年1月24日土曜日、Ryohei Ueda<notifications@github.com>さんは書きました:

> The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/648#issuecomment-71301511>
> .
>


-- 
--
◉ Kei Okada

**Comment by garaemon** [comment]
> Ok, I'll take care of this

separating build test into jsk_pcl_ros and jsk_perception might solve this problem...

**Comment by garaemon** [comment]
I think --no-status option should solve this issue

**Comment by garaemon** [comment]
```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```
we need -v option

**Comment by garaemon** [comment]
sigh..., -v does not resolve thus issue

**Comment by garaemon** [comment]
It's taken over by https://github.com/jsk-ros-pkg/jsk_recognition/pull/665

**Pull request closed without merging**
