### PR TITLE
Smoothing filter

### PR DESCRIPTION
**Pull request by iory**
Add smoothing filter's, gaussian filter, median filter, bilateral filter.

filter s

### CODE REVIEW

**Comment by k-okada** [comment]
nice, if we can support tutorial_code (https://github.com/opencv/opencv/tree/master/samples/cpp/tutorial_code/ImgProc)  in addition to sample (https://github.com/opencv/opencv/tree/master/samples/cpp), we can cover this in opencv_apps

**Comment by iory** [comment]
@k-okada 

> nice, if we can support tutorial_code (https://github.com/opencv/opencv/tree/master/samples/cpp/tutorial_code/ImgProc) in addition to sample (https://github.com/opencv/opencv/tree/master/samples/cpp), we can cover this in opencv_apps

this means that I should close this PR and send PR in opencv_apps?

**Comment by k-okada** [comment]
yes, if that code is one of the tutorial code. see
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1843#issuecomment-242342694

--
◉ Kei Okada

**Comment by iory** [comment]
OK

**Pull request closed without merging**
