### PR TITLE
[jsk_pcl_ros] torus should directs to origin always in TorusFinder

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
```
[jsk_recognition_msgs] CMake Error at /opt/ros/indigo/share/catkin/cmake/catkin_add_env_hooks.cmake:91 (file): 
[jsk_recognition_msgs]   file COPY cannot set permissions on 
[jsk_recognition_msgs]   "/workspace/ros/ws_jsk_recognition/devel/etc/catkin/profile.d/05.catkin_make.bash" 
[jsk_recognition_msgs] Call Stack (most recent call first): 
[jsk_recognition_msgs]   /opt/ros/indigo/share/catkin/cmake/all.cmake:198 (catkin_add_env_hooks) 
[jsk_recognition_msgs]   /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:20 (include) 
[jsk_recognition_msgs]   CMakeLists.txt:3 (find_package) 
[jsk_recognition_msgs]  
```

**Comment by garaemon** [comment]
strange, just restarting travis resolved the problem above

**Comment by k-okada** [comment]
I suspect that is a bug in catkin (catkin used both catkin_make and catkin
build, catkin_tools provide catkin build), that two different process try
to copy the file at same time, write report at
https://github.com/ros/catkin/issues/718

--
◉ Kei Okada

**Comment by garaemon** [comment]
interesting, concurrent programming is always difficult for human beings

**Pull request merged**
