### PR TITLE
[jsk_perception] Add RectArrayActualSizeFilter

### PR DESCRIPTION
**Pull request by garaemon**
Filtering array of rectangle regions based on actual size estimated from
depth image.

rect_array_actual_size_filter

### CODE REVIEW

**Comment by wkentaro** [comment]
@garaemon How do you draw the RectArray onto the Image?

**Comment by wkentaro** [comment]
Ah, you use http://jsk-recognition.readthedocs.org/en/latest/jsk_perception/nodes/rect_array_to_image_marker.html ?
Or are there easier way to view it on image_view and rviz?

**Comment by garaemon** [comment]
image_view does not support marker stuff and rviz is not good at visualizing 2D image processing.
We can make a simple program which takes an image and rect array and publish an image with drawing rectangles.

**Comment by wkentaro** [comment]
I see. 

> We can make a simple program which takes an image and rect array and publish an image with drawing rectangles.

This has not yet done, have it?

**Comment by garaemon** [comment]
> This has not yet done, have it?

Not yet done

**Comment by wkentaro** [comment]
Ok, thank you!

**Comment by wkentaro** [comment]
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1568

**Pull request merged**
