### PR TITLE
jsk_pcl_ros/package.xml: remove robot_self_filter from pcakage.xml

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by furushchev** [comment]
failed on jade. maybe posedetection_msgs is not yet released.

```bash
[checkerboard_detector] CMake Error at /opt/ros/jade/share/catkin/cmake/catkinConfig.cmake:75 (find_package): 

[checkerboard_detector]   Could not find a package configuration file provided by 

[checkerboard_detector]   "posedetection_msgs" with any of the following names: 

[checkerboard_detector]                                                         

[checkerboard_detector]     posedetection_msgsConfig.cmake                      

[checkerboard_detector]     posedetection_msgs-config.cmake                     

[checkerboard_detector]                                                         

[checkerboard_detector]   Add the installation prefix of "posedetection_msgs" to CMAKE_PREFIX_PATH or 

[checkerboard_detector]   set "posedetection_msgs_DIR" to a directory containing one of the above 

[checkerboard_detector]   files.  If "posedetection_msgs" provides a separate development package or 

[checkerboard_detector]   SDK, be sure it has been installed.                   

[checkerboard_detector] Call Stack (most recent call first):                    

[checkerboard_detector]   CMakeLists.txt:5 (find_package)    
```

**Comment by k-okada** [comment]
failed to release on jade;
```
Pre-verifying Debian dependency keys...
Running 'rosdep update'...
Could not resolve rosdep key 'ml_classifiers'
Failed to resolve ml_classifiers on ubuntu:trusty with: Error running
generator: Failed to resolve rosdep key 'ml_classifiers', aborting.
ml_classifiers is depended on by these packages: ['jsk_pcl_ros']
<== Failed
Could not resolve rosdep key 'ml_classifiers'
Failed to resolve ml_classifiers on ubuntu:utopic with: Error running
generator: Failed to resolve rosdep key 'ml_classifiers', aborting.
ml_classifiers is depended on by these packages: ['jsk_pcl_ros']
<== Failed
Could not resolve rosdep key 'ml_classifiers'
Failed to resolve ml_classifiers on ubuntu:vivid with: Error running
generator: Failed to resolve rosdep key 'ml_classifiers', aborting.
ml_classifiers is depended on by these packages: ['jsk_pcl_ros']
<== Failed
Could not resolve rosdep key 'sklearn'
Failed to resolve sklearn on ubuntu:trusty with: Error running generator:
Failed to resolve rosdep key 'sklearn', aborting.
sklearn is depended on by these packages: ['jsk_pcl_ros']
<== Failed
Could not resolve rosdep key 'sklearn'
Failed to resolve sklearn on ubuntu:utopic with: Error running generator:
Failed to resolve rosdep key 'sklearn', aborting.
sklearn is depended on by these packages: ['jsk_pcl_ros']
<== Failed
Could not resolve rosdep key 'sklearn'
Failed to resolve sklearn on ubuntu:vivid with: Error running generator:
Failed to resolve rosdep key 'sklearn', aborting.
sklearn is depended on by these packages: ['jsk_pcl_ros']
<== Failed
Some of the dependencies for packages in this repository could not be
resolved by rosdep.
You can try to address the issues which appear above and try again if you
wish.
```

--
◉ Kei Okada

**Comment by k-okada** [comment]
c.f.
https://github.com/jolting/ml_classifiers-release/issues/1
https://github.com/tork-a/jsk_3rdparty-release/blob/master/jade.ignored#L7

--
◉ Kei Okada

**Comment by garaemon** [comment]
robot_self_filter should be released.

https://github.com/PR2/robot_self_filter/releases

**Pull request closed without merging**
