### PR TITLE
[jsk_perception] support sensor_msgs/PanoramaInfo with adding a publisher to DualFisheyeToPanorama node

### PR DESCRIPTION
**Pull request by sktometometo**
I defined PanoramaInfo message for meta information of panorama images.
The message have fields below.
- header (std_msgs/Header)
- projection_model (string)
  + describing the projection model of a panorama image.
  + Currently, only "equirectangular" is used. But use of other projection models is possible. e.g. "mercator" 
- theta_min, theta_max, phi_min, phi_max (float64)
  + describing the region of shown image in [spherical coordinate system](https://en.wikipedia.org/wiki/Spherical_coordinate_system)

And I added a publisher of PanoramaInfo.msg to DualFisheyeToPanorama for example usage.

### CODE REVIEW

**Comment by k-okada** [comment]
please cleate PR to https://github.com/ros/common_msgs/pulls
--
◉ Kei Okada



2021年3月12日(金) 8:51 Koki Shinjo ***@***.***>:

**Comment by sktometometo** [comment]
PanoramaInfo.msg is defined in https://github.com/ros/common_msgs/pull/171.

Change panorama info publisher of DualFisheyeToPanorama to use sensor_msgs/Panoramainfo

**Comment by sktometometo** [comment]
Example usage of PanoramaInfo will be in https://github.com/jsk-ros-pkg/jsk_recognition/pull/2581

**Review by k-okada — APPROVED** [review]
LGTM

**Comment by k-okada** [comment]
failing with
```
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/dual_fisheye_to_panorama.cpp:36:
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/include/jsk_perception/dual_fisheye_to_panorama.h:43:10: fatal error: sensor_msgs/PanoramaInfo.h: No such file or directory
   43 | #include <sensor_msgs/PanoramaInfo.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/jsk_perception.dir/build.make:219: CMakeFiles/jsk_perception.dir/src/dual_fisheye_to_panorama.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Pull request merged**
