### PR TITLE
Do not compile octomap_server and jsk_3rdparty on jade

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
Need next sync of shadow-fixed

**Comment by garaemon** [comment]
because of https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/51

**Comment by k-okada** [comment]
do we still need this?

**Comment by wkentaro** [comment]
It seems that ros-jade-octomap-server and ros-jade-octomap-mapping is released on apt.
So this commit is valid, but need to be rebased with origin/master.

**Comment by k-okada** [comment]
@garaemon need rebase origin/master

**Pull request closed without merging**
