### PR TITLE
Use 1 queue size for pub/sub not synchronization

### PR DESCRIPTION
**Pull request by wkentaro**
## Why?

This causes low rate of topic processing, and it can be 1 in most case.

### CODE REVIEW

**Comment by k-okada** [comment]
sorry please resolve conflict

--
◉ Kei Okada


2017-06-03 4:52 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
Could you please merge this? @k-okada

**Comment by k-okada** [comment]
how about set max_callback_queue_size_, max_synchronizer_queue_size_, or
max_queue_size_ and max_callback_queue_size if you want to keep
backward compatibility
--
◉ Kei Okada



2017-06-08 17:41 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
Thanks for the comment. I updated the change.

**Comment by wkentaro** [comment]
Looks good?

**Comment by wkentaro** [comment]
Could you please merge this?

**Comment by k-okada** [comment]
please add link to launch file who uses this new feature.

**Comment by wkentaro** [comment]
See #2111

**Pull request merged**
