### PR TITLE
Node to convert Marker to MarkerArray

### PR DESCRIPTION
**Pull request by wkentaro**
## Why?

I use marker_array to evaluate the 3D segmentation algorithm, and this is a util to convert marker to marker_array.

### CODE REVIEW

**Comment by wkentaro** [comment]
@iory Could you please review this?

**Comment by wkentaro** [comment]
@iory Could you please ?

**Comment by wkentaro** [comment]
@iory 😭

**Comment by iory** [comment]
Oh, sorry. I had overlooked this issue.

**Comment by iory** [comment]
LGTM!

**Comment by wkentaro** [comment]
Thanks. @k-okada Could u please merge this?

**Comment by k-okada** [comment]
which node publish marker ?

**Comment by wkentaro** [comment]
OctomapServer: https://github.com/OctoMap/octomap_mapping/blob/jade-devel/octomap_server/src/OctomapServer.cpp#L169

**Comment by k-okada** [comment]
it there possibility to publish both marker and marker array?

**Comment by wkentaro** [comment]
> it there possibility to publish both marker and marker array?

+1

**Pull request closed without merging**
