### PR TITLE
[jsk_perception] Add sample/test for image_cluster_indices_decomposer.py

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge this if it looks good!

**Comment by k-okada** [comment]
Please rebase origin/master..

**Comment by wkentaro** [comment]
Rebased.

**Comment by wkentaro** [comment]
Please merge this if it looks good.

**Comment by wkentaro** [comment]
Please merge.

**Pull request merged**
