### PR TITLE
Organize CMakeLists.txt of jsk_perception

### PR DESCRIPTION
**Pull request by wkentaro**
- Refactor: jsk_perception_add_rostest -> _add_rostest
- Refactor: jsk_perception -> ${PROJECT_NAME}
- Refactor: jsk_perception_nodelet -> _add_nodelet
- Sort service files
- Fix if block syntax
- Fix missing CATKIN_DEPENDS of posedetection_msgs
- Fix node executables installation by introducing macro
- Organize cmake setup order

### CODE REVIEW

**Comment by k-okada** [comment]
> Refactor: jsk_perception_add_rostest -> _add_rostest
> Refactor: jsk_perception_nodelet -> _add_nodelet

what is the benefit of this?

**Comment by wkentaro** [comment]
> what is the benefit of this?

The benefit is small but

1. The macro will be written without `jsk_perception` as below and able to be copied to other package's CMakeLists.txt.
2. The name of macro become short and easy to read. (`jsk_perception_` was redundant meanglessly)
```
macro(_add_nodelet _nodelet_cpp _nodelet_class _single_nodelet_exec_name)
  if(NOT EXISTS "${PROJECT_SOURCE_DIR}/test/${_single_nodelet_exec_name}.test")
    list(APPEND ${PROJECT_NAME}_nodes_without_test ${_nodelet_cpp})
  endif()
  jsk_nodelet(${_nodelet_cpp} ${_nodelet_class} ${_single_nodelet_exec_name}
  ${PROJECT_NAME}_nodelet_sources ${PROJECT_NAME}_nodelet_executables)
endmacro()
```

**Comment by wkentaro** [comment]
Any comments, please?

**Comment by k-okada** [comment]
If you wan to reuse this macro, how about put that macro to https://github.com/jsk-ros-pkg/jsk_common/blob/7645de37183503e7c0443daa030772dc603afbde/jsk_topic_tools/cmake/nodelet.cmake#L6 ?

**Comment by wkentaro** [comment]
> If you wan to reuse this macro, how about put that macro to https://github.com/jsk-ros-pkg/jsk_common/blob/7645de37183503e7c0443daa030772dc603afbde/jsk_topic_tools/cmake/nodelet.cmake#L6 ?

I don't think this macro is not so reusable, because it depends on the path of `test` dir and name of `.test` files.
But `_add_nodelet` macro is easier to copy and paste.
Also the shorter macro name is better, and `_` prefix can represent private macro that cannot be reusable by other packages.

**Comment by wkentaro** [comment]
If you think this change is not necessary at this time, I can revert it.

**Comment by k-okada** [comment]
I prefer jsk_add_nodelet rather than _add_nodelet
Because _ prefix is considered as private and local variable, but I think cmake does not guarantee that. Other contributors are great, I'll merge if you change macro name

**Comment by wkentaro** [comment]
Ok, fixed.

**Comment by k-okada** [comment]
something wrong on hydro
```
[jsk_pcl_ros_utils] Linking CXX executable /workspace/ros/ws_jsk_recognition/devel/lib/jsk_pcl_ros_utils/colorize_distance_from_plane
[jsk_perception] CMake Warning (dev) at CMakeLists.txt:346 (message):
[jsk_perception]   Node/Nodelets without rostest:
[jsk_perception]   node_scripts/matchtemplate.py;node_scripts/unwrap_histogram_with_range_array.py;node_scripts/random_forest_server.py;node_scripts/image_time_diff.py;node_scripts/non_maximum_suppression.py;node_scripts/fast_rcnn.py;node_scripts/solidity_rag_merge.py;node_scripts/fisheye_ray.py;node_scripts/extract_images_sync;node_scripts/image_saver_sync;node_scripts/binpack_rect_array.py;node_scripts/publish_header;src/polygon_array_color_likelihood.cpp;src/polygon_array_color_histogram.cpp;src/edge_detector.cpp;src/sparse_image_encoder.cpp;src/sparse_image_decoder.cpp;src/background_substraction_nodelet.cpp;src/hough_circles.cpp;src/fisheye_to_panorama.cpp;src/grabcut_nodelet.cpp;src/rgb_decomposer.cpp;src/hsv_decomposer.cpp;src/lab_decomposer.cpp;src/ycc_decomposer.cpp;src/contour_finder.cpp;src/snake_segmentation.cpp;src/grid_label.cpp;src/color_histogram_label_match.cpp;src/unapply_mask_image.cpp;src/single_channel_histogram.cpp;src/morphological_operator.cpp;src/morphological_operator.cpp;src/morphological_operator.cpp;src/morphological_operator.cpp;src/morphological_operator.cpp;src/morphological_operator.cpp;src/morphological_operator.cpp;src/rect_to_mask_image.cpp;src/mask_image_to_roi.cpp;src/mask_image_to_rect.cpp;src/roi_to_rect.cpp;src/roi_to_mask_image.cpp;src/polygon_to_mask_image.cpp;src/polygon_array_to_label_image.cpp;src/rect_to_roi.cpp;src/project_image_point.cpp;src/sliding_window_object_detector.cpp;src/gaussian_blur.cpp;src/tabletop_color_difference_likelihood.cpp;src/saliency_map_generator_node.cpp;src/skeletonization_nodelet.cpp
[jsk_perception] This warning is for project developers.  Use -Wno-dev to suppress it.
[jsk_perception] 
[jsk_perception] CMake Error at CMakeLists.txt:401 (jsk_add_rostest):
[jsk_perception]   Unknown CMake command "jsk_add_rostest".
[jsk_perception] 
[jsk_perception] 
[jsk_perception] -- Configuring incomplete, errors occurred!
[jsk_perception] <== '/workspace/ros/ws_jsk_recognition/build/jsk_perception/build_env.sh /usr/bin/cmake /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception -DCATKIN_DEVEL_PREFIX=/workspace/ros/ws_jsk_recognition/devel -DCMAKE_INSTALL_PREFIX=/workspace/ros/ws_jsk_recognition/install' failed with return code '1'
```

**Comment by k-okada** [comment]
thx

**Comment by k-okada** [comment]
1) why jsk_pcl_ros_utils do not depends on jsk_data and why that is passed on travis?
2) please consider using cache or do not download heavy data during compile time, or show warning that you're downloading XX data and that takes XX time.... a lot of people thinks they need faster CPU to speed up compile.

http://build.ros.org/job/Ibin_uT64__jsk_pcl_ros_utils__ubuntu_trusty_amd64__binary/75/console
```
10:48:32 Traceback (most recent call last):
10:48:32   File "../scripts/install_sample_data.py", line 3, in <module>
10:48:32     from jsk_data import download_data
10:48:32 ImportError: No module named jsk_data
10:48:32 make[4]: *** [CMakeFiles/install_sample_data] Error 1
10:48:32 make[4]: Leaving directory `/tmp/binarydeb/ros-indigo-jsk-pcl-ros-utils-1.0.0/obj-x86_64-linux-gnu'
10:48:32 make[3]: *** [CMakeFiles/install_sample_data.dir/all] Error 2
10:48:32 make[3]: Leaving directory `/tmp/binarydeb/ros-indigo-jsk-pcl-ros-utils-1.0.0/obj-x86_64-linux-gnu'
10:48:32 make[2]: *** [all] Error 2
10:48:32 make[2]: Leaving directory `/tmp/binarydeb/ros-indigo-jsk-pcl-ros-utils-1.0.0/obj-x86_64-linux-gnu'
10:48:32 dh_auto_build: make -j1 returned exit code 2
10:48:32 make[1]: *** [override_dh_auto_build] Error 2
10:48:32 make[1]: Leaving directory `/tmp/binarydeb/ros-indigo-jsk-pcl-ros-utils-1.0.0'
10:48:32 make: *** [build] Error 2
10:48:32 dpkg-buildpackage: error: debian/rules build gave error exit status 2
10:48:32 E: Building failed
10:48:32 Traceback (most recent call last):
10:48:32   File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 133, in build_binarydeb
10:48:32     subprocess.check_call(cmd, cwd=source_dir)
10:48:32   File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
10:48:32     raise CalledProcessError(retcode, cmd)
10:48:32 subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-indigo-jsk-pcl-ros-utils']' returned non-zero exit status 1
10:48:32 # END SUBSECTION
```

**Comment by wkentaro** [comment]
@k-okada is your question related to this PR? If not, please consider of opening new issue.


> why jsk_pcl_ros_utils do not depends on jsk_data and why that is passed on travis?

Maybe it is a bug, and the reason why the test pass is jsk_perception depends on jsk_data and rosdep installs it.

> please consider using cache or do not download heavy data during compile time

We are using cache already, and the installation at compile time is only for sample/trained data. (we don't install test data)

>  show warning that you're downloading XX data

I think it is  already shown.

> hat takes XX time...

Some times it is hard to estimate the end time, because files on google drive does not have size info. in the header

**Comment by k-okada** [comment]
Thanks, 

I found this PR because blame told me who added `add_custom_target(install_sample_data ALL COMMAND ${PROJECT_SOURCE_DIR}/scripts/install_sample_data.py)`

screenshot from 2016-12-13 16 19 46

**Comment by wkentaro** [comment]
Hmm, the limitation of the git blame on GitHub is that it does not support to backward the history... (In actual, the add_custom_target... is not added with this PR, and this PR just refactored the file.)

**Comment by k-okada** [comment]
yes, i know....

**Pull request merged**
