### PR TITLE
Add mask image indices concatator

### PR DESCRIPTION
**Pull request by YuOhara**
node to segment cloud with 

* user-selected mask Image
* some other clustring result(example, superVoxelSegmentation).

### CODE REVIEW

**Comment by garaemon** [comment]
> mask_image_cluster_indices_concatenator_nodelet

naming ins not good. how about make_image_cluster_filter?

**Comment by YuOhara** [comment]
mask\_image\_cluster\_filter seems better because the diff from mask\_image\_filter is using(or not using) cluster results. Therefore, it' more user-friendly.
Yes, I will rename nodes tomorrow.

**Comment by garaemon** [comment]
merge origin/master

**Comment by garaemon** [comment]
```
[jsk_pcl_ros] CMake Error at CMakeLists.txt:296 (add_library): 
[jsk_pcl_ros]   Cannot find source file: 
[jsk_pcl_ros]  
[jsk_pcl_ros]     src/mask_image_cluster_filter_nodelet.cpp 
[jsk_pcl_ros]  
[jsk_pcl_ros]   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp 
[jsk_pcl_ros]   .hxx .in .txx 
```

**Comment by YuOhara** [comment]
I forgotten commit, thanks

**Pull request merged**
