### PR TITLE
Update sample image in docs for BoundingRectMaskImage

### PR DESCRIPTION
**Pull request by wkentaro**
tag: documentation

image

### CODE REVIEW

**Comment by k-okada** [comment]
How do you segment the image, depth filter?

2016年5月31日火曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> Assigned #1715 <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1715>
> to @k-okada <https://github.com/k-okada>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1715#event-676602423>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3Bv-bsH81trVebcgFzHHH07-guEaks5qG99vgaJpZM4IqPMt>
> .
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
Yes, it is segmented by localizing point cloud around the robot's hand.

2016年5月31日火曜日、Kei Okada<notifications@github.com>さんは書きました:

> How do you segment the image, depth filter?
>
> 2016年5月31日火曜日、Kentaro Wada<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
> > Assigned #1715 <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1715
> >
> > to @k-okada <https://github.com/k-okada>.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_recognition/pull/1715#event-676602423>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAeG3Bv-bsH81trVebcgFzHHH07-guEaks5qG99vgaJpZM4IqPMt
> >
> > .
> >
>
>
> --
> --
> ◉ Kei Okada
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1715#issuecomment-222701208>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEHFk8RnHnN_3wfrQt1XIgaGvA1wG4GXks5qHEILgaJpZM4IqPMt>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by k-okada** [comment]
If so cloud you move the robot hand more close to the camera? It took a few
seconds to understand the scene, may be because of
1 the camera is rotated
2 the target is small compare to the entire image

2016年5月31日火曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> Yes, it is segmented by localizing point cloud around the robot's hand.
>
> 2016年5月31日火曜日、Kei Okada<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
>
> > How do you segment the image, depth filter?
> >
> > 2016年5月31日火曜日、Kentaro Wada<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>さんは書きました:
> >
> > > Assigned #1715 <
> https://github.com/jsk-ros-pkg/jsk_recognition/pull/1715
> > >
> > > to @k-okada <https://github.com/k-okada>.
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <
> > https://github.com/jsk-ros-pkg/jsk_recognition/pull/1715#event-676602423
> >,
> > > or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/AAeG3Bv-bsH81trVebcgFzHHH07-guEaks5qG99vgaJpZM4IqPMt
> > >
> > > .
> > >
> >
> >
> > --
> > --
> > ◉ Kei Okada
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_recognition/pull/1715#issuecomment-222701208
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AEHFk8RnHnN_3wfrQt1XIgaGvA1wG4GXks5qHEILgaJpZM4IqPMt
> >
> > .
> >
>
>
> --
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1715#issuecomment-222701991>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3KRMbexgRkEKGjhgDv9lxFMf9exjks5qHEK3gaJpZM4IqPMt>
> .
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
Ok, I created an sample image it is easer to understand.
sample_bounding_rect_mask_image

**Comment by k-okada** [comment]
very nice.

**Pull request merged**
