### PR TITLE
[jsk_pcl_ros_utils] Add nodelet for computing & comparing color histogram

### PR DESCRIPTION
**Pull request by furushchev**
- [x] separate logic to compute color histogram from nodelet internal definition
- [x] add nodelet for computing color histogram for each point indices
- [x] add nodelet for filtering indices using similarity of color histogram
- [x] add image for doc
- [x] update docs
- [x] add sample launch file
- [x] add test codes

related https://github.com/jsk-ros-pkg/jsk_recognition/pull/2094

Below is image that iemon green tea is filtered.

color_histogram

### CODE REVIEW

**Comment by furushchev** [comment]
Added node for visualization

- Hue only
histogram_hue

- Hue and saturation
histogram_hue_sat

**Comment by furushchev** [comment]
Rewrote comparison methods from scratch and now it seems to work well.
Original comparison algorithms for 2 vectors might be wrong in both euslisp....

detect_cans

**Comment by mukuact** [comment]
mizuna環境，手元PCどちらでも，buildが出来ませんでした．
```
roscd jsk_pcl_ros
git fetch furushchev 
git checkout color-histogram
catkin bt -c -DCMAKE_BULID_TYPE=RelWithDebInfo -v
```
その時のlogです
[log_jsk_pcl_ros.txt](https://github.com/jsk-ros-pkg/jsk_recognition/files/1070843/log_jsk_pcl_ros.txt)

**Comment by furushchev** [comment]
@mukuact You will need https://github.com/jsk-ros-pkg/jsk_common/pull/1523

**Comment by mukuact** [comment]
I switched forward jsk_common to master branch and succeed to build this package! 
Thanks!!

**Comment by k-okada** [comment]
released newer version of jsk_common,
https://github.com/ros/rosdistro/pull/15227

--
◉ Kei Okada


2017-06-14 9:21 GMT+09:00 muku takeda <notifications@github.com>:

**Comment by k-okada** [comment]
hydro : 
```
[jsk_pcl_ros_utils] In file included from /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/color_histogram_filter.h:48:0, 
[jsk_pcl_ros_utils]                  from /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_filter_nodelet.cpp:41: 
[jsk_pcl_ros_utils] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_recognition_utils/include/jsk_recognition_utils/pcl/color_histogram.h: In function 'bool jsk_recognition_utils::compareHistogram(const std::vector<float>&, const std::vector<float>&, jsk_recognition_utils::ComparePolicy, double&)': 
[jsk_pcl_ros_utils] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_recognition_utils/include/jsk_recognition_utils/pcl/color_histogram.h:212:28: error: 'DBL_EPSILON' was not declared in this scope 
[jsk_pcl_ros_utils] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_recognition_utils/include/jsk_recognition_utils/pcl/color_histogram.h:223:38: error: 'DBL_EPSILON' was not declared in this scope 
[jsk_pcl_ros_utils] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_recognition_utils/include/jsk_recognition_utils/pcl/color_histogram.h:235:28: error: 'DBL_EPSILON' was not declared in this scope 
[jsk_pcl_ros_utils] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_recognition_utils/include/jsk_recognition_utils/pcl/color_histogram.h:240:29: error: 'DBL_EPSILON' was not declared in this scope 
[jsk_pcl_ros_utils] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_recognition_utils/include/jsk_recognition_utils/pcl/color_histogram.h:241:29: error: 'DBL_EPSILON' was not declared in this scope 
[jsk_pcl_ros_utils] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_filter_nodelet.cpp: In member function 'virtual void jsk_pcl_ros_utils::ColorHistogramFilter::configCallback(jsk_pcl_ros_utils::ColorHistogramFilter::Config&, uint32_t)': 
[jsk_pcl_ros_utils] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_filter_nodelet.cpp:71:24: error: 'isSubscribed' was not declared in this scope 
[jsk_pcl_ros_utils] make[2]: *** [CMakeFiles/jsk_pcl_ros_utils.dir/src/color_histogram_filter_nodelet.cpp.o] Error 1 
[jsk_pcl_ros_utils] make[1]: *** [CMakeFiles/jsk_pcl_ros_utils.dir/all] Error 2 
[jsk_pcl_ros_utils] make: *** [all] Error 2 
```
kinetic
```

cd /workspace/ros/ws_jsk_recognition/build/jsk_perception; catkin build --get-env jsk_perception | catkin env -si  /usr/bin/cmake /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/workspace/ros/ws_jsk_recognition/devel/.private/jsk_perception -DCMAKE_INSTALL_PREFIX=/workspace/ros/ws_jsk_recognition/install; cd -
Errors     << jsk_pcl_ros_utils:make /workspace/ros/ws_jsk_recognition/logs/jsk_pcl_ros_utils/build.make.000.log
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_classifier_nodelet.cpp: In member function 'virtual void jsk_pcl_ros_utils::ColorHistogramClassifier::configCallback(jsk_pcl_ros_utils::ColorHistogramClassifier::Config&, uint32_t)':
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_classifier_nodelet.cpp:106:24: error: 'isSubscribed' was not declared in this scope
       if (isSubscribed()) {
                        ^
make[2]: *** [CMakeFiles/jsk_pcl_ros_utils.dir/src/color_histogram_classifier_nodelet.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_filter_nodelet.cpp: In member function 'virtual void jsk_pcl_ros_utils::ColorHistogramFilter::configCallback(jsk_pcl_ros_utils::ColorHistogramFilter::Config&, uint32_t)':
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_filter_nodelet.cpp:71:24: error: 'isSubscribed' was not declared in this scope
       if (isSubscribed()) {
                        ^
make[2]: *** [CMakeFiles/jsk_pcl_ros_utils.dir/src/color_histogram_filter_nodelet.cpp.o] Error 1
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_nodelet.cpp: In member function 'virtual void jsk_pcl_ros_utils::ColorHistogram::configCallback(jsk_pcl_ros_utils::ColorHistogram::Config&, uint32_t)':
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_nodelet.cpp:66:24: error: 'isSubscribed' was not declared in this scope
       if (isSubscribed()) {
                        ^
make[2]: *** [CMakeFiles/jsk_pcl_ros_utils.dir/src/color_histogram_nodelet.cpp.o] Error 1
make[1]: *** [CMakeFiles/jsk_pcl_ros_utils.dir/all] Error 2
make: *** [all] Error 2
cd /workspace/ros/ws_jsk_recognition/build/jsk_pcl_ros_utils; catkin build --get-env jsk_pcl_ros_utils | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
Failed     << jsk_pcl_ros_utils:make                 [ Exited with code 2 ]
Failed    <<< jsk_pcl_ros_utils                      [ 3 minutes and 13.1 seconds ]
Abandoned <<< jsk_pcl_ros                            [ Unrelated job failed ]
```
release repo
```

cd /workspace/ros/ws_jsk_recognition/build/jsk_perception; catkin build --get-env jsk_perception | catkin env -si  /usr/bin/cmake /workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/workspace/ros/ws_jsk_recognition/devel/.private/jsk_perception -DCMAKE_INSTALL_PREFIX=/workspace/ros/ws_jsk_recognition/install; cd -
Errors     << jsk_pcl_ros_utils:make /workspace/ros/ws_jsk_recognition/logs/jsk_pcl_ros_utils/build.make.000.log
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_classifier_nodelet.cpp: In member function 'virtual void jsk_pcl_ros_utils::ColorHistogramClassifier::configCallback(jsk_pcl_ros_utils::ColorHistogramClassifier::Config&, uint32_t)':
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_classifier_nodelet.cpp:106:24: error: 'isSubscribed' was not declared in this scope
       if (isSubscribed()) {
                        ^
make[2]: *** [CMakeFiles/jsk_pcl_ros_utils.dir/src/color_histogram_classifier_nodelet.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_filter_nodelet.cpp: In member function 'virtual void jsk_pcl_ros_utils::ColorHistogramFilter::configCallback(jsk_pcl_ros_utils::ColorHistogramFilter::Config&, uint32_t)':
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_filter_nodelet.cpp:71:24: error: 'isSubscribed' was not declared in this scope
       if (isSubscribed()) {
                        ^
make[2]: *** [CMakeFiles/jsk_pcl_ros_utils.dir/src/color_histogram_filter_nodelet.cpp.o] Error 1
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_nodelet.cpp: In member function 'virtual void jsk_pcl_ros_utils::ColorHistogram::configCallback(jsk_pcl_ros_utils::ColorHistogram::Config&, uint32_t)':
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros_utils/src/color_histogram_nodelet.cpp:66:24: error: 'isSubscribed' was not declared in this scope
       if (isSubscribed()) {
                        ^
make[2]: *** [CMakeFiles/jsk_pcl_ros_utils.dir/src/color_histogram_nodelet.cpp.o] Error 1
make[1]: *** [CMakeFiles/jsk_pcl_ros_utils.dir/all] Error 2
make: *** [all] Error 2
cd /workspace/ros/ws_jsk_recognition/build/jsk_pcl_ros_utils; catkin build --get-env jsk_pcl_ros_utils | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
Failed     << jsk_pcl_ros_utils:make                 [ Exited with code 2 ]
Failed    <<< jsk_pcl_ros_utils                      [ 1 minute and 24.5 seconds ]
Abandoned <<< jsk_pcl_ros                            [ Unrelated job failed ]
```

**Comment by furushchev** [comment]
@k-okada So, I finally moved all nodelets proposed in this PR into `jsk_pcl_ros`.
FYI, I encountered a bag of PCL 1.7.1 and added fixed version of the header file and selective include along with PCL version.

```diff
+#include <pcl/pcl_config.h>
 +#if PCL_VERSION_COMPARE (<, 1, 7, 2)
 +#include <jsk_pcl_ros/pcl/point_types_conversion.h>
 +#else
 +#include <pcl/point_types_conversion.h>
 +#endif
```

**Comment by furushchev** [comment]
@k-okada Please review and merge if there is no problem

**Comment by furushchev** [comment]
@k-okada Any other advices with this PR?

**Comment by k-okada** [comment]
can you create doc t how to use this node? it seems we have doc for each node https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/doc/jsk_pcl_ros/nodes/color_histogram_classifier.md, and we 'd like to know

1. how to learn histogram
2. how to start program with learnt histogram
3. how to visualize result

**Comment by furushchev** [comment]
@k-okada Thanks for merging! OK, I will create a tutorial as an individual page in docs. :+1:

**Pull request merged**
