### PR TITLE
[jsk_perception] Recognize object with VGG16 net

### PR DESCRIPTION
**Pull request by wkentaro**
Object recognition with [Bag of Features](http://jsk-docs.readthedocs.io/en/latest/jsk_recognition/doc/jsk_perception/bof_object_recognition.html) is around **52%**. (25 class)
I trained VGG16 net for object recognition for 26 class (25 + background) with **95%**.

See https://github.com/wkentaro/vgg16#amazon-picking-challenge-2015 for more detail.

### CODE REVIEW

**Comment by wkentaro** [comment]
image

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
need rebase

**Comment by wkentaro** [comment]
Please merge this.

**Pull request merged**
