### PR TITLE
[checker_board_detector] check if image already rectifierd

### PR DESCRIPTION
**Pull request by YuOhara**
This PR is to prevent rectified image been rectified again.
Check if the image already rectified or not by topic having "image_rect" in its name.

### CODE REVIEW

**Comment by k-okada** [comment]
i think we should not depend on topic name, how about
https://github.com/ros-perception/image_pipeline/blob/indigo/image_proc/src/nodelets/rectify.cpp#L117-L122

**Comment by YuOhara** [comment]
> i think we should not depend on topic name, how about

Yes, i think so.
But there seems no info about if image is rectified or not.
Because image_raw and image_rect uses the same camera_info

```
rosmsg show sensor_msgs/Image 
std_msgs/Header header
  uint32 seq
  time stamp
  string frame_id
uint32 height
uint32 width
string encoding
uint8 is_bigendian
uint32 step
uint8[] data
```

Also, I can't understand why
https://github.com/ros-perception/image_pipeline/blob/indigo/image_proc/src/nodelets/rectify.cpp#L117-L122
needed.

**Comment by k-okada** [comment]
> https://github.com/ros-perception/image_pipeline/blob/indigo/image_proc/src/nodelets/rectify.cpp#L117-L122

I see, that's checking if camera is calibrated or not, and that's different from rectified or not.

**Comment by YuOhara** [comment]
Many users use relay tools (like that in jsk_topic_tools) that changes topic names, so this pr seems to be confusing.

**Pull request closed without merging**
