### PR TITLE
[imagesift] Make imagesift as nodelet

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by wkentaro** [comment]
**DEPENDS** https://github.com/jsk-ros-pkg/jsk_common/pull/961

**Comment by k-okada** [comment]
DO NOT MERGE, until jsk-ros-pkg/jsk_common#961 MERGED

**Comment by garaemon** [comment]
great

**Comment by wkentaro** [comment]
Should we wait for the release of `jsk_topic_tools` after DRC?
@k-okada

**Comment by garaemon** [comment]
Do not need to wait for that. we dont use deb packages

2015年5月31日日曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> Should we wait for the release of jsk_topic_tools after DRC?
> @k-okada <https://github.com/k-okada>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/965#issuecomment-107271159>
> .
>


-- 
✉︎ from iPhone

**Comment by k-okada** [comment]
We need to wait for new deb of jsk_common to pass this travis test, and we
found drill_sift.launch in jsk_demos.
So if this PR is not important for DRC team, I think we can wait after DRC.
If this helps your team, we can merge this ignoring travis test.

--
◉ Kei Okada

**Comment by garaemon** [comment]
It's not important for us, thanks

2015年5月31日日曜日、Kei Okada<notifications@github.com>さんは書きました:

> We need to wait for new deb of jsk_common to pass this travis test, and we
> found drill_sift.launch in jsk_demos.
> So if this PR is not important for DRC team, I think we can wait after DRC.
> If this helps your team, we can merge this ignoring travis test.
>
> --
> ◉ Kei Okada
>
>
> On Mon, Jun 1, 2015 at 9:55 AM, Ryohei Ueda <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Do not need to wait for that. we dont use deb packages
> >
> > 2015年5月31日日曜日、Kentaro Wada<notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>さんは書きました:
> >
> > > Should we wait for the release of jsk_topic_tools after DRC?
> > > @k-okada <https://github.com/k-okada>
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/jsk-ros-pkg/jsk_recognition/pull/965#issuecomment-107271159
> > >
> > > .
> > >
> >
> >
> > --
> > ✉︎ from iPhone
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_recognition/pull/965#issuecomment-107271234
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/965#issuecomment-107274843>
> .
>


-- 
✉︎ from iPhone

**Comment by garaemon** [comment]
new version of jsk_common has just been released

**Comment by k-okada** [comment]
this has same error as we had in https://github.com/jsk-ros-pkg/jsk_recognition/pull/972#issuecomment-112277000

**Comment by wkentaro** [comment]
In my environment, I don't have below warnings but in travis it does.
```
+ wstool info -t src
WARNING [vcstools] Command failed: 'git status -s  -uno'
 run at: '/workspace/ros/ws_jsk_recognition/src/jsk_recognition'
 errcode: 128:
fatal: Not a git repository: /var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_recognition-hydro-deb-true-true-jsk_pcl_ros/workspace/jenkins-trusty-travis-jsk-ros-pkg-jsk_recognition-hydro-deb-true-true-jsk_pcl_ros-649/jsk-ros-pkg/jsk_recognition/.git/modules/.travis
[/vcstools]
WARNING [vcstools] Command failed: 'git submodule foreach --recursive git status -s -uno'
 run at: '/workspace/ros/ws_jsk_recognition/src/jsk_recognition'
 errcode: 1:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
fatal: Not a git repository: /var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_recognition-hydro-deb-true-true-jsk_pcl_ros/workspace/jenkins-trusty-travis-jsk-ros-pkg-jsk_recognition-hydro-deb-true-true-jsk_pcl_ros-649/jsk-ros-pkg/jsk_recognition/.git/modules/.travis
Stopping at '.travis'; script returned non-zero status.
[/vcstools]
```

And I think this is not caused by not this PR's changes.

**Comment by k-okada** [comment]
you're correnct `-uno` is because old git version on travis environment, but you still have following error
```
[imagesift] /opt/ros/hydro/include/nodelet/nodelet.h: In member function 'virtual void imagesift::SiftNode::onInit()': 
[imagesift] /opt/ros/hydro/include/nodelet/nodelet.h:147:17: error: 'nodelet::NodeHandlePtr nodelet::Nodelet::nh_' is private 
[imagesift] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/imagesift/src/imagesift.cpp:52:56: error: within this context 
[imagesift] /opt/ros/hydro/include/nodelet/nodelet.h:147:17: error: 'nodelet::NodeHandlePtr nodelet::Nodelet::nh_' is private 
[imagesift] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/imagesift/src/imagesift.cpp:56:66: error: within this context 
[imagesift] /opt/ros/hydro/include/nodelet/nodelet.h:147:17: error: 'nodelet::NodeHandlePtr nodelet::Nodelet::nh_' is private 
[imagesift] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/imagesift/src/imagesift.cpp:57:67: error: within this context 
[imagesift] /opt/ros/hydro/include/nodelet/nodelet.h:147:17: error: 'nodelet::NodeHandlePtr nodelet::Nodelet::nh_' is private 
[imagesift] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/imagesift/src/imagesift.cpp:58:22: error: within this context 
[imagesift] /opt/ros/hydro/include/nodelet/nodelet.h: In member function 'virtual void imagesift::SiftNode::subscribe()': 
[imagesift] /opt/ros/hydro/include/nodelet/nodelet.h:147:17: error: 'nodelet::NodeHandlePtr nodelet::Nodelet::nh_' is private 
[imagesift] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/imagesift/src/imagesift.cpp:69:42: error: within this context 
[imagesift] /opt/ros/hydro/include/nodelet/nodelet.h:147:17: error: 'nodelet::NodeHandlePtr nodelet::Nodelet::nh_' is private 
[imagesift] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/imagesift/src/imagesift.cpp:70:33: error: within this context 
[imagesift] /opt/ros/hydro/include/nodelet/nodelet.h:147:17: error: 'nodelet::NodeHandlePtr nodelet::Nodelet::nh_' is private 
[imagesift] /workspace/ros/ws_jsk_recognition/src/jsk_recognition/imagesift/src/imagesift.cpp:75:20: error: within this context 
[imagesift] make[2]: *** [CMakeFiles/imagesift.dir/src/imagesift.cpp.o] Error 1 
[imagesift] make[1]: *** [CMakeFiles/imagesift.dir/all] Error 2 
```

**Comment by wkentaro** [comment]
As I said, this PR depends on a change in `jsk_topic_tools` .
https://github.com/jsk-ros-pkg/jsk_common/pull/961

So, please wait for `jsk_topic_tools` to be released.
I think the version should be `2.0.0-0`.
https://github.com/ros/rosdistro/pull/8720

**Comment by k-okada** [comment]
Ok, now I understand.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
I think the test is passed, after the relase of `jsk_topic_tools`.
Please merge if this PR is ok for you.

**Pull request merged**
