### PR TITLE
Save point cloud data as pcd format through ROS service.

### PR DESCRIPTION
**Pull request by YUKINA-3252**
This PR is about PointCloudToPCD.

In this PR, the point cloud data can be changed to be saved in pcd format as ROS service. 

The minimum value of duration set in the configuration file was 0.0 before the change, but it is changed to -1.0 in this PR. 
If the duration is greater than 0.0, the pcd data is stored continuously, and if the duration is less than 0.0, service could be used.

### CODE REVIEW

**Comment by tkmtnt7000** [comment]
Could you update the document of `PointCloudToPCD` about `srv_save_pcd_server_` ?
https://jsk-docs.readthedocs.io/projects/jsk_recognition/en/latest/jsk_pcl_ros_utils/nodes/pointcloud_to_pcd.html

**Comment by YUKINA-3252** [comment]
Thank you for your notification. I have updated the document of this PR part.

**Comment by mqcmd196** [comment]
@YUKINA-3252 
I am slightly concerned about allowing the duration to be set to a negative value. I think the duration should always be zero or positive in its original sense. 

If you want to capture the PCD with rosservice, how about these solutions?
- Add `~always_save` parameter to avoid always saving. (This node always saves pointcloud as pcd and you wanted to avoid it, right?)
- Add `filepath` field to service request and save pcd manually

**Comment by nakane11** [comment]
I left some comments.

1.
When I run `sample_pointcloud_to_pcd.launch` and call `save_pcd` service, the following error occurred and the node died at wait_for_message in `savePCD()`.
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
By putting `return true;` to the end of service callback, the error disappeared.

2.

> If the duration is less than 0.0, service could be used.

I conceren that this description could cause misunderstanding.
Now `save_pcd` service is always advertised regardless of `duration`. 
It only switches the timer.

To set `duration` to 0 is equivalent to `always_save`=false, so I assume that `duration` works  in 0.0 ~ 1.0 range without additional rosparam.

**Comment by mqcmd196** [comment]
I agree with 
> I conceren that this description could cause misunderstanding.

> Now save_pcd service is always advertised regardless of duration.
> It only switches the timer.
> 
> To set duration to 0 is equivalent to always_save=false, so I assume that duration works in 0.0 ~ 1.0 range without additional rosparam.

So all @YUKINA-3252 has to do are
- Set duration param to 0.0~
- Add return `true` in `savePCDCallback`

**Comment by YUKINA-3252** [comment]
Thank you for your comment.
Now I have set the minimum of the duration back to 0.0 and added the statement `return true` in `SavePCDCallback`.

**Review by mqcmd196 — APPROVED** [review]
lgtm

**Pull request merged**
