### PR TITLE
[jsk_pcl_ros/pointcloud_moveit_filter] build support moveit > 1.0.0

### PR DESCRIPTION
**Pull request by knorth55**
current implementation cause build failure with `moveit` `1.0.0`.
I change to be build with `moveit` `1.0.0`.
I build Kinetic with `moveit` `1.0.2`.

### CODE REVIEW

**Comment by k-okada** [comment]
why travis did not fail ?https://travis-ci.org/jsk-ros-pkg/jsk_recognition/builds/552684588

**Comment by knorth55** [comment]
because moveit 1.0.0 is not released in Kinetic debian yet.
http://packages.ros.org/ros-testing/ubuntu/pool/main/r/ros-kinetic-moveit-core/
--
Shingo Kitagawa
the University of Tokyo, JSK Lab
s-kitagawa@jsk.imi.i.u-tokyo.ac.jp


2019年7月9日(火) 21:10 Kei Okada <notifications@github.com>:

**Comment by k-okada** [comment]
but we also check melodic in travis.
--
◉ Kei Okada



2019年7月10日(水) 0:36 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
current master checks if it is melodic or not `#if ROS_VERSION_MINIMUM(1,14,0) // melodic`.
I change it to check `melodic or MoveIt1.0` or not.

**Comment by k-okada** [comment]
I see,thanks.

**Pull request merged**
