### PR TITLE
Upgrade jsk_travis to 0.4.8

### PR DESCRIPTION
**Pull request by wkentaro**
This is debugging for #1676

### CODE REVIEW

**Comment by wkentaro** [comment]
```


make[2]: *** [CMakeFiles/jsk_perception.dir/src/grid_label.cpp.o] Error 1


/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/polygon_array_color_likelihood.cpp: In member function 'virtual void jsk_perception::PolygonArrayColorLikelihood::likelihood(const ConstPtr&, const ConstPtr&)':


/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/polygon_array_color_likelihood.cpp:203:9: error: 'HistogramWithRangeBinArrayTocvMatND' is not a member of 'jsk_recognition_utils'


/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/polygon_array_color_likelihood.cpp:210:11: error: 'HistogramWithRangeBinArrayTocvMatND' is not a member of 'jsk_recognition_utils'


make[2]: *** [CMakeFiles/jsk_perception.dir/src/polygon_array_color_likelihood.cpp.o] Error 1


/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/color_histogram_label_match.cpp: In member function 'virtual void jsk_perception::ColorHistogramLabelMatch::subscribe()':


/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/src/color_histogram_label_match.cpp:87:5: error: 'warnNoRemap' is not a member of 'jsk_topic_tools'


make[2]: *** [CMakeFiles/jsk_perception.dir/src/color_histogram_label_match.cpp.o] Error 1


make[1]: *** [CMakeFiles/jsk_perception.dir/all] Error 2


make: *** [all] Error 2


[jsk_perception] <== '/workspace/ros/ws_jsk_recognition/build/jsk_perception/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j' failed with return code '2'



Failed <== jsk_perception          [ 1 minute and 15.8 seconds ]
```

**Comment by wkentaro** [comment]
It seems that the old version jsk_topic_tools are looked up at building.

```
Selecting previously unselected package ros-hydro-jsk-topic-tools.

Unpacking ros-hydro-jsk-topic-tools (from .../ros-hydro-jsk-topic-tools_2.0.3-0precise-20150808-0742-+0000_amd64.deb) ...
```

**Comment by wkentaro** [comment]
Test fails on hydro will be fixed via **https://github.com/jsk-ros-pkg/jsk_travis/pull/266**

**Comment by wkentaro** [comment]
Still fails, because of not working  option.. No idea how to fix this. 
https://s3.amazonaws.com/archive.travis-ci.org/jobs/131736681/log.txt

**Comment by k-okada** [comment]
may because of removing imagesift/CATKIN_IGNORE in #1628, see #1684, now it seems working

**Comment by wkentaro** [comment]
> may because of removing imagesift/CATKIN_IGNORE

Sorry about that, but is it the actual reason?
In the log of #1628 (https://s3.amazonaws.com/archive.travis-ci.org/jobs/131325645/log.txt), there is no installation of ros-hydro-jsk-recognition-utils.

**Comment by wkentaro** [comment]
Even if without removing imagesift/CATKIN_IGNORE. It is fixed after rebooting.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1685
https://travis-ci.org/jsk-ros-pkg/jsk_recognition/builds/131874544

**Pull request closed without merging**
