### PR TITLE
Re-enable tests which use chainer inside them

### LINKED ISSUE #2272: Test failures caused by the regression of Chainer v4
https://api.travis-ci.org/v3/job/370870512/log.txt
```
jsk_perception/test_results/jsk_perception/rosunit-test_regional_feature_based_object_recognition.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_perception/test_results/jsk_perception/rosunit-test_vgg16_object_recognition.xml: 1 tests, 0 errors, 1 failures, 0 skipped

```
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk-recognition-indigo-deb-true-true-http-packages-ros-org-ros-ubuntu/751/consoleText
```
jsk_perception/test_results/jsk_perception/rosunit-test_regional_feature_based_object_recognition.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_perception/test_results/jsk_perception/rosunit-test_ssd_object_detector.xml: 1 tests, 1 errors, 0 failures, 0 skipped
```
https://api.travis-ci.org/v3/job/370870515/log.txt
```
jsk_perception/test_results/jsk_perception/rosunit-test_regional_feature_based_object_recognition.xml: 1 tests, 0 errors, 1 failures, 0 skipped
jsk_perception/test_results/jsk_perception/rosunit-test_vgg16_object_recognition.xml: 1 tests, 0 errors, 1 failures, 0 skipped
```

to avoid chainer issue (https://github.com/jsk-ros-pkg/jsk_recognition/pull/2268#issuecomment-383804409), I have manually installed working cersion for docker
```
echo -e "FROM ros-ubuntu:14.04\nRUN pip install matplotlib==2.0.0 chainer==4.0.0 chainercv==0.9.0 fcn==6.3.0\nEXPOSE 22" | sudo docker build -t ros-ubuntu:14.04 -
```
The issue is reported at https://github.com/chainer/chainer/issues/4670 and @makabe0510 had this issue on 73B1, maybe @sshige 's issue is caused by this.

### PR DESCRIPTION
**Pull request by wkentaro**
Close #2272

### CODE REVIEW

**Comment by wkentaro** [comment]
```
chainer 4.0.0 has requirement numpy>=1.9.0, but you'll have numpy 1.8.2 which is incompatible.
pandas 0.22.0 has requirement numpy>=1.9.0, but you'll have numpy 1.8.2 which is incompatible.
```

**Comment by wkentaro** [comment]
@k-okada Now the test passed. It seems pre-installed chainer is causing the issue, because it is installed with old pip, and right version of numpy is not installed. 

I think we should resolve this using BEFORE_SCRIPT, and will fix completely with #2199. The issue is caused by the fact that the Dockerfile is not under control, I think.

**Comment by wkentaro** [comment]
@k-okada It seems ready to be merged. Could you review this?

**Comment by wkentaro** [comment]
> Did you run ‘pip install numpy ....’ within docker at jenkins machine?

no

> How about classifier test, do they have another problem then wrong version of numpy?

No, so I will add them too.

Please add link to chaniner reposoitory on this numpy issue

**Comment by k-okada** [comment]
I see, so how about running something link
````
echo -e "FROM ros-ubuntu:14.04\nRUN curl https://bootstrap.pypa.io/get-pip.py | python -; /usr/local/bin/pip install 'pip<10'; /usr/local/bin/pip install -I chainer\nEXPOSE 22" | sudo docker build -t ros-ubuntu:14.04 -
```
in jenkins machine? (see https://github.com/jsk-ros-pkg/jsk_travis)

1. Since `jsk_recognition` depends on chianer, will `jsk_recognition` not run with system installed pip? https://packages.ubuntu.com/search?keywords=python-pip
2. jsk_recognition does not work with system installed numpy ? https://packages.ubuntu.com/search?keywords=python-numpy

**Comment by wkentaro** [comment]
Yeah, it seems better at this time. 

> 1.

I think if we can specify package version in `package.xml`,
it works, but the use of catkin_virtualenv seems better.

> 2.

Maybe we should specify old chainer which depends on numpy as the dependency of jsk_recognition.

**Pull request merged**
