### PR TITLE
Use Travis instead of Jenkins

### PR DESCRIPTION
**Pull request by wkentaro**
Because Jenkins is unstable, I'm tired of restarting it.

### CODE REVIEW

**Comment by wkentaro** [comment]
This requires https://github.com/jsk-ros-pkg/jsk_travis/pull/288.

**Comment by wkentaro** [comment]
Hmm, it's really tough.
screen shot 2016-08-05 at 17 09 56

**Comment by k-okada** [comment]
using local apt repo?
https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-with-the-APT-Addon


--
◉ Kei Okada

**Comment by wkentaro** [comment]
> using local apt repo?
https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-with-the-APT-Addon

@k-okada Do you mean installing ROS via local apt repo?

**Comment by k-okada** [comment]
yes, and may be https://github.com/travis-ci/apt-source-whitelist/issues/171
is the blocker.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
@k-okada Thanks for the info. I'm closing this at at this time, and maybe will make another PR after some new features of Travis.

**Pull request closed without merging**
