### PR TITLE
[jsk_perception] Use jsk_data download_data function for test_data

### PR DESCRIPTION
**Pull request by wkentaro**
Depends on jsk-ros-pkg/jsk_common#1383

### CODE REVIEW

**Comment by k-okada** [comment]
merged after jsk_common releases

**Comment by wkentaro** [comment]
TODO: https://github.com/jsk-ros-pkg/jsk_travis/issues/253
It is expected to be failed
```
                                                                               
[jsk_perception:make] make[1]: Leaving directory `/workspace/ros/ws_jsk_recognition/build/jsk_perception'




                                                                                
[jsk_perception:make] make: *** [run_tests] Error 2



Failed <<< jsk_perception                         [ 0.5 seconds ]

Abandoned <<< jsk_pcl_ros                            [ Unrelated job failed ]

Abandoned <<< imagesift                              [ Unrelated job failed ]

Abandoned <<< resized_image_transport                [ Unrelated job failed ]


Finished <<< jsk_pcl_ros_utils                      [ 0.3 seconds ]

[build] Summary: 4 of 8 packages succeeded.

[build] Ignored: None.

[build] Warnings: None.

[build] Abandoned: 3 packages were abandoned.

[build] Failed: 1 packages failed.

[build] Runtime: 9.8 seconds total.

+ catkin_test_results build

Summary: 4 tests, 0 errors, 0 failures

+ travis_time_end

+ set +x

traivs_time:end:62ov6v3p:start=1461928060846147418,finish=1461928072949545664,duration=12103398246
```
but the exit code is 0 so test passes.

**Comment by wkentaro** [comment]
```
executing command [sudo -H apt-get install -y -qq ros-indigo-jsk-data]

Selecting previously unselected package ros-indigo-jsk-data.

(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 107007 files and directories currently installed.)

Preparing to unpack .../ros-indigo-jsk-data_2.0.11-0trusty-20160420-075701-0700_amd64.deb ...

Unpacking ros-indigo-jsk-data (2.0.11-0trusty-20160420-075701-0700) ...

Setting up ros-indigo-jsk-data (2.0.11-0trusty-20160420-075701-0700) ...

```

**Comment by wkentaro** [comment]
```
[jsk_common/jsk_tools] Fetching https://github.com/tork-a/jsk_common-release/archive/release/indigo/jsk_tools/2.0.14-0.tar.gz (version jsk_common-release-release-indigo-jsk_tools-2.0.14-0) to /workspace/ros/ws_jsk_recognition/src/jsk_common/jsk_tools

[jsk_common/jsk_tools] Done.

[jsk_recognition] Updating /workspace/ros/ws_jsk_recognition/src/jsk_recognition

WARNING [vcstools] Command failed: 'git submodule update --init --recursive'

 run at: '/workspace/ros/ws_jsk_recognition/src/jsk_recognition'

 errcode: 1:

perl: warning: Setting locale failed.

perl: warning: Please check that your locale settings:

	LANGUAGE = (unset),

	LC_ALL = (unset),

	LANG = "en_US.UTF-8"

    are supported and installed on your system.

perl: warning: Falling back to the standard locale ("C").

perl: warning: Setting locale failed.

perl: warning: Please check that your locale settings:

	LANGUAGE = (unset),

	LC_ALL = (unset),

	LANG = "en_US.UTF-8"

    are supported and installed on your system.

perl: warning: Falling back to the standard locale ("C").

fatal: Not a git repository: /var/lib/jenkins/jobs/trusty-travis-jsk-ros-pkg-jsk_recognition-indigo-deb-true-true/workspace@2/jenkins-trusty-travis-jsk-ros-pkg-jsk_recognition-indigo-deb-true-true-2401/jsk-ros-pkg/jsk_recognition/.git/modules/.travis

Unable to find current revision in submodule path '.travis'

[/vcstools]

Exception caught during install: Error processing 'jsk_recognition' : [jsk_recognition] Update Failed of /workspace/ros/ws_jsk_recognition/src/jsk_recognition



ERROR in config: Error processing 'jsk_recognition' : [jsk_recognition] Update Failed of /workspace/ros/ws_jsk_recognition/src/jsk_recognition

```

**Comment by wkentaro** [comment]
PLZ merge this

**Comment by wkentaro** [comment]
please-xySPXHdgIWWCQ

**Comment by knorth55** [comment]
:+1:

**Pull request merged**
