### PR TITLE
Implement ConvexHullMaskImage

### PR DESCRIPTION
**Pull request by wkentaro**
~~https://cloud.githubusercontent.com/assets/4310419/15577496/c204df16-2397-11e6-92fe-460bca6fccf3.png~~

~~https://cloud.githubusercontent.com/assets/4310419/15599608/4660a060-241f-11e6-82c4-3903f73b21a4.png~~

image

### CODE REVIEW

**Comment by k-okada** [comment]
what do you mean by 'rectify mask image', set mask image as rectangle and rectify  with camera_info?

**Comment by wkentaro** [comment]
> what do you mean by 'rectify mask image', set mask image as rectangle and rectify with camera_info?

I mean converting input mask image to have a rectangle white region.
It only uses mask image and find a minimum size of rectangle which cover the all white region of the input.

In the above example, left is the input and right is the output.

**Comment by k-okada** [comment]
aha, that's may not 'rectify', rectangularr-fy ? rectangle - convex - hull ?? may be better to ask @iKrishneel

**Comment by iKrishneel** [comment]
I agree with @k-okada sensei that its not rectification but a convex hull with minimum bounding box.

**Comment by iKrishneel** [comment]
Just a comment: The function `boundingRectOfMaskImage(.)` simply searches for first and last non-zero pixel, therefore if you notice on your image on the left, small noisy white pixels gets included on the rectangular bounding box. This function therefore is not robust to noisy mask image in general. 

I did something similar before, but I used `cv::convexHull( , )` on the contour points. whereby small noisy pixels/regions can be removed using contour smoothing, which helps to remove small noisy regions and gives better boundary confined rectangular mask.

**Comment by wkentaro** [comment]
Thank you both.
I found I just need to compute convex hull with maximum area of contour of the mask image.
So name was changed to **ConvexHullMaskImage** and I also updated the image on the top of this PR.

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
Does this node really support 'convex hull'? Or 'rectangle'?

**Comment by wkentaro** [comment]
convex hull

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
Can you update example image so that we can recognize this node supports "Convex Hull" ?

**Comment by wkentaro** [comment]
Updated.

**Comment by k-okada** [comment]
thanks you,
I'm sorry but I prefer previous image because that makes easy to understand
what are you tring to do, courrnt image is very hard to understand what the
target is.
https://cloud.githubusercontent.com/assets/4310419/15599608/4660a060-241f-11e6-82c4-3903f73b21a4.png
so how about using kiva pod and human is trying to grab something so left
image could contain frontal face of the pod and a part of human hand? or
take human shape and compare convex hull and rectangle

--
◉ Kei Okada

**Comment by wkentaro** [comment]
I'm trying to find appropriate mask processing for object recognition in
robotic hand.
The kiva pod image was used just for sample.

2016年5月30日月曜日、Kei Okada<notifications@github.com>さんは書きました:

> thanks you,
> I'm sorry but I prefer previous image because that makes easy to understand
> what are you tring to do, courrnt image is very hard to understand what the
> target is.
>
> https://cloud.githubusercontent.com/assets/4310419/15599608/4660a060-241f-11e6-82c4-3903f73b21a4.png
> so how about using kiva pod and human is trying to grab something so left
> image could contain frontal face of the pod and a part of human hand? or
> take human shape and compare convex hull and rectangle
>
> --
> ◉ Kei Okada
>
>
> On Sat, May 28, 2016 at 11:27 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Updated.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_recognition/pull/1697#issuecomment-222311273
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AAeG3Cic6nn1zCp0w-XAHykWtw4WnT_Uks5qGFDLgaJpZM4Inlg1
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1697#issuecomment-222393441>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEHFk_y-65G5Ajdj7HWfbdKMBUGrwIvOks5qGjYAgaJpZM4Inlg1>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Pull request merged**
