### PR TITLE
[imagesift] Add sample of imagesift

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by garaemon** [comment]
Please check it works on PR2

**Comment by wkentaro** [comment]
you mean inside the PR2 robot?

**Comment by garaemon** [comment]
Yes, PR2 is the only robot using imagesift.

**Comment by garaemon** [comment]
and baxter?

**Comment by wkentaro** [comment]
**BAXTER**
screenshot from 2015-06-29 17 12 31

**Comment by wkentaro** [comment]
**PR2**
image

**Comment by k-okada** [comment]
need to check if this will not break demo program @furushchev

**Pull request merged**
