### PR TITLE
[jsk_perception] Support fcn8s_atonce model in fcn_object_segmentation.py

### PR DESCRIPTION
**Pull request by YutoUchimi**
Network weight of FCN8s and FCN8sAtOnce are the same shape, but some parameters are different and should be distinguished.
The accuracy becomes very low if you use wrong model.

- correct
fcn8s_atonce_correct

- wrong
fcn8s_atonce_wrong

### CODE REVIEW

**Comment by YutoUchimi** [comment]
@knorth55 Thanks! Updated.

**Comment by knorth55** [comment]
This PR is ready to be merged!

**Comment by k-okada** [comment]
Merged, but @yuki-shark please learn how to use `git merge`, `git rebase` etc...

**Comment by yuki-shark** [comment]
@k-okada ok, thanks.

**Pull request merged**
