### PR TITLE
Fix missing dependency declaration of jsk_pcl_ros

### PR DESCRIPTION
**Pull request by iory**

### CODE REVIEW

**Comment by iory** [comment]
here
https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/launch/openni2_remote.launch#L180-L197

**Comment by wkentaro** [comment]
Then, `run_depend`?

**Comment by iory** [comment]
year, should write run_depend only?

**Comment by wkentaro** [comment]
I think so.

**Comment by iory** [comment]
thanks

**Comment by wkentaro** [comment]
Then, `rosrun roslaunch roslaunch-check openni2_remote.launch` passes?

**Comment by wkentaro** [comment]
Why not add `roslaunch_add_test` to CMakeLists.txt?

**Comment by wkentaro** [comment]
BTW, do you know why openni2_remote.launch is located in jsk_pcl_ros?
It should be located in `resized_image_transport` if it depends on the package, don't you think?

**Comment by wkentaro** [comment]
Ah, I noticed that it also uses `jsk_pcl/ResizedPointsPublisher`

**Comment by iory** [comment]
```
 rosrun roslaunch roslaunch-check openni2_remote.launch
```
passed

**Comment by wkentaro** [comment]
Why not add roslaunch_add_file_check to CMakeLists.txt?
https://github.com/ros/ros_comm/blob/kinetic-devel/tools/roslaunch/cmake/roslaunch-extras.cmake.em#L24

**Comment by iory** [comment]
added

**Comment by wkentaro** [comment]
LGTM

**Comment by iory** [comment]
thanks

2016-09-17 17:12 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
oops youre missing find_package for roslaunch?

**Comment by iory** [comment]
OK, added find_package for roslaunch and package.xml's test_dependencies

**Comment by wkentaro** [comment]
LGTM

**Comment by iory** [comment]
Please merge this.

**Pull request merged**
