### PR TITLE
[WIP][jsk_recognition_utils] add TfListener wrapper class to provide commom API for tf / tf2

### PR DESCRIPTION
**Pull request by furushchev**
Yet another pull request of https://github.com/jsk-ros-pkg/jsk_recognition/pull/1439

### CODE REVIEW

**Comment by k-okada** [comment]
please send PR to upstream too

--
◉ Kei Okada


2017-07-02 1:35 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
@k-okada Sure,,, where is the upstream? I can at least imagine who wants this other than as recognition nodelet, so `jsk_topic_tools` is good to put it?

**Comment by k-okada** [comment]
somewhere in tf/tf2?

--
◉ Kei Okada


2017-07-03 18:19 GMT+09:00 Furushchev <notifications@github.com>:

**Comment by furushchev** [comment]
Closed this time since tf synchronizer heavily depends on tf1 and looks not easy  to migrate to tf2

**Pull request closed without merging**
