### PR TITLE
[jsk_pcl_ros/cluster_point_indices_decomposer] Modified publishNegativeIndices to make it fast

### PR DESCRIPTION
**Pull request by iory**
Related to #2325 

This PR modified ```publishNegativeIndices``` function to make it faster than current implementation
and add publish ```~/output/negative_indices``` when subscriber connected.

### CODE REVIEW

**Comment by wkentaro** [comment]
You did a great job! @iory 
What about invoking a warning for a large class of the input cluster indices in order to introduce users to the `~publish_negative_indices` param?

**Comment by iory** [comment]
@wkentaro  I agree with you.
I'll add commit

**Comment by wkentaro** [comment]
It looks great and good to me. 

BTW, I think we can check the ~output/negative_indices is subscribed or not. Could you add it?

**Comment by wkentaro** [comment]
Now I think we don't need `~publish_negative_indices` param. What do you think? @iory

**Comment by iory** [comment]
I think so. Should I remove that commit or rebase?

**Comment by wkentaro** [comment]
Could you do that?

**Comment by iory** [comment]
OK. I did

**Comment by Affonso-Gui** [comment]
Travis is failing at kinetic due to some timeouts (apparently).
Maybe restart travis should do?

**Comment by Affonso-Gui** [comment]
travis error:
```
docker: Error response from daemon: Conflict. 
The name "/jsk-ros-pkg.jsk_recognition_6705.6" is already in use by container d7df81aa5bf6a64fa734bf989c70c326f911625f00a8a5228a9511c8606eeb1f. 
You have to remove (or rename) that container to be able to reuse that name..
```
Any ideas how to fix this?
@k-okada 
@knorth55

**Comment by knorth55** [comment]
@iory is working on this travis issue

**Comment by iory** [comment]
@k-okada 

Travis passed.
This patch's change is slight and improve performance of ```cluster_point_indices_decomposer```.

Could you please merge this?

**Comment by iory** [comment]
@k-okada 

This patch is reviewed and approved.
Could you please merge this?

**Comment by Affonso-Gui** [comment]
@k-okada @iory Maybe should have a new tag soon?

**Pull request merged**
