### PR TITLE
[jsk_perception] FastRCNN: (new node)

### PR DESCRIPTION
**Pull request by wkentaro**
fast_rcnn_caffenet
image

### CODE REVIEW

**Comment by k-okada** [comment]
can we find the yellow object behind the bottle, also interested if we can find 2 objects in the next bin

**Comment by wkentaro** [comment]
It only supports below objects:
```
CLASSES = ('__background__',
             'aeroplane', 'bicycle', 'bird', 'boat',
             'bottle', 'bus', 'car', 'cat', 'chair',
             'cow', 'diningtable', 'dog', 'horse',
             'motorbike', 'person', 'pottedplant',
             'sheep', 'sofa', 'train', 'tvmonitor')
```
so we need train the classifier again. 
But we need a large memory to do that. ( currently I use trained one )

**Comment by k-okada** [comment]
put car object behind the bottle

--
◉ Kei Okada

**Comment by wkentaro** [comment]
I think it works theoretically.
Do you want to see the actual result?

2015年11月9日月曜日、Kei Okada<notifications@github.com>さんは書きました:

> put car object behind the bottle
>
> --
> ◉ Kei Okada
>
>
> On Mon, Nov 9, 2015 at 2:54 PM, Kentaro Wada <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > It only supports below objects:
> >
> > CLASSES = ('__background__',
> > 'aeroplane', 'bicycle', 'bird', 'boat',
> > 'bottle', 'bus', 'car', 'cat', 'chair',
> > 'cow', 'diningtable', 'dog', 'horse',
> > 'motorbike', 'person', 'pottedplant',
> > 'sheep', 'sofa', 'train', 'tvmonitor')
> >
> > so we need train the classifier again.
> > But we need a large memory to do that. ( currently I use trained one )
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/jsk-ros-pkg/jsk_recognition/pull/1299#issuecomment-154944340
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1299#issuecomment-154995596>
> .
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
TEST.

**Comment by wkentaro** [comment]
frame0000
frame0001
frame0002
frame0003
frame0004

**Comment by k-okada** [comment]
does this detector not invariant to the rotation of the object?, which
means the object must stand on the horizontal plane?

--
◉ Kei Okada


2015-11-09 23:15 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
that depends on how the classifier is trained.
The current classifier does work in horizontaly for bottle.
But tv monitor with rotation posture is recognized.
frame0001

**Comment by wkentaro** [comment]
Please merge.

**Pull request merged**
