### PR TITLE
[jsk_pcl_ros/PointcloudDatabaseServer] fix and improve for frame_id

### PR DESCRIPTION
**Pull request by knorth55**
MERGE AFTER #1625 
Before modification, there is no string (such as `""`) in frame_id.
In this PR, frame_id is named after`.pcd` file's name without extension `.pcd`

### CODE REVIEW

**Comment by wkentaro** [comment]
Could you please add a test?

**Comment by knorth55** [comment]
ok, which do you prefer? i think test is better.

**Comment by wkentaro** [comment]
You can right both without taking so much time, can't you? I mean using `<include>` tag in test launch file.

**Comment by knorth55** [comment]
i see

**Comment by k-okada** [comment]
should we wait for test program?

**Comment by knorth55** [comment]
that is better

**Comment by knorth55** [comment]
please merge this

**Pull request merged**
