### PR TITLE
jsk_pcl_ros: add sample door detector

### PR DESCRIPTION
**Pull request by furushchev**
Add sample launch file for application to door detector.

hrp2_door_detect

### CODE REVIEW

**Comment by snozawa** [comment]
hrp2_door_recog
Thanks!!

**Comment by furushchev** [comment]
@snozawa Edited and attached on the top! Thanks for trying!

**Comment by wkentaro** [comment]
If you can, please put a rosbag file to try this sample.

**Comment by furushchev** [comment]
@wkentaro Done!

**Comment by snozawa** [comment]
@furushchev (for reminder)

PCL seem not to support no-execution when no subscriber exists.
Using throttle such as LightWeightThrottle reduces CPU load.

**Comment by wkentaro** [comment]
@snozawa https://github.com/ros-perception/perception_pcl/pull/153 will solve your problem.

**Comment by furushchev** [comment]
- [ ] TF 'ground' is ok? @snozawa 
- [ ] wait for https://github.com/jsk-ros-pkg/jsk_recognition/pull/2189
- [ ] wait for https://github.com/jsk-ros-pkg/jsk_recognition/pull/2191

**Comment by furushchev** [comment]
BTW, I think it'd be better if we can generalize a frame that represents `base_footprint` or `ground` originally.
@snozawa @mmurooka 
Do you have any idea about defining `base_footprint` for all robots?
(I know it is hard to define the frame like a `base_footprint` for wheeled robots on some specific environment, for example on stairs.)

**Comment by mmurooka** [comment]
As for hrpsys robot, base_footprint is same with root link
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/launch/robot_pose_ekf.launch#L13-L16

Ground is midcoords of lleg endcoords and rleg endcoords (i.e. `(midcoords 0.5 (send *robot* :lleg :endcoords) (send *robot* :rleg :endcoords))`) .
https://github.com/jsk-ros-pkg/jsk_control/blob/master/jsk_footstep_controller/README.md

Is base_footprint already broadcasted for PR2?
```
7.irteusgl$ (car (send *pr2* :links))
#<bodyset-link #X6768bb8 base_footprint  0.0 0.0 0.0 / 0.0 0.0 0.0>
```

**Comment by snozawa** [comment]
> Do you have any idea about defining base_footprint for all robots?
> (I know it is hard to define the frame like a base_footprint for wheeled robots on some specific environment, for example on stairs.)

I'd like to know the definitions of `base_footprint` and `ground` because I forgot related discussions about this (few years ago).

**Comment by furushchev** [comment]
AFAIK, `base_footprint` is a frame that represents `base_link` projected into a floor which supports the robot.
What is important is the normal direction of the supporting floor can be identified from the frame from the perspective of this application.

**Comment by furushchev** [comment]
@k-okada I think it is already ok to be merged, isn't it?

**Comment by furushchev** [comment]
@snozawa When you have time, please let me know which nodelets you replaced :+1:

**Pull request merged**
