### PR TITLE
Enhance PeoplePoseEstimation2D

### PR DESCRIPTION
**Pull request by wkentaro**
Close #2161 

## Why?

- Support 16UC1 depth image in PeoplePoseEstimation2D
- Fix AttributeError of argsort in cupy == 1.0.1
- Add script to convert people pose to pose array

## Updated sample

sample_peple_pose_estimation_2d

### CODE REVIEW

**Comment by furushchev** [comment]
@wkentaro
Great! BTW, is it possible to switch download source uri on different version of chainer?
(It's still necessary to download another weights on chainer v1 env)

**Comment by wkentaro** [comment]
Yes, it's possible.

**Comment by furushchev** [comment]
@wkentaro SUPER!!!! THX!!!!!

**Comment by wkentaro** [comment]
```


ERROR: the following rosdeps failed to install

  apt: command [sudo -H apt-get install -y -qq ros-indigo-openni2-launch] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-sound-play] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-image-view] failed

  apt: command [sudo -H apt-get install -y -qq python-h5py] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-moveit-core] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-opencv-apps] failed

  apt: command [sudo -H apt-get install -y -qq liblapack-dev] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-jsk-topic-tools] failed

  apt: command [sudo -H apt-get install -y -qq cython] failed

  apt: command [sudo -H apt-get install -y -qq python-sklearn] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-cv-bridge] failed

  apt: command [sudo -H apt-get install -y -qq libyaml-cpp-dev] failed

  apt: command [sudo -H apt-get install -y -qq python-skimage] failed

  apt: command [sudo -H apt-get install -y -qq python-coverage] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-image-view2] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-robot-self-filter] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-kdl-parser] failed

  apt: command [sudo -H apt-get install -y -qq python-mock] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-image-geometry] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-jsk-tools] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-rqt-gui] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-rviz] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-jsk-rqt-plugins] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-tf-conversions] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-roseus] failed

  apt: command [sudo -H apt-get install -y -qq libcppunit-dev] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-openni-launch] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-posedetection-msgs] failed

  apt: command [sudo -H apt-get install -y -qq python-imaging] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-libcmt] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-stereo-image-proc] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-jsk-data] failed

  apt: command [sudo -H apt-get install -y -qq ros-indigo-moveit-ros-perception] failed

  apt: command [sudo -H apt-get install -y -qq libleveldb-dev] failed

  apt: Failed to detect successful installation of [python-h5py]

  apt: Failed to detect successful installation of [python-imaging]

  apt: Failed to detect successful installation of [ros-indigo-image-view]

  apt: Failed to detect successful installation of [python-skimage]

  apt: Failed to detect successful installation of [ros-indigo-posedetection-msgs]

  apt: Failed to detect successful installation of [ros-indigo-openni2-launch]

  apt: Failed to detect successful installation of [cython]

  apt: Failed to detect successful installation of [python-mock]

  apt: Failed to detect successful installation of [python-sklearn]

  apt: Failed to detect successful installation of [ros-indigo-image-geometry]

  apt: Failed to detect successful installation of [ros-indigo-jsk-tools]

  apt: Failed to detect successful installation of [ros-indigo-rqt-gui]

  apt: Failed to detect successful installation of [ros-indigo-robot-self-filter]

  apt: Failed to detect successful installation of [libyaml-cpp-dev]

  apt: Failed to detect successful installation of [ros-indigo-rviz]

  apt: Failed to detect successful installation of [ros-indigo-libcmt]

  apt: Failed to detect successful installation of [ros-indigo-stereo-image-proc]

  apt: Failed to detect successful installation of [python-coverage]

  apt: Failed to detect successful installation of [ros-indigo-roseus]

  apt: Failed to detect successful installation of [ros-indigo-opencv-apps]

  apt: Failed to detect successful installation of [liblapack-dev]

  apt: Failed to detect successful installation of [libcppunit-dev]

  apt: Failed to detect successful installation of [ros-indigo-jsk-topic-tools]

  apt: Failed to detect successful installation of [libleveldb-dev]

  apt: Failed to detect successful installation of [ros-indigo-kdl-parser]

  apt: Failed to detect successful installation of [ros-indigo-sound-play]

  apt: Failed to detect successful installation of [ros-indigo-jsk-rqt-plugins]

  apt: Failed to detect successful installation of [ros-indigo-jsk-data]

  apt: Failed to detect successful installation of [ros-indigo-cv-bridge]

  apt: Failed to detect successful installation of [ros-indigo-image-view2]

  apt: Failed to detect successful installation of [ros-indigo-openni-launch]

  apt: Failed to detect successful installation of [ros-indigo-moveit-core]

  apt: Failed to detect successful installation of [ros-indigo-tf-conversions]

  apt: Failed to detect successful installation of [ros-indigo-moveit-ros-perception]

```

**Comment by wkentaro** [comment]
@k-okada Could u please merge this?

**Pull request merged**
