### PR TITLE
Use diagnostic nodelet for EuclideanClustering and other nodelets

### PR DESCRIPTION
**Pull request by furushchev**
- `EuclideanClusteringNodelet`
    Maybe since this nodelet is implemented before `DiagnosticNodelet` was present, this nodelet has almost the same function as in `DiagnosticNodelet`. In this PR, I changed the super class of this nodelet from `ConnectionBasedNodelet` to `DiagnosticNodelet` and removed the duplicated codes.
- `ClusterPointIndicesDecomposer` and other nodelets
    This nodelet currently inherits `DiagnosticNodelet` but implement own `updateDiagnostic` function  instead of the function in `DiagnosticNodelet`. In this PR, I removed duplicated codes from this class.
- Remove duplicate functions from `jsk_recognition_utils`
    There are some functions that is also implemented in `jsk_topic_tools`. I fixed to let them use the functions in `jsk_topic_tools`.
- Minor bugfixes
Also while I was fixing these nodelets, I also found that some nodelets don't call `onInitPostProcess` in the last line of `onInit` function.

- Add `<build_depend version_gte="2.2.7">jsk_topic_tools</build_depend>` for `jsk_pcl_ros`
The package now requires https://github.com/jsk-ros-pkg/jsk_common/pull/1585

### CODE REVIEW

**Comment by k-okada** [comment]
@furushchev @iory 
we need fix
```
Errors << jsk_pcl_ros:make /workspace/ros/ws_jsk_recognition/logs/jsk_pcl_ros/build.make.000.log
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/joint_state_static_filter_nodelet.cpp: In member function 'virtual void jsk_pcl_ros::JointStateStaticFilter::updateDiagnostic(diagnostic_updater::DiagnosticStatusWrapper&)':
/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/src/joint_state_static_filter_nodelet.cpp:177:38: error: 'diagnostic_error_level_' was not declared in this scope
           name_, joint_vital_, stat, diagnostic_error_level_);
```

**Comment by k-okada** [comment]
oh, please add "versoin_gte" attribute to package.xml

**Comment by furushchev** [comment]
@k-okada Thanks. Added!

**Comment by k-okada** [comment]
please add them both build_depend and run_depend https://github.com/ros-gbp/cartographer_ros-release/issues/11#issuecomment-396352099

**Comment by furushchev** [comment]
@k-okada Thanks. Updated. 勉強になりました．

**Comment by k-okada** [comment]
released jsk_common 2.2.27
indigo: https://github.com/ros/rosdistro/pull/18285
kinetic: https://github.com/ros/rosdistro/pull/18286

**Comment by furushchev** [comment]
@k-okada Thank you. I found that some tests use stable repo for fetching deb files.
I will restart the test again on next stable release.

**Comment by furushchev** [comment]
@k-okada Kinetic test failed because old version is installed on docker image in jenkins server.
Any chance to upgrade the docker image to the latest version?

**Pull request merged**
