### PR TITLE
[jsk_perception] Support latest sklearn in BoF feature extraction

### LINKED ISSUE #1669: [jsk_perception] bof_feature_extractor.py with old pickle does not work
If you install sklearn with pip, it raise error with old pickled data. (because of changed api)
```
[ERROR] [WallTime: 1463393760.278256] bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0x7fe54077a1d0>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/message_filters/__init__.py", line 74, in callback
    self.signalMessage(msg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/message_filters/__init__.py", line 56, in signalMessage
    cb(*(msg + args))
  File "/opt/ros/indigo/lib/python2.7/dist-packages/message_filters/__init__.py", line 199, in add
    self.signalMessage(*msgs)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/message_filters/__init__.py", line 56, in signalMessage
    cb(*(msg + args))
  File "/home/baxter/ros/indigo/src/jsk-ros-pkg/jsk_recognition/jsk_perception/node_scripts/bof_histogram_extractor.py", line 75, in _apply
    X = self.bof.transform(X)
  File "/home/baxter/ros/indigo/src/jsk-ros-pkg/jsk_recognition/jsk_recognition_utils/python/jsk_recognition_utils/feature.py", line 24, in transform
    return np.vstack([self.make_hist(xi.reshape((-1, 128))) for xi in X])
  File "/home/baxter/ros/indigo/src/jsk-ros-pkg/jsk_recognition/jsk_recognition_utils/python/jsk_recognition_utils/feature.py", line 31, in make_hist
    indices = nn.kneighbors(descriptors, return_distance=False)
  File "/home/baxter/.local/lib/python2.7/site-packages/sklearn/neighbors/base.py", line 366, in kneighbors
    n_jobs = _get_n_jobs(self.n_jobs)
AttributeError: 'NearestNeighbors' object has no attribute 'n_jobs'
```

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #1669

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
plz merge

**Comment by k-okada** [comment]
is it possible to specify install version in rosdep pip key?

**Comment by wkentaro** [comment]
Currently no I think.

**Comment by k-okada** [comment]
Humm, I think we'd better to have such feature, because pip is basically try to follow latest release, I think.
In our experience, we used HEAD version of assimp_devel and that very difficult to follow, after
https://github.com/jsk-ros-pkg/jsk_common/issues/408#issuecomment-41233271 comment, we freeze the assimp_devel version and that make us very happy.

**Comment by k-okada** [comment]
but specifying  package version for pip may have another problem, someone want to use latest and some want stable....

**Pull request merged**
