### PR TITLE
[doc/jsk_perception/nodes/skeletonization.md] update document

### PR DESCRIPTION
**Pull request by rkoyama1623**
add comment about output from Skeletonization.

### CODE REVIEW

**Comment by wkentaro** [comment]
:+1:

2015年11月14日土曜日、Ryo KOYAMA<notifications@github.com>さんは書きました:

> add comment about output from Skeletonization.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jsk-ros-pkg/jsk_recognition/pull/1317
> Commit Summary
>
>    - [doc/jsk_perception/nodes/skeletonization.md] update document
>
> File Changes
>
>    - *M* doc/jsk_perception/nodes/skeletonization.md
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1317/files#diff-0>
>    (3)
>
> Patch Links:
>
>    - https://github.com/jsk-ros-pkg/jsk_recognition/pull/1317.patch
>    - https://github.com/jsk-ros-pkg/jsk_recognition/pull/1317.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1317>.
>


-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
@rkoyama1623 could you please squash two commits?

**Comment by rkoyama1623** [comment]
OK, I've done.

**Comment by wkentaro** [comment]
Please send ping to k-okada.

**Pull request merged**
