### PR TITLE
[jsk_pcl_ros] Modified openni2_remote for republish compressed image

### PR DESCRIPTION
**Pull request by iory**
Related to https://github.com/jsk-ros-pkg/jsk_recognition/issues/2034

### CODE REVIEW

**Comment by wkentaro** [comment]
> This program might be used in many other users or robots, so I think default behavior should not be changed.
Please add arguments to use republish or not.

Maybe you can use relay instead of remap in order not to change the current behavior.

**Comment by mmurooka** [comment]
> This program might be used in many other users or robots, so I think default behavior should not be changed.
Please add arguments to use republish or not.
>> Maybe you can use relay instead of remap in order not to change the current behavior.

I talked locally with @wkentaro, 
and he said republish should work in all cases (users and robots), and keeping relay (current style) has no merit.
I search with google a while, and could not find republish is lossless compression or not.
So @wkentaro will check that with real robot data, and if it is lossless compression, let's use republish as default as @wkentaro says.

**Comment by wkentaro** [comment]
Actually, the compressed and compressedDepth cannot be decompressed in a loss-less way.
```
% ./check_loss_less.py \~input1:=/right_hand_camera/rgb/image_raw \~input2:=/right_hand_camera_local/rgb/image_raw                          
[ERROR] [1490085889.993181]: [/check_loss_less] [cb] 2.76236111111
```

```
% ./check_loss_less.py \~input1:=/right_hand_camera/rgb/image_raw \~input2:=/right_hand_camera_local/rgb/image_raw                          
[ERROR] [1490085889.993181]: [/check_loss_less] [cb] 2.76236111111

```

**Comment by iory** [comment]
@mmurooka modified, please check it.

**Comment by mmurooka** [comment]
LGTM

**Comment by k-okada** [comment]
```
Skipping "jsk_pcl_ros_utils/test_results/jsk_pcl_ros_utils/rosunit-test_pointcloud_to_mask_image.xml": no element found: line 2, column 0
Skipping "jsk_pcl_ros_utils/test_results/jsk_pcl_ros_utils/rosunit-test_pointcloud_to_point_indices.xml": no element found: line 2, column 0
Skipping "jsk_pcl_ros_utils/test_results/jsk_pcl_ros_utils/rosunit-test_subtract_point_indices.xml": no element found: line 2, column 0
Skipping "jsk_pcl_ros_utils/test_results/jsk_pcl_ros_utils/rosunit-test_add_point_indices.xml": no element found: line 2, column 0
Full test results for 'jsk_perception/test_results/jsk_perception/rosunit-test_bof_histogram_extractor.xml'
-------------------------------------------------
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="1" time="28.949"><testcase classname="__main__.TestTopicPublished" name="test_published" time="28.9484"><failure type="AssertionError">/bof_histogram_extractor/output is not published
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/jade/share/jsk_tools/src/test_topic_published.py", line 56, in test_published
    assert_true(checker.check(), msg)
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
</failure></testcase><system-out>&lt;![CDATA[
 Checking /bof_histogram_extractor/output for 30 seconds
]]&gt;</system-out><system-err>&lt;![CDATA[
WARNING: topic [/bof_histogram_extractor/output] does not appear to be published yet
]]&gt;</system-err></testsuite>
-------------------------------------------------
Full test results for 'jsk_perception/test_results/jsk_perception/rostest-test_bof_histogram_extractor.xml'
-------------------------------------------------
<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="1" failures="0" name="unittest.suite.TestSuite" tests="1" time="226.249"><testcase classname="rostest.runner.RosTest" name="testtest_bof_histogram_extractor" time="226.2484"><error type="RLTestTimeoutException">max time [30.0s] allotted for test [test_bof_histogram_extractor] of type [jsk_tools/test_topic_published.py]
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/runner.py", line 148, in fn
    self.test_parent.run_test(test)
  File "/opt/ros/jade/lib/python2.7/dist-packages/rostest/rostest_parent.py", line 132, in run_test
    return self.runner.run_test(test)
  File "/opt/ros/jade/lib/python2.7/dist-packages/roslaunch/launch.py", line 681, in run_test
    (test.time_limit, test.test_name, test.package, test.type))
</error></testcase><system-out>&lt;![CDATA[
[ROSTEST]setup[/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_perception/test/bof_histogram_extractor.test] run_id[9273907a-0e4d-11e7-baf1-0242ac110004] starting
&amp;#x001B;[1mstarted roslaunch server http://9e64b4e43226:46900/&amp;#x001B;[0m
SUMMARY
========
```

**Pull request merged**
