### PR TITLE
[Major Release] Remove extract_images_sync that merged in image_view

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
- ros-perception/image_pipeline#159 1.12.15
- ros-perception/image_pipeline#163 not yet merged
- ros-perception/image_pipeline#164 not yet merged

**Comment by wkentaro** [comment]
PLZ merge this.

**Comment by wkentaro** [comment]
plz merge

**Comment by k-okada** [comment]
I think we need to wait for https://github.com/jsk-ros-pkg/jsk_recognition/pull/1633#issuecomment-216022831

**Comment by wkentaro** [comment]
Ok.

**Comment by k-okada** [comment]
can we merge even if https://github.com/ros-perception/image_pipeline/pull/164 is not merged yet?

**Comment by wkentaro** [comment]
Yeah, I think so.
I will revise the current extract_image_sync in image_view to have a feature in image_save_sync.

**Pull request merged**
