### PR TITLE
[jsk_perception] Download trained_data with jsk_data function

### PR DESCRIPTION
**Pull request by wkentaro**

### CODE REVIEW

**Comment by k-okada** [comment]
need rebase?

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
why you need `.travis_before_script_released_testing.bash`, instead of just to use `ROS_REPOSITORY_PATH="http://packages.ros.org/ros/ubuntu"`

**Comment by wkentaro** [comment]
because we need latest jsk_data which is released in GitHub (not apt server) for `jsk_data.download_data` function.

**Comment by k-okada** [comment]
You mean do we need to release jsk_common?

2016年6月11日土曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> because we need latest jsk_data which is released in GitHub (not apt
> server) for jsk_data.download_data function.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1628#issuecomment-225210199>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeG3HKsRQvtoVhsj4WYdERPTX5JDCOsks5qKX8UgaJpZM4ISdtl>
> .
>


-- 
--
◉ Kei Okada

**Comment by wkentaro** [comment]
If I remember correctly, the jsk_common which this PR requires had been released only to shadow-fixed when I sent this PR.
That's why I need to install jsk_common from source only for testing with `ROS_REPOSITORY_PATH="http://packages.ros.org/ros/ubuntu"`.
Maybe that jsk_common is also released to `http://package.ros.org/ros/ubuntu` server and I can remove that before_script at this time.

screen shot 2016-06-12 at 17 09 16

**Pull request merged**
