### PR TITLE
Delay point cloud

### PR DESCRIPTION
**Pull request by iory**

### CODE REVIEW

**Comment by k-okada** [comment]
Why you need this

On Tuesday, 5 July 2016, iory <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/jsk-ros-pkg/jsk_recognition/pull/1769
> Commit Summary
>
>    - [jsk_pcl_ros_utils/delay_point_cloud] Refactor sleep_time ->
>    delay_time
>    - [jsk_pcl_ros_utils/delay_point_cloud] Modified delay_time as dynamic
>    parameter
>    - [jsk_pcl_ros_utils/delay_point_cloud] Modified delay_point's time
>    stampe
>    - [doc/jsk_pcl_ros_utils] Add doc for delay_point_cloud
>
> File Changes
>
>    - *A* doc/jsk_pcl_ros_utils/nodes/delay_point_cloud.rst
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1769/files#diff-0>
>    (26)
>    - *A* doc/jsk_pcl_ros_utils/nodes/images/delay_point_cloud.png
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1769/files#diff-1>
>    (0)
>    - *M* jsk_pcl_ros_utils/CMakeLists.txt
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1769/files#diff-2>
>    (1)
>    - *A* jsk_pcl_ros_utils/cfg/DelayPointCloud.cfg
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1769/files#diff-3>
>    (12)
>    - *M* jsk_pcl_ros_utils/include/jsk_pcl_ros_utils/delay_pointcloud.h
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1769/files#diff-4>
>    (18)
>    - *M* jsk_pcl_ros_utils/src/delay_pointcloud_nodelet.cpp
>    <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1769/files#diff-5>
>    (21)
>
> Patch Links:
>
>    - https://github.com/jsk-ros-pkg/jsk_recognition/pull/1769.patch
>    - https://github.com/jsk-ros-pkg/jsk_recognition/pull/1769.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_recognition/pull/1769>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AAeG3IWhXC08NVBzL1-7H3cCnv08NqzLks5qSUIYgaJpZM4JEioi>
> .
>


-- 
--
◉ Kei Okada

**Comment by iory** [comment]
In case of time dilation processing, 
I need a point cloud n seconds before.

**Comment by k-okada** [comment]
can you use message filter?
http://wiki.ros.org/message_filters

**Comment by wkentaro** [comment]
I guess @iory want to compare the delaied point cloud with one not delaied.

**Comment by iory** [comment]
I applyed message filter.
Please review this

**Comment by k-okada** [comment]
> I guess @iory want to compare the delaied point cloud with one not delaied.

so you need background subscruction? https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/src/octree_change_publisher_nodelet.cpp ?

**Comment by k-okada** [comment]
closed via #1860

**Pull request closed without merging**
