### PR TITLE
[jsk_perception] Fix supported encodings of split_fore_background.py

### PR DESCRIPTION
**Pull request by wkentaro**
It supports both 16UC1 and 32FC1.

### CODE REVIEW

**Comment by wkentaro** [comment]
To fix jsk-ros-pkg/jsk_perception#1332

**Comment by wkentaro** [comment]
plz merge

**Comment by k-okada** [comment]
@knorth55 ,please check if this fix your problem

**Comment by knorth55** [comment]
this is effective for the problem, thank you

**Pull request merged**
