### PR TITLE
[jsk_recognition_utils, jsk_recognition_msgs, jsk_pcl_ros] add element_matching_pose_estimation_nodelet

### PR DESCRIPTION
**Pull request by mmurooka**
model-based tracking
https://mail.google.com/mail/u/0/#search/IROS+%E5%AE%A4%E5%B2%A1/15a70168538e9fd8?projector=1

https://github.com/jsk-ros-pkg/jsk_visualization/pull/665 is necessary to debug with visualization.

### CODE REVIEW

**Comment by mmurooka** [comment]
一度に全部マージしてもらうのはさすがに厳しそうに思うので，
小分けにしてみました．（まだ全体の30%くらいです．）
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2030
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2031
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2032

**Comment by wkentaro** [comment]
I prefer LabeledPose.msg, because it is grammatically correct, I think.

**Comment by k-okada** [comment]
#2030 が close, #2031 が merge になったんだけど、ここはどうなるでしょうか？

**Comment by YoheiKakiuchi** [comment]
ping @mmurooka

**Comment by k-okada** [comment]
pong @mmurooka

**Comment by mmurooka** [comment]
遅くなりすみません．

#2030 -> closed（必要ないことがわかりました．）
#2031 -> merged
#2032 ->close and make new PR https://github.com/jsk-ros-pkg/jsk_recognition/pull/2047

ここまでで3割で残りもやります．

**Comment by k-okada** [comment]
ok, I closed this and marked ForNextRelease to -> https://github.com/jsk-ros-pkg/jsk_recognition/pull/2047

**Pull request closed without merging**
