### PR TITLE
fix doc build and typo in aws_auto_checkin_app doc

### PR DESCRIPTION
**Pull request by knorth55**
now `aws_auto_checkin_app` doc is messed up because of mixed syntax of md and rst.
I fixed the typo.
this PR also fix doc build.

current: https://jsk-docs.readthedocs.io/projects/jsk-recognition/en/latest/jsk_perception/nodes/aws_auto_checkin_app.html
this PR: https://knorth55-jsk-recognition.readthedocs.io/en/aws-auto-checkin-doc/jsk_perception/nodes/aws_auto_checkin_app.html

### CODE REVIEW

**Review by iory — APPROVED** [review]

**Comment by k-okada** [comment]
@iory thank you for review and approve. When you approve, I got notification email, that is good chance to merge the PR, but if the CI not passed, I have to restart CI and forget about this PR. So if you approve AFTER CI passed, I can push merge button immediately.

**Comment by knorth55** [comment]
all the test other than `noetic-full-test` passed.

**Comment by iory** [comment]
> thank you for review and approve. When you approve, I got notification email, that is good chance to merge the PR, but if the CI not passed, I have to restart CI and forget about this PR. So if you approve AFTER CI passed, I can push merge button immediately.

OK. I'll check the test.

**Comment by k-okada** [comment]
@knorth55 sorry to break your commit, but please resolve conflicts

**Comment by knorth55** [comment]
I resolve the conflicts.

**Pull request merged**
