### PR TITLE
jsk_pcl_ros: multi_plane_extraction: add option use_coefficients

### PR DESCRIPTION
**Pull request by furushchev**
Addresses #2186 

If `~use_sensor_frame` is false, the z-axis of plane may be flipped on each detection and coefficients topic is never used.
I added a new option `~use_coefficients` that determines z-axis of each planes.

**NOTE** Visualization of normal arrow in rviz is not valid. (To see actual z normal axis, we must consider both polygon and coefficients)

extraction_falure

extraction_success

### CODE REVIEW

**Comment by furushchev** [comment]
Just to clarify:

|                         | use_sensor_frame: false            | use_sensor_frame: true                 |   |   |
|-------------------------|------------------------------------|----------------------------------------|---|---|
| use_coefficients: false | PCL computes z-axis internally     | Determine z-axis direction to TF frame |   |   |
| use_coefficients: true  | Determine z-axis from coefficients | N/A (Warning shows up)                 |   |   |
|                         |                                    |                                        |   |   |

**Comment by k-okada** [comment]
Did you update doc?

**Comment by furushchev** [comment]
Totally forgot at all. Thanks.

**Comment by furushchev** [comment]
@k-okada OK. Updated.

**Comment by furushchev** [comment]
Now passed tests.

**Pull request merged**
