### PR TITLE
[resized_image_transport] Publish scale information

### PR DESCRIPTION
**Pull request by garaemon**
it does not support dst_width and dst_height

### CODE REVIEW

**Comment by garaemon** [comment]
fie COPY problem again
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_recognition-indigo-deb-true-true-jsk_pcl_ros/60/console

```
[[36mjsk_recognition_msgs[0m] [31m[1mCMake Error[0m at /opt/ros/indigo/share/catkin/cmake/catkin_add_env_hooks.cmake:91 (file):[0m [0m[0m
[[36mjsk_recognition_msgs[0m]   file COPY cannot set permissions on[0m [0m[0m
[[36mjsk_recognition_msgs[0m]   "/workspace/ros/ws_jsk_recognition/devel/etc/catkin/profile.d/05.catkin_make.bash"[0m [0m[0m
```

**Comment by k-okada** [comment]
humm, i created test packages for this issue, but not able to fail ->
https://travis-ci.org/k-okada/test_catkin_parallel/builds/50891939

--
◉ Kei Okada

**Comment by garaemon** [comment]
sometime it fails as we know...

**Comment by garaemon** [comment]
@k-okada Now you have COPY error! https://travis-ci.org/k-okada/test_catkin_parallel/jobs/50891940

**Comment by k-okada** [comment]
yes, I reported this to upstream issue ->
https://github.com/ros/catkin/issues/718

--
◉ Kei Okada

**Comment by garaemon** [comment]
on jenkins, I specified compilation without jsk_pcl_ros but it tries to compile jsk_pcl_ros

http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_recognition-indigo-deb-true-true-jsk_perception-checkerboard_detector-resized_image_transport-imagesift/71/console

**Comment by garaemon** [comment]
I think BUILD_PKG argument is not passed to jenkins

**Comment by garaemon** [comment]
typo?
`BUILD_PKGSS` -> `BUILD_PKGS`

```
sudo docker run -t -e ROS_DISTRO=indigo -e ROSWS=wstool -e BUILDER=catkin -e USE_DEB=true -e TRAVIS_REPO_SLUG=jsk-ros-pkg/jsk_recognition -e EXTRA_DEB="" -e NOT_TEST_INSTALL=true -e BUILD_PKGSS="jsk_perception checkerboard_detector resized_image_transport imagesift"  -e HOME=/workspace -v $WORKSPACE/${BUILD_TAG}:/workspace -w /workspace ros-ubuntu:14.04 /bin/bash -c "$(cat <<EOL

```

**Comment by garaemon** [comment]
see https://github.com/jsk-ros-pkg/jsk_travis/pull/60

**Pull request merged**
