### PR TITLE
Highlight syntax of *.test on GitHub

### PR DESCRIPTION
**Pull request by wkentaro**
screen shot 2016-10-11 at 7 56 25 am

screen shot 2016-10-11 at 7 56 10 am

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
humm, why https://github.com/jsk-ros-pkg/jsk_recognition/pull/1899 did not take care of this...

**Comment by wkentaro** [comment]
It is described here, but there is no reason .https://github.com/github/linguist#using-gitattributes

**Comment by wkentaro** [comment]
It seems that this solution is not good because it is not automated and we should **always** add the modeline.
So I close this at this time.

**Comment by k-okada** [comment]
good decision ;)

--
◉ Kei Okada


2016-10-15 5:54 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Pull request closed without merging**
