### PR TITLE
[jsk_pcl_ros] Modified openni2_remote.launch to change camera namespace

### PR DESCRIPTION
**Pull request by iory**
To change namespace of openni2_remote.launch, 
I modified camera value.

### CODE REVIEW

**Comment by mmurooka** [comment]
Did you check this with real HRP2 environment?

**Comment by iory** [comment]
Yes, I did.

2018年6月1日(金) 12:46 Masaki Murooka <notifications@github.com>:

**Comment by iory** [comment]
@k-okada Please merge this.

**Comment by k-okada** [comment]
waiting for @itohdak 's review

**Comment by iory** [comment]
Thanks!

**Pull request merged**
