### PR TITLE
Upgrade jsk_travis to 0.4.8 and fix some regressions

### PR DESCRIPTION
**Pull request by wkentaro**
Closes #1684

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
Please look at https://github.com/jsk-ros-pkg/jsk_recognition/pull/1684/commits/7602645a0e4e31471a937acf6339abeba3b420cf / https://github.com/jsk-ros-pkg/jsk_recognition/issues/1682 and update your PR

**Comment by k-okada** [comment]
also include https://github.com/jsk-ros-pkg/jsk_recognition/pull/1684/commits/975b7abd04a92929b891135b1c6ce8e6d59f6fb8 to this PR

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Please merge this.

**Pull request merged**
