### PR TITLE
Add hand pose estimation

### PR DESCRIPTION
**Pull request by knorth55**
refined version of #2597
@W567 you can open a PR as this.

```
roscd jsk_perception
git remote add W567 https://github.com/W567/jsk_recognition.git
git remote add knorth55 https://github.com/knorth55/jsk_recognition.git
git fetch --all
git checkout knorth55/add-hand-pose-estimation -b add-hand-pose-estimation
git push W567 add-hand-pose-estimation
```

### CODE REVIEW

**Comment by W567** [comment]
@knorth55 I see, I'll follow those steps to open the PR from now on. Thank you for your instruction and help!

**Comment by knorth55** [comment]
@W567 I tried with the sample launch, but the node detects nothing.
I think this is because camera image rgb field seems wrong to me.
can you give me rosbag of camera output not `/hand_pose_estimation_2d/input`?


https://user-images.githubusercontent.com/9300063/119374922-28a76300-bcf5-11eb-80c6-1d0919cb2f0f.mp4

**Comment by knorth55** [comment]
@W567 I also update your node to reformat all the stuff and I tried with my usb camera.
the result is like this and I cannot get detected result. I'm runing with `pytorch==1.4.0` `cpu`.

https://user-images.githubusercontent.com/9300063/119378148-e2ec9980-bcf8-11eb-8d37-72ea9c70f6a4.mp4

**Comment by W567** [comment]
@knorth55 The image color is also weird during my testing, but the detecting should have been successful. I've did some tests and found the weird color is caused by `cv2_to_imgmsg(frame, encoding='rgb8')`, when I changed rgb8 to bgr8, the color became normal. In this case, the hand detection code part also needs some modification, and I'll do it tomorrow as soon as possible. Currently I have no ideas why it didn't work for you, it may caused by the encoding part or anything else, I'll do the test tomorrow and figure out what's wrong with it. Sorry for the inconvenience

**Pull request closed without merging**
