### PR TITLE
[jsk_perception] Fix unconfigured cmake and manifest

### PR DESCRIPTION
**Pull request by wkentaro**
Modified:
  - jsk_perception/CMakeLists.txt
  - jsk_perception/package.xml

### CODE REVIEW

**Comment by wkentaro** [comment]
**before**
```
% catkin lint .
jsk_perception: error: unconfigured build_depend on 'robot_self_filter'
jsk_perception: error: unconfigured build_depend on 'rosbuild'
jsk_perception: error: unconfigured build_depend on 'rostest'
jsk_perception: error: unconfigured build_depend on 'rospy'
jsk_perception: error: unconfigured build_depend on 'angles'
jsk_perception: error: unconfigured build_depend on 'posedetection_msgs'
jsk_perception: error: unconfigured build_depend on 'roseus'
catkin_lint: checked 1 packages and found 7 problems
catkin_lint: 8 warnings have been ignored. Use -W1 to see them
catkin_lint: 25 notices have been ignored. Use -W2 to see them
```

**after**
```
% catkin lint .
catkin_lint: checked 1 packages and found 0 problems
catkin_lint: 10 warnings have been ignored. Use -W1 to see them
catkin_lint: 24 notices have been ignored. Use -W2 to see them
```

**Comment by garaemon** [comment]
robot_self_filter is optional.

**Comment by wkentaro** [comment]
> robot_self_filter is optional. 

why?

**Comment by wkentaro** [comment]
maybe I understood what you mean now.
you mean robot-self-filter is not released on hydro.

**Comment by garaemon** [comment]
> you mean robot-self-filter is not released on hydro.
>  Hide all checks

yes

**Pull request merged**
