### PR TITLE
Update attention_clipper.md

### PR DESCRIPTION
**Pull request by MiyabiTane**
クリップした領域内の点群の出し方について加筆しました。

### CODE REVIEW

**Comment by knorth55** [comment]
I made PR to this PR.
Please check it, and merge it if it is OK
https://github.com/MiyabiTane/jsk_recognition/pull/1

**Comment by knorth55** [comment]
@MiyabiTane why did you close this PR?

**Comment by MiyabiTane** [comment]
@knorth55 
I have checked and merged your PR.
Should I make PR for master again?

**Comment by knorth55** [comment]
this is a PR for `jsk-ros-pkg/jsk_recognition` and it is not merged yet.
(my PR is for `MiyabiTane/jsk_recognition`)
we have to wait for @k-okada merging this.

**Comment by MiyabiTane** [comment]
I am sorry I didn't understand. Thank you for your explanation.
I have reopened this PR.

**Comment by knorth55** [comment]
Good! 👍

**Comment by knorth55** [comment]
@k-okada it passed travis test. can you please merge this PR?

**Comment by knorth55** [comment]
@k-okada 
I made a new label, PR/WaitForMaintainerCheck.
This label means:
- PR is reviewed by related people
- PR passed travis test
- PR is waiting for check by a maintainer (@k-okada)

So, PR label should be transferred as below:
```
PR/PleaseFix and so on
  -> (student's review, travis success) -> PR/WaitForMaintainerCheck
  -> (@k-okada review, travis success) -> PR/MergeOK
  -> (travis success) -> PR merge
```
I hope this label may help your package maintenance.

**Pull request merged**
