### PR TITLE
[doc][jsk_pcl_ros] Fix document

### PR DESCRIPTION
**Pull request by taichiH**
color_histogram_matcher node subscribe 4 topics 
```
~input (sensor_msgs::PointCloud2)
~input_indices (jsk_recognition_msgs::ClusterPointIndices)
~input_reference_cloud (sensor_msgs::PointCloud2)
~input_reference (jsk_recognition_msgs::ColorHistogram)
```

Although the code has a color histogram Subscriber, the document has an omission of `~input_reference` input topic.

https://github.com/jsk-ros-pkg/jsk_recognition/blob/507738a1acebe38ba7c1c29845b80f35240561c0/jsk_pcl_ros/src/color_histogram_matcher_nodelet.cpp#L81-L84

### CODE REVIEW

**Comment by YutoUchimi** [comment]
@taichiH 
Can you also fix `Publishing Topic`?
- Message type: `jsk_pcl_ros::XXX` -> `jsk_recognition_msgs::XXX`
- Add document for `~best_match` and `~coefficient_points`.

**Comment by YutoUchimi** [comment]
And can you please add sample and test for this node when you have time?

It seems that `jsk_pcl_ros/launch/organized_multi_plane_segmentation.launch`, which is a "sample" launch file according to this doc, requires input point cloud by each user.
It's ok because this is located under `launch/`, but a sample should run standalone.
i.e. Please create a new sample file which includes `rosbag_play` or `pcl_ros/pcd_to_pointcloud` or something like that to input the point cloud to `ColorHistogramMatcher`.

**Comment by taichiH** [comment]
@YutoUchimi  
I fixed documentation about publish topic.

I also create sample launch file you mentioned and create new PR https://github.com/jsk-ros-pkg/jsk_recognition/pull/2429, please review.

**Comment by k-okada** [comment]
wait for #2429

**Pull request merged**
