### PR TITLE
[jsk_recognition_utils] Add label color utility function

### PR DESCRIPTION
**Pull request by wkentaro**
## Summary 

- Generate colormap from number of labels (`jsk_recognition_utils.color.labelcolormap`)
- Use above function in jsk_perception nodes.
- Add test for the changed nodes.

## Validation

frame0000

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
sorry , need rebase

**Comment by wkentaro** [comment]
Please merge this.

**Comment by wkentaro** [comment]
Please merge this.

**Comment by jinfagang** [comment]
@wkentaro  How to make a label color map in my map? I want change the default color showing in rviz with jsk bounding box message

**Comment by wkentaro** [comment]
@jinfagang Please open an issue in https://github.com/jsk-ros-pkg/jsk_visualization for more detail.

The color of bounding_box_array is determined here:

https://github.com/jsk-ros-pkg/jsk_visualization/blob/272b878939689408a34c1405c5c303b06d0fdf15/jsk_rviz_plugins/src/bounding_box_display_common.h#L84-L88

and `jsk_topic_tools::colorCategory20` is defined here:

https://github.com/jsk-ros-pkg/jsk_common/blob/27f26b89386d8ee6bd9dac442819f4337ee8935c/jsk_topic_tools/src/color_utils.cpp#L40

**Pull request merged**
