### PR TITLE
Implement OverlayImageColorOnMono: nodelet that overlay color image on mono image

### PR DESCRIPTION
**Pull request by wkentaro**
cc @yuyu2172

### CODE REVIEW

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
@yuyu2172 Could you update sample image ? I think you have nice sample image with object recognition (over lay posterity image over input image)

**Comment by yuyu2172** [comment]
target_posterior_image_in_bin

Float image represents how likely pixels are assigned to the category 'ball'.

**Comment by k-okada** [comment]
very nice image, but please update sample image, but we want to remove left 'start bar' ,  you can choose 'grab current screen option' or move the rqt image viewer and grub again
hoge

**Comment by k-okada** [comment]
nice, but does the image is upside down?

--
◉ Kei Okada

**Comment by k-okada** [comment]
also bettor to remove mask from image, because this is to explain overlay,
not mask function.

--
◉ Kei Okada

**Comment by yuyu2172** [comment]
@k-okada 
Probability likelihood of the object is calculated only in masked region, so we can only use masked image for this example.

**Comment by wkentaro** [comment]
> @k-okada 
Probability likelihood of the object is calculated only in masked region, so we can only use masked image for this example.

In that case, why not overlay the posterior image on the masked color image?

**Comment by yuyu2172** [comment]
that makes sense

**Comment by yuyu2172** [comment]
screenshot from 2016-05-31 16 21 11

**Comment by wkentaro** [comment]
1. Please add an image on which the color image is overlaid
2. Please update the topic name.

**Comment by yuyu2172** [comment]
screenshot from 2016-05-31 17 32 46

**Comment by yuyu2172** [comment]
screenshot from 2016-05-31 17 35 58

**Comment by k-okada** [comment]
!!!! Great!

Can you add more example? Since this example shows red ball which seems very easy to recognize simple color filter so I'm interested in more difficult target

**Comment by k-okada** [comment]
!!!! Great!

Can you add more example? Since this example shows red ball which seems very easy to recognize simple color filter so I'm interested in more difficult target

**Comment by k-okada** [comment]
Can you recognize the book on left side?

**Comment by yuyu2172** [comment]
Likelihood image for the book is not as clear as the image for the balls.
I think that the image for the balls is a good example for this node.

screenshot from 2016-05-31 17 35 58

**Comment by yuyu2172** [comment]
The picture above is just an internal state of the segmentation algorithm.
Segmented 


frame0000

**Comment by wkentaro** [comment]
Please merge this.

**Pull request merged**
