### PR TITLE
Fix configuration of jsk_pcl_ros

### PR DESCRIPTION
**Pull request by k-okada**
rewrite #1828

1. just change the order in find_package
2. do not have to add genmsg to build_depend
3. do not add 'missing components' in find package (https://github.com/jsk-ros-pkg/jsk_recognition/pull/1828/commits/c54d279c3c689d649e0e5ce6e6423911639686f0)

by the wey, why did you add these missing components? did `catkin_lint` said so?

- Missing installation of executables
- Fix missing dependency declaration of jsk_pcl_ros
- Fix order of components in find_package of jsk_pcl_ros

### CODE REVIEW

**Comment by wkentaro** [comment]
> by the wey, why did you add these missing components? did catkin_lint said so?

Yes. All dependencies that are listed as `build_depend` in `package.xml` should be listed in `find_package`, right?

**Comment by k-okada** [comment]
I think catkin_lint assuming that all packages in build_depends has
different <PACKAGE>_INLCUDE_DIRS/LIBRARIES, that we need to add them to
find_package,
If we can compile current code with current find_package, i think we can
remove packages from build_depend, instead of adding packages find_package.

--
◉ Kei Okada

**Comment by wkentaro** [comment]
Ok, so you'd like to remove the declarations in package.xml.

**Comment by k-okada** [comment]
yes, always try to reduce size of sources
13. ``Perfection (in design) is achieved not when there is nothing more to add, but rather when there is nothing more to take away.''  http://cruel.org/freeware/cathedral.html#6

**Pull request merged**
