### PR TITLE
Make the tests pass and add TODO for stabilizing

### LINKED ISSUE #1882: List of rostest that is unstable on Travis/Jenkins testing
## Format

- test name (fixer): log url

## List

- [x] jsk_pcl_ros/color_based_region_growing_segmentation.test:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/160671742/log.txt
```
jsk_pcl_ros/test_results/jsk_pcl_ros/rosunit-test_color_based_region_growing_segmentation.xml: 1 tests, 0 errors, 1 failures
```

- [x] jsk_perception/sklearn_classifier.test: https://s3.amazonaws.com/archive.travis-ci.org/jobs/160671743/log.txt
```
jsk_perception/test_results/jsk_perception/rosunit-test_sklearn_classifier.xml: 1 tests, 0 errors, 1 failures
```

- [x] jsk_pcl_ros_utils/cluster_point_indices_to_point_indices.test (@wkentaro): https://s3.amazonaws.com/archive.travis-ci.org/jobs/160671744/log.txt
```
jsk_pcl_ros_utils/test_results/jsk_pcl_ros_utils/MISSING-rostest-test_point_indices_to_cluster_point_indices.xml: 1 tests, 0 errors, 1 failures
```

- [x] jsk_pcl_ros/organized_pointcloud_to_point_indices.test (@wkentaro): https://s3.amazonaws.com/archive.travis-ci.org/jobs/160671744/log.txt
```
jsk_pcl_ros/test_results/jsk_pcl_ros/MISSING-rostest-test_test_organized_pointcloud_to_point_indices.xml: 1 tests, 0 errors, 1 failures
```

- [x] jsk_perception.rosunit-test_label_image_decomposer/test_published: https://s3.amazonaws.com/archive.travis-ci.org/jobs/165166786/log.txt

- [x] jsk_perception/test_results/jsk_perception/rosunit-test_bing.xml: 1 tests, 0 errors, 1 failures

### PR DESCRIPTION
**Pull request by wkentaro**
Close #1882 

- [x] Comment out unstable tests
- ~~Stabilize them~~ (maybe it should be TODO at this time)

I'm doing some tests of tests ;) 
screen shot 2016-10-06 at 9 52 43 pm
https://github.com/wkentaro/jsk_recognition/branches

### CODE REVIEW

**Comment by wkentaro** [comment]
The reason of `MISSING-...xml` is below, maybe because of parallel building?
```
[jsk_pcl_ros_utils:make] [ROSUNIT] Outputting test results to /workspace/ros/ws_jsk_recognition/build/jsk_pcl_ros_utils/test_results/jsk_pcl_ros_utils/rostest-test_point_indices_to_cluster_point_indices.xml




                                                                                
[jsk_pcl_ros_utils:make] Traceback (most recent call last):



                                                                                
[jsk_pcl_ros_utils:make]   File "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest", line 36, in <module>



                                                                                
[jsk_pcl_ros_utils:make] Traceback (most recent call last):



                                                                                
[jsk_pcl_ros_utils:make]   File "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest", line 36, in <module>



                                                                                
[jsk_pcl_ros_utils:make]     rostestmain()



                                                                                
[jsk_pcl_ros_utils:make]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 273, in rostestmain



                                                                                
[jsk_pcl_ros_utils:make]     rostestmain()



                                                                                
[jsk_pcl_ros_utils:make]       File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 273, in rostestmain



                                                                                
[jsk_pcl_ros_utils:make] _main()



                                                                                
[jsk_pcl_ros_utils:make]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 167, in rostestmain



                                                                                
[jsk_pcl_ros_utils:make]     _main()



                                                                                
[jsk_pcl_ros_utils:make]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 167, in rostestmain



                                                                                
[jsk_pcl_ros_utils:make]     results_file = xmlResultsFile(pkg, outname, is_rostest, env=env)



                                                                                
[jsk_pcl_ros_utils:make]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/core.py", line 102, in xml_results_file



                                                                                
[jsk_pcl_ros_utils:make]         raise IOError("cannot create test results directory [%s]. Please check permissions."%(test_dir))



                                                                                
[jsk_pcl_ros_utils:make] results_file = xmlResultsFile(pkg, outname, is_rostest, env=env)



                                                                                
[jsk_pcl_ros_utils:make] IOError  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/core.py", line 102, in xml_results_file



                                                                                
[jsk_pcl_ros_utils:make] : cannot create test results directory [/workspace/ros/ws_jsk_recognition/build/jsk_pcl_ros_utils/test_results/jsk_pcl_ros_utils]. Please check permissions.



                                                                                
[jsk_pcl_ros_utils:make]     raise IOError("cannot create test results directory [%s]. Please check permissions."%(test_dir))



                                                                                
[jsk_pcl_ros_utils:make] IOError: cannot create test results directory [/workspace/ros/ws_jsk_recognition/build/jsk_pcl_ros_utils/test_results/jsk_pcl_ros_utils]. Please check permissions.
```

**Comment by wkentaro** [comment]
@k-okada Some of the unstable tests seems **really** unstable.
So I'm planning comment out them at this time, and will fix them as TODO.
Do you agree?

cc @mmurooka

**Comment by k-okada** [comment]
if you set todo, please assign that issue to someone with deadline, if you
can not, please give me a time to make an effort to fix this, once we
accept this strategy, I'm afraid that we're moving to disable all tests,
for example, label decomposer is actively used and I think it is very
dangerous to disable that. Please also notify we're in trouble on maintain
the code to the both node code author and test code author.

Cc: https://github.com/jsk-ros-pkg/jsk_recognition/pull/1891

--
◉ Kei Okada


2016-10-06 21:56 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
Author of most of the code is me @wkentaro.
And you @k-okada for color_based_region_growing_segmentation.test.

**Comment by wkentaro** [comment]
> if you set todo, please assign that issue to someone with deadline, if you
can not, please give me a time to make an effort to fix this, once we
accept this strategy, I'm afraid that we're moving to disable all tests,
for example, label decomposer is actively used and I think it is very
dangerous to disable that. Please also notify we're in trouble on maintain
the code to the both node code author and test code author.

Yeah, you're right, but I and you are active and I think I can fix this problem until next week's lab meeting.

**Comment by wkentaro** [comment]
I'm just sorry for contributors who are restarting many times the job.
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1893
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1893
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1887
https://github.com/jsk-ros-pkg/jsk_recognition/pull/1886

**Comment by k-okada** [comment]
> And you @k-okada for color_based_region_growing_segmentation.test.

Yes I know, that's why I'm working on #1891
If you can fix this within a few days, that's very nice. If @mmurooka can
not wait until then, we welcome him to working on this issue.


--
◉ Kei Okada


2016-10-06 22:17 GMT+09:00 Kentaro Wada <notifications@github.com>:

**Comment by wkentaro** [comment]
Closed via https://github.com/jsk-ros-pkg/jsk_recognition/pull/1897

**Pull request closed without merging**
