### PR TITLE
[jsk_perception] Visualization node for rosmsg jsk_recognition_utils/ClassificationResult

### PR DESCRIPTION
**Pull request by wkentaro**
image

### CODE REVIEW

**Comment by wkentaro** [comment]
```
17:26:03 
                                                                                
[jsk_perception:make] FAILURE: Test Fixture Nodes ['imagesift'] failed to launch

17:26:03 

                                                                                
[jsk_perception:make]   File "/usr/lib/python2.7/unittest/case.py", line 331, in run

17:26:03 
                                                                                
[jsk_perception:make]     testMethod()

17:26:03 
                                                                                
[jsk_perception:make]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn

17:26:03 
                                                                                
[jsk_perception:make]     self.assert_(not failed, "Test Fixture Nodes %s failed to launch"%failed)

17:26:03 
                                                                                
[jsk_perception:make]   File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue

17:26:03 
                                                                                
[jsk_perception:make]     raise self.failureException(msg)

```

**Comment by wkentaro** [comment]
Needs #1642

**Comment by wkentaro** [comment]
```
+ catkin build -i --summarize --no-status -p4 --make-args -j8

----------------------------------------------------------------------

Profile:                     default

Extending:             [env] /opt/ros/hydro

Workspace:                   /workspace/ros/ws_jsk_recognition

Source Space:       [exists] /workspace/ros/ws_jsk_recognition/src

Build Space:        [exists] /workspace/ros/ws_jsk_recognition/build

Devel Space:        [exists] /workspace/ros/ws_jsk_recognition/devel

Install Space:     [missing] /workspace/ros/ws_jsk_recognition/install

DESTDIR:                     None

----------------------------------------------------------------------

Isolate Develspaces:         False

Install Packages:            False

Isolate Installs:            False

----------------------------------------------------------------------

Additional CMake Args:       None

Additional Make Args:        None

Additional catkin Make Args: None

Internal Make Job Server:    True

----------------------------------------------------------------------

Whitelisted Packages:        None

Blacklisted Packages:        None

----------------------------------------------------------------------

Workspace configuration appears valid.

----------------------------------------------------------------------

Found '16' packages in 0.2 seconds.

Starting ==> dynamic_tf_publisher

Starting ==> image_view2

Starting ==> jsk_data

Starting ==> jsk_network_tools

Finished <== jsk_data                [ 2.6 seconds ]

Starting ==> jsk_recognition_msgs

Finished <== dynamic_tf_publisher    [ 7.1 seconds ]

Starting ==> jsk_tilt_laser

Finished <== jsk_network_tools       [ 8.5 seconds ]

Starting ==> jsk_tools

Finished <== jsk_tilt_laser          [ 5.4 seconds ]

Starting ==> virtual_force_publisher

Finished <== jsk_tools               [ 6.1 seconds ]

Starting ==> jsk_topic_tools

Finished <== image_view2             [ 15.4 seconds ]

Finished <== jsk_recognition_msgs    [ 12.9 seconds ]

Starting ==> checkerboard_detector

Finished <== virtual_force_publisher [ 4.2 seconds ]

Finished <== checkerboard_detector   [ 5.1 seconds ]

Finished <== jsk_topic_tools         [ 9.7 seconds ]

Starting ==> jsk_recognition_utils

Starting ==> multi_map_server

Finished <== multi_map_server        [ 3.7 seconds ]

Finished <== jsk_recognition_utils   [ 11.7 seconds ]

Starting ==> jsk_pcl_ros_utils

Starting ==> jsk_perception

Finished <== jsk_pcl_ros_utils       [ 41.5 seconds ]

Starting ==> jsk_pcl_ros

Failed <== jsk_perception          [ 51.0 seconds ]

Finished <== jsk_pcl_ros             [ 1 minute and 46.0 seconds ]

[build] There were '1' errors:



Failed to build package 'jsk_perception' because the following command:



# Command to reproduce:

cd /workspace/ros/ws_jsk_recognition/build/jsk_perception && /workspace/ros/ws_jsk_recognition/build/jsk_perception/build_env.sh /usr/bin/make --jobserver-fds=3,4 -j; cd -



# Path to log:

cat /workspace/ros/ws_jsk_recognition/build/build_logs/jsk_perception.log



Exited with return code: 2





Build summary:

 Successful checkerboard_detector   Successful dynamic_tf_publisher   

 Successful image_view2             Successful jsk_data               

 Successful jsk_network_tools       Successful jsk_pcl_ros            

 Successful jsk_pcl_ros_utils       Successful jsk_recognition_msgs   

 Successful jsk_recognition_utils   Successful jsk_tilt_laser         

 Successful jsk_tools               Successful jsk_topic_tools        

 Successful multi_map_server        Not built  resized_image_transport

 Successful virtual_force_publisher



Failed packages:

 Failed     jsk_perception         



[build] Successfully built '14' packages, failed to build '1' packages, and did not try to build '1' packages.

[build] Runtime: 3 minutes and 4.0 seconds

++ error
```

**Comment by wkentaro** [comment]
Please merge this.

**Comment by k-okada** [comment]
to put the image within the paper, better to use  bold and non-italic,  font

**Pull request merged**
