### PR TITLE
Add bbox test for cpi decomposer.

### PR DESCRIPTION
**Pull request by weiqiyang**
Test for detecting the bug fixed in #2369 
Travis test of this PR will fail, and will become succeeded in #2369

### CODE REVIEW

**Comment by weiqiyang** [comment]
While trying to get bounding box from point cluster indices masked by mask rcnn segmentation, `cluster_point_indices_decomposer` node failed to calculate the bounding box, and published a bounding box array of boxes with nan value in poses.

After reading the source code, the bug was thought to occurred because the input point clouds contains nan points, but `cluster_point_indices_decomposer` was taking the input as is dense without checking. Thus the nan points are not removed before decomposed.

Below is a part of my launch file:
```
  <node name="cluster_point_indices_decomposer"
	      pkg="jsk_pcl_ros" type="cluster_point_indices_decomposer">
    <remap from="~input" to="$(arg INPUT_CLOUD)" />
    <remap from="~target" to="okashi_detector/output/cluster_indices" />
 <!--
    <remap from="~input_polygons" to="multi_plane_estimate/output_polygon" />
    <remap from="~input_coefficients" to="multi_plane_estimate/output_coefficients" />
-->
    <rosparam>
      approximate_sync: true
      queue_size: 200
      use_pca: true
      align_boxes: true
      align_boxes_with_plane: false
      target_frame_id: base_link
    </rosparam>
  </node>
```

**Comment by pazeshun** [comment]
Test correctly failed in both indigo and kinetic.
```
[ROSTEST]-----------------------------------------------------------------------


                                                                                



                                                                                
[jsk_pcl_ros.rosunit-test_cluster_point_indices_decomposer_bbox/test_bbox][passed]


                                                                                
[jsk_pcl_ros.rosunit-test_cluster_point_indices_decomposer_bbox_align_boxes_with_frame/test_bbox][passed]


                                                                                
[jsk_pcl_ros.rosunit-test_cluster_point_indices_decomposer_bbox_pca/test_bbox][FAILURE]


                                                                                
pose.position.x is nan


                                                                                
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run


                                                                                
    testMethod()


                                                                                
  File "/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/test/test_cluster_point_indices_decomposer_bbox.py", line 33, in test_bbox


                                                                                
    'pose.position.x is nan')


                                                                                
  File "/usr/lib/python2.7/unittest/case.py", line 418, in assertFalse


                                                                                
    raise self.failureException(msg)


                                                                                
--------------------------------------------------------------------------------
```

**Comment by YutoUchimi** [comment]
@pazeshun Well, judged from https://travis-ci.org/jsk-ros-pkg/jsk_recognition/jobs/461734840, it seems that travis test fails correctly as we expected.
```
[ROSUNIT] Outputting test results to /workspace/ros/ws_jsk_recognition/build/jsk_pcl_ros/test_results/jsk_pcl_ros/rostest-test_test_cluster_point_indices_decomposer_bbox.xml
[ INFO] [1543578599.028501166]: Initializing nodelet with 4 worker threads.
[ INFO] [1543578606.314221543]: Initializing nodelet with 4 worker threads.
[ INFO] [1543578613.809403435]: Initializing nodelet with 4 worker threads.
[ INFO] [1543578620.392918250]: Initializing nodelet with 4 worker threads.
testtest_cluster_point_indices_decomposer_bbox ... ok
testtest_cluster_point_indices_decomposer_bbox_align_boxes_with_frame ... ok
testtest_cluster_point_indices_decomposer_bbox_pca ... ok

[ROSTEST]-----------------------------------------------------------------------
                                                                                
[jsk_pcl_ros.rosunit-test_cluster_point_indices_decomposer_bbox/test_bbox][passed]
[jsk_pcl_ros.rosunit-test_cluster_point_indices_decomposer_bbox_align_boxes_with_frame/test_bbox][passed]
[jsk_pcl_ros.rosunit-test_cluster_point_indices_decomposer_bbox_pca/test_bbox][FAILURE]
pose.position.x is nan
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/workspace/ros/ws_jsk_recognition/src/jsk_recognition/jsk_pcl_ros/test/test_cluster_point_indices_decomposer_bbox.py", line 33, in test_bbox
    'pose.position.x is nan')
  File "/usr/lib/python2.7/unittest/case.py", line 418, in assertFalse
    raise self.failureException(msg)
--------------------------------------------------------------------------------


SUMMARY
 * RESULT: FAIL
 * TESTS: 3
 * ERRORS: 0
 * FAILURES: 1

rostest log file is in /workspace/jsk-ros-pkg/jsk_recognition/log/rostest-477eb99c0a15-3682.log
```

But in https://travis-ci.org/jsk-ros-pkg/jsk_recognition/jobs/461734844, there is another error.
```
[ROSUNIT] Outputting test results to /workspace/ros/ws_jsk_recognition/build/jsk_pcl_ros/test_results/jsk_pcl_ros/rostest-test_test_cluster_point_indices_decomposer_bbox.xml
[ INFO] [1543577811.990583112]: Initializing nodelet with 4 worker threads.
[ INFO] [1543577814.788555094]: Initializing nodelet with 4 worker threads.
[ INFO] [1543577818.081601833]: Initializing nodelet with 4 worker threads.
testtest_cluster_point_indices_decomposer_bbox ... FAILURE!
FAILURE: Test Fixture Nodes ['mask_image_generator', 'mask_image_to_label'] failed to launch
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn
    self.assert_(not failed, "Test Fixture Nodes %s failed to launch"%failed)
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------
testtest_cluster_point_indices_decomposer_bbox_align_boxes_with_frame ... FAILURE!
FAILURE: Test Fixture Nodes ['mask_image_generator', 'mask_image_to_label'] failed to launch
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn
    self.assert_(not failed, "Test Fixture Nodes %s failed to launch"%failed)
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------
testtest_cluster_point_indices_decomposer_bbox_pca ... FAILURE!
FAILURE: Test Fixture Nodes ['mask_image_generator', 'mask_image_to_label'] failed to launch
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/runner.py", line 121, in fn
    self.assert_(not failed, "Test Fixture Nodes %s failed to launch"%failed)
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[ROSTEST]-----------------------------------------------------------------------

[testtest_cluster_point_indices_decomposer_bbox][failed]
[testtest_cluster_point_indices_decomposer_bbox_align_boxes_with_frame][failed]
[testtest_cluster_point_indices_decomposer_bbox_pca][failed]

SUMMARY
 * RESULT: FAIL
 * TESTS: 0
 * ERRORS: 0
 * FAILURES: 3

ERROR: The following tests failed to run:
 * testtest_cluster_point_indices_decomposer_bbox
 * testtest_cluster_point_indices_decomposer_bbox_align_boxes_with_frame
 * testtest_cluster_point_indices_decomposer_bbox_pca

rostest log file is in /workspace/jsk-ros-pkg/jsk_recognition/log/rostest-8420474c0744-78305.log
```

So we may have to fix this...

**Comment by pazeshun** [comment]
> So we may have to fix this...

Oh, I overlooked this. Thanks for your attention.
I also found this error in #2369 , so this error has reproducibility.
(I misjudged and restarted the errored test in #2369 , but this will fail.)

**Comment by pazeshun** [comment]
Oh, I forgot to add test_depend to `jsk_perception`.
This may cause this problem.

**Comment by pazeshun** [comment]
@weiqiyang Sorry, but I pushed https://github.com/jsk-ros-pkg/jsk_recognition/pull/2373/commits/9473d5d2560b945e4f1d1f309af33bc10ebceb1f to your branch.

**Pull request closed without merging**
